### ISSUE TITLE
onDelete events for Image block

### ISSUE THREAD

**Issue by Ashfak-Hossain** [TypeCellOS/BlockNote#1004]
**Describe the bug**
i store images in aws S3, but there is no onDelete action for the image block, which can be use to delete image from the storage. 

**Misc**
- Node version: v22.2.0
- Package manager: npm 10.8.2
- Browser: Google Crome Version 127.0.6533.100 (Official Build) (arm64)

**Comment by YousefED** [comment]
see #482 for discussion
