### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: require() of ES Module 

### ISSUE THREAD

**Issue by odufuwa-segun** [TypeCellOS/BlockNote#1008]
**Describe the bug**
Error when starting nodejs application

<img width="1340" alt="Screenshot 2024-08-14 at 2 55 01 PM" src="https://github.com/user-attachments/assets/dfa7451f-9efc-4661-8a4d-8b759c67d9c8">

node_modules/ts-node/dist/index.js:851
            return old(m, filename);
                   ^
Error [ERR_REQUIRE_ESM]: require() of ES Module node_modules/@blocknote/core/node_modules/rehype-parse/index.js from node_modules/@blocknote/core/dist/blocknote.umd.cjs not supported.
Instead change the require of index.js in node_modules/@blocknote/core/dist/blocknote.umd.cjs to a dynamic import() which is available in all CommonJS modules.
    at require.extensions.<computed> [as .js] (node_modules/ts-node/dist/index.js:851:20)
    at node_modules/@blocknote/core/dist/blocknote.umd.cjs:1:99
    at Object.<anonymous> (node_modules/@blocknote/core/dist/blocknote.umd.cjs:1:2397)
    at require.extensions.<computed> [as .js] (node_modules/ts-node/dist/index.js:851:20)
    at node_modules/@blocknote/server-util/dist/blocknote-server-util.umd.cjs:1:70
    at Object.<anonymous> (node_modules/@blocknote/server-util/dist/blocknote-server-util.umd.cjs:1:487)
    at require.extensions.<computed> [as .js] (node_modules/ts-node/dist/index.js:851:20)
    at Object.<anonymous> (src/yjs.ts:8:23)
    at m._compile (node_modules/ts-node/dist/index.js:857:29)
    at require.extensions.<computed> [as .ts] (node_modules/ts-node/dist/index.js:859:16)
    at Object.<anonymous> (src/socket.ts:4:18)
    at m._compile (node_modules/ts-node/dist/index.js:857:29)
    at require.extensions.<computed> [as .ts] (node_modules/ts-node/dist/index.js:859:16)
    at Object.<anonymous> (src/index.ts:32:21)
    at m._compile (node_modules/ts-node/dist/index.js:857:29)
    at require.extensions.<computed> [as .ts] (node_modules/ts-node/dist/index.js:859:16)
    at phase4 (node_modules/ts-node/dist/bin.js:466:20)
    at bootstrap (node_modules/ts-node/dist/bin.js:54:12)
    at main (node_modules/ts-node/dist/bin.js:33:12)
    at Object.<anonymous> (node_modules/ts-node/dist/bin.js:579:5) {
  code: 'ERR_REQUIRE_ESM'
}
[nodemon] app crashed - waiting for file changes before starting...
Error [ERR_REQUIRE_ESM]: require() of ES Module 

**To Reproduce**
Create Node app with package.json and tsconfig.json

`{
  "name": "App",
  "version": "0.0.1",
  "description": "Collaboration Provider Service(Powered by SocketIO & YJS)",
  "type": "commonjs",
  "devDependencies": {
    "@babel/preset-typescript": "^7.22.5",
    "@types/html-to-text": "^9.0.4",
    "@types/jest": "^29.5.2",
    "@types/node": "^20.8.6",
    "jest": "^29.5.0",
    "nodemon": "^3.0.1",
    "swagger-autogen": "^2.23.7",
    "ts-jest": "^29.1.0",
    "ts-node": "10.9.1",
    "tspec": "^0.1.112",
    "typescript": "^5.2.2"
  },
  "dependencies": {
    "@blocknote/server-util": "^0.15.3",
    "@logtail/node": "^0.4.21",
    "@sentry/node": "^7.103.0",
    "@socket.io/redis-adapter": "^8.2.1",
    "@socket.io/sticky": "^1.0.4",
    "cors": "^2.8.5",
    "dotenv": "^16.1.4",
    "express": "^4.17.2",
    "html-to-text": "^9.0.5",
    "mysql2": "^2.3.3",
    "redis": "^4.6.13",
    "reflect-metadata": "^0.1.13",
    "sha1": "^1.1.1",
    "socket.io": "^4.7.2",
    "typeorm": "0.3.7",
    "y-socket.io": "^1.1.3"
  },
  "scripts": {
    "build": "npm run clean && tsc --project ./",
    "dev": "npm run clean && nodemon --watch 'src/**/*.ts' --ignore 'src/**/*.spec.ts' --exec 'ts-node' src/index.ts",
    "start": "node build/index.js",
    "test": "jest"
  }
}
`
`
{
  "compilerOptions": {
    "lib": [
      "es6"
    ],
    "target": "es2018",
    "module": "commonjs",
    "moduleResolution": "node",
    "outDir": "./build",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "sourceMap": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowImportingTsExtensions": true
  },
  "exclude": [
    "node_modules"
  ]
}
`

src/index.tsx
`
import "reflect-metadata"
import express, {NextFunction, Request, Response} from "express"
import http, {Server} from "http";
import {ServerBlockNoteEditor} from "@blocknote/server-util";

const app = express()
const server = http.createServer(app);

const defaultBlock: any = [{
    type: "paragraph",
    content: "",
}]

app.get('/', (req: Request, res: Response, next: NextFunction) => {
   
        const editor = ServerBlockNoteEditor.create();
        editor.blocksToYXmlFragment(defaultBlock, doc.getXmlFragment("document-store"))

    return response.send('Huh? works..')
})

const startListening = (server: Server, port: number) => {
    server.listen(port)

    console.log(`Servidor iniciado on port: 3030`);
    console.log(`Server started: ${new Date()}`);

}
`

Note: Code is stripped down for simplicity.

**Misc**
- Node version: 18.18.0
- Package manager: npm 9.8.1
- Browser: N/A
- [ ] I'm a [sponsor](https://github.com/sponsors/YousefED) and would appreciate if you could look into this sooner than later 💖

**Comment by YousefED** [comment]
As we define `type: "module"` in package json I think nodejs should load the ES module (`blocknote.js` instead of `blocknote.umd.cjs`). So this seems to be going wrong.

Can you check whether you still have this issue with pure node? (I see you're using ts-node)

**Comment by odufuwa-segun** [comment]
@YousefED I reproduced it on Stackblitz https://stackblitz.com/edit/stackblitz-starters-zvg6g4

**Comment by odufuwa-segun** [comment]
Update!!! I was able to fix it by replacing ts-node(in development) and node(in production) with [tsx](https://tsx.is/).

I also updated my tsconfig.json file, changing compileOptions.target and compileOptions.module to **es2022**

**Comment by natti-tamnoon** [comment]
Running the `server-util` method `tryParseMarkdownToBlocks` in a standard express `NestJS` project  fails with the following error. Nest is `CJS`. Is there no solution here other than running node in `ESM` ?
```
Error [ERR_REQUIRE_ESM]: require() of ES Module /usr/src/app/dist/node_modules/prosemirror-highlight/dist/index.js from /usr/src/app/dist/node_modules/@blocknote/core/dist/BlockNoteSchema-DjDaA2C3.cjs not supported.\",\"Instead change the require of index.js in /usr/src/app/dist/node_modules/@blocknote/core/dist/BlockNoteSchema-DjDaA2C3.cjs to a dynamic import() which is available in all CommonJS modules
```

**Comment by nperez0111** [comment]
@natti-tamnoon I think if you upgrade your node version, then you actually should now be able to require ESM. I'm not sure the actual node version, but it may be behind a flag, I heard about it recently

**Comment by natti-tamnoon** [comment]
@nperez0111 thanks for the tip! You are correct, node did release something for this in `20.19`
https://nodejs.org/en/blog/release/v20.19.0

We were on node 18, and bumping to node 22 LTS appeared to have solved it using version `^0.42.3"` of server-util package and our Nest CJS transpiled build.

However, then when testing against latest version of server util package `^0.44.2` I encountered a different ESM related error, `ERR_PACKAGE_PATH_NOT_EXPORTED` coming from the prosemirror `handlewithcare` package. That dependency looks new to latest release, and I believe the error is saying they don't support CJS export.

Is server util package generally recomended to be run in CJS environment, or only official ESM support? 

Thanks for help

#### Details below from testing.

node v22.20.0

using `tsc` to compile script and running the `dist/index.js`

stack trace
```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in ******/node_modules/@handlewithcare/prosemirror-inputrules/package.json
    at exportsNotFound (node:internal/modules/esm/resolve:313:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:603:13)
    at resolveExports (node:internal/modules/cjs/loader:650:36)
    at Function._findPath (node:internal/modules/cjs/loader:717:31)
    at Function._resolveFilename (node:internal/modules/cjs/loader:1369:27)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1025:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1030:22)
    at Function._load (node:internal/modules/cjs/loader:1192:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:237:24) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

package.json
```
{
  "name": "blocknote-server-util",
  "version": "1.0.0",
  "main": "dist/index.js",
  "license": "MIT",
  "devDependencies": {
    "typescript": "^5.9.3"
  },
  "dependencies": {
    "@blocknote/server-util": "^0.44.2",
    "@tiptap/extensions": "^3.13.0",
    "react": "^19.2.3",
    "react-dom": "^19.2.3"
  }
}
```

tsconfig.json
```
{
  "compilerOptions": {
    "target": "es2017",
    "module": "commonjs",
    "moduleResolution": "Node",
    "esModuleInterop": true,
    "strict": true,
    "skipLibCheck": true,
    "outDir": "dist"
  },
  "include": ["*.ts"]
}
```

index.ts
```
import type { Block } from "@blocknote/core";
import { ServerBlockNoteEditor } from "@blocknote/server-util";

export class BlocknoteMarkdownTransformer {
  private editor: ServerBlockNoteEditor  = ServerBlockNoteEditor.create();


  async markdownToBlocks(markdown: string): Promise<Block[]> {
    if (!markdown) {
      return [];
    }
    const blocks = await this.editor!.tryParseMarkdownToBlocks(markdown);
    return blocks ?? [];
  }

  async blocksToMarkdown(blocks: Block[]): Promise<string> {
    const markdown = await this.editor!.blocksToMarkdownLossy(blocks);
    return markdown ?? "";
  }
}

const test = async () => {
  const transformer = new BlocknoteMarkdownTransformer();
  const markdown = "# Hello, World!\n\nThis is a **bold** text.";
  const blocks = await transformer.markdownToBlocks(markdown);
  console.log(blocks);
};

test();

```

**Comment by nperez0111** [comment]
@natti-tamnoon we don't have any tests for CJS support, and given that the whole ecosystem is moving away from CJS, it is not likely worth it for us to add support for it. If at all possible, it would be ideal for you to just run the server util in an ESM compatible way.

This is what it took for me to get it to run properly based on what you've given me:

<img width="1857" height="543" alt="Image" src="https://github.com/user-attachments/assets/512e5809-f232-43f1-b89b-45775c047448" />

I would happily accept PRs that changes this, but for us to go out of our way to support this is becoming increasingly burdensome.

**Comment by natti-tamnoon** [comment]
@nperez0111 My sample script was purposefully omitting `type: module` to simulate our NestJS build in CJS. 

We likely won't migrate the Nest app to ESM now as it is CJS by default, and not sure the impact of that migration. I understand your maintenance viewpoint as well. We will probably look to extract the blocknote server-util logic into an ESM configuration in dedicated service / lambda.

Thanks again for the help!
