### ISSUE TITLE
Unexpected format block

### ISSUE THREAD

**Issue by lamtuanamc** [TypeCellOS/BlockNote#1014]
**Description:**

When I click the left mouse button 4 times on a line of text to select the entire line and apply formatting, the formatting is not only applied to the selected line but also to the line below it.

https://github.com/user-attachments/assets/1aeed91c-dd62-44a7-b546-a4ceb646254c

**Steps to Reproduce:**

1. Click the left mouse button 4 times on a line of text.
2. Apply any formatting.
3. Observe that the line below is also formatted.

**Expected Behavior:**
Only the selected (highlighted) line should be formatted.

**Actual Behavior:**
The line below the selected line is also formatted, even though it wasn't highlighted.

**Comment by YousefED** [comment]
Thanks. was able to reproduce this on the homepage. It's quite an edge case but will add a bounty in case anyone wants to look into it. What are you building with BlockNote btw?


/bounty 10

**Comment by Bhavyajain21** [comment]
Can I be assigned? @YousefED

**Comment by lamtuanamc** [comment]
I use BlockNote as the editor for a website that provides user guides for my company's products. Thank for your reply.

**Comment by itsdheerajdp** [comment]
@YousefED I'll be working on this issue , can i get to know which part of codebase is responsible for this issue?
