### ISSUE TITLE
Don't automatically create a new empty line when I write something.

### ISSUE THREAD

**Issue by Kacper-Hernacki** [TypeCellOS/BlockNote#1017]
**Describe the bug**
It can be a potential bug or lacking feature. Mainly, there is no shown way to disable creating a new empty line when writing something.

**To Reproduce**
Just type something in a line, then new empty line will be automatically added.

![Untitled video](https://github.com/user-attachments/assets/14e75b67-a2f1-4731-a205-304c15f6beee)

**Comment by YousefED** [comment]
see the `trailingBlock` option: https://www.blocknotejs.org/docs/editor-basics/setup
