### ISSUE TITLE
Feedback for “Suggestion Menus” (removing items)

### ISSUE THREAD

**Issue by anuvo** [TypeCellOS/BlockNote#1018]
Hi there! Is there any way to remove some items from Slash Menu?

**Comment by j7-dev** [comment]
this is how I remove Suggestion Menus
![圖片](https://github.com/user-attachments/assets/54ae3584-5a6f-4744-8189-e1026dfb781e)

**Comment by anuvo** [comment]
@j7-dev Thank you a lot! That pointed me the right direction!

**Comment by YousefED** [comment]
also see https://www.blocknotejs.org/docs/ui-components/suggestion-menus
