### ISSUE TITLE
Can the checkbox from the CheckList be updated with the Shadcn's version instead of the  default HTML one?

### ISSUE THREAD

**Issue by techlism** [TypeCellOS/BlockNote#1023]
![image](https://github.com/user-attachments/assets/5ea24135-e5e3-4134-a572-5a483a34f91e)

Since all the components are based of Shadcn  design language the checkbox should also be in sync.
Just a suggestion..

**Comment by techlism** [comment]
![image](https://github.com/user-attachments/assets/cf6c12b0-67a3-4ea9-85b6-279dc7334882)

**Comment by YousefED** [comment]
At this moment only the UI elements like toolbars (not the blocks themselves) are ported to the different UI libraries. 

For now this is out of scope, you could always create your own custom blocks of course. What are you building with BN?
