### ISSUE TITLE
Selected Blocks does not reflect changes to select block

### ISSUE THREAD

**Issue by m-risto** [TypeCellOS/BlockNote#1029]
**Describe the bug**
The Selected change listener does not reflect changes, when changes on selectedblocks happen.

**To Reproduce**
1. go to https://www.blocknotejs.org/examples/basic/selection-blocks
2. Select a paragraph
3. Change with formatting toolbar the type to heading
4. See that the type in selected blocks does not change

**Misc**
- Node version:
- Package manager:
- Browser: 
- [x] I'm a [sponsor](https://github.com/sponsors/YousefED) and would appreciate if you could look into this sooner than later 💖

**Comment by Kashifwahaj** [comment]
@m-risto, it's not changing immediately, but if you click on the text again, the type updates correctly. So, you want it to reflect immediately after changing a paragraph to a heading using the toolbar, right?

**Comment by matthewlipski** [comment]
You should use the same callback in both the `onSelectionChange` and `onChange` listeners, that should fix it. You can also use `useEditorContentOrSelectionChange` which combines both into a single React hook.
