### ISSUE TITLE
Support Vue3?

### ISSUE THREAD

**Issue by HalleyGao** [TypeCellOS/BlockNote#104]
Is so great. May you support vue3?

**Comment by howtopick** [comment]
same ask

**Comment by Achrou** [comment]
+1

**Comment by YousefED** [comment]
Hi!

Thanks for sharing your interest. As the UI components are written in React, there's two ways we could work on this:

1) recreate UI components completely in Vue. This would have the disadvantage of needing to maintain 2 UI interfaces
2) have the Vue implementation for now bridge to the React components. This mean there will be a dependency on React as well.

I think option 2 is feasible at the moment. Would this be a ok for you?

**Comment by howtopick** [comment]
> 1. recreate UI components completely in Vue. 
Hi!
I'm trying the first one, but still encountered some difficulties, eg: I'm trying to create my slashMenu extension by SlashMenuExtension, but don't know how to create a SuggestionsMenuFactory use vue, so ask a simple example for this.
Many thanks！

**Comment by YousefED** [comment]
We're working on a website with documentation. This page should help to explain how to integrate without React: https://www.blocknotejs.org/docs/vanilla-js

**Comment by ManUtopiK** [comment]
Hi! I would like to use it in Vue.
I'm trying vanilla-js but nothing appear on the screen :/

In the console :
![image](https://user-images.githubusercontent.com/188172/224762005-c8e09951-b8ae-469a-9200-4fdcde45fb7a.png)

But the dom is not filled. There is still the root div.

**Comment by YousefED** [comment]
@ManUtopiK did you pass `parentElement` when creating the editor?

**Comment by ManUtopiK** [comment]
I just run the vanilla-js example.

**Comment by ManUtopiK** [comment]
As I said, the console output informs that the editor is well created.

I tried to add options without success :
```
_tiptapOptions: {
    content: 'Some content',
    autofocus: true,
  }
```

Fun fact, in the devtools console, i can store the editor in the temp1 variable and get the content :
![image](https://user-images.githubusercontent.com/188172/225090986-4f8b56ac-de55-49ac-9c6b-8ba5e864308f.png)

**Comment by ManUtopiK** [comment]
Awesome. It works !
Have you started a branch with Vue.js ?

**Comment by ManUtopiK** [comment]
Ok, I just created a working branch with vue3 #130 !

**Comment by YousefED** [comment]
Actually, I just realized we have "option 2" (bridge to React) already working for the website, which is based on Vitepress / Vue.

I figured everyone who's following this thread might be interested in this. You can see the approach here:

https://github.com/YousefED/BlockNote/tree/main/packages/website/docs/.vitepress/theme/components/Examples/BlockNote

**Comment by ManUtopiK** [comment]
Hey!

I started a vue3 branch here #130.
BlockSideMenu and SlashMenu work pretty well, and fully customizable with slots !

For now, we can just write the main component like this to override the parts with custom components :
```vue
<BlockNoteView v-model="content">
  <template #BlockSideMenu-AddBlock="{ staticParams }">
    <button @click="staticParams.addBlock()">+</button>
  </template>

  <template #SlashMenuItem-Heading="{ menu, selected, onClick }">
    <button @click="onClick()" :style="selected && 'font-weight: bold;'">Slot {{ menu.name }}</button>
  </template>
</BlockNoteView>
```

I'm so satisfied with the work I've done ! :smile: 
I experiment along I code, but I think it goes to the right direction.
So, I tried [in this branch](https://github.com/ManUtopiK/BlockNote/tree/packages/vue) to move the components from `examples/vue` to its own package in `packages/vue`. But thing goes wrong. I'm struggling with vite and lerna. I need help to do that...

What do you think how it goes ? What about working with slots ?
It Missing Hyperlink and FormattingToolbar. Feel free to contribute :)

**Comment by YousefED** [comment]
@ManUtopiK Looks promising! I'm not that much of a Vue expert, but seems smart to use slots. I'll discuss more in your PR so that we can keep this thread clean
