### ISSUE TITLE
Sublime Text 3 builder reports errors in the presence of @types/parse5

### ISSUE THREAD

**Issue by HenrikBechmann** [TypeCellOS/BlockNote#1056]
**Describe the bug**
<what's going wrong!?>
FYI Sublime Text 3 builder reports errors in the presence of @types/parse5

... but no errors are reported in webpack build

**To Reproduce**
<clear steps to reproduce are super helpful! Best is to provide an online sandbox, [click to create one](https://stackblitz.com/github/TypeCellOS/BlockNote/tree/main/examples/01-basic/01-minimal?file=App.tsx)>
build in latest sublime text 3
**Misc**
- Node version: 20.5.1
- Package manager: webpack
- Browser:  Chrome Mac
- [ ] I'm a [sponsor](https://github.com/sponsors/YousefED) and would appreciate if you could look into this sooner than later 💖

I was able to resolve the problem by removing @types/parse5 from node_modules (but now webpack reports @types/parse5 as MISSING)

The errors reported by sublime text are 
```
../../../../node_modules/rehype-parse/node_modules/hast-util-from-parse5/lib/index.d.ts(19,54): error TS2694: Namespace '"/Users/henrikbechmann/Projects/tribalopolis-dev/node_modules/@types/parse5/index"' has no exported member 'DefaultTreeAdapterMap'.
../../../../node_modules/rehype-parse/node_modules/hast-util-from-parse5/lib/index.d.ts(20,50): error TS2694: Namespace '"/Users/henrikbechmann/Projects/tribalopolis-dev/node_modules/@types/parse5/index"' has no exported member 'Token'.
../../../../node_modules/rehype-parse/node_modules/hast-util-from-parse5/lib/index.d.ts(21,43): error TS2694: Namespace '"/Users/henrikbechmann/Projects/tribalopolis-dev/node_modules/@types/parse5/index"' has no exported member 'Token'.
```

**Comment by YousefED** [comment]
Unfortuantely we can't look into specific editor issues. You could try to make sure your editor is using a recent version of TS
