### ISSUE TITLE
Copy to Clipboard Error in Firefox

### ISSUE THREAD

**Issue by luukbox** [TypeCellOS/BlockNote#1063]
**Describe the bug**
Firefox does not support the async Clipboard API, causing an error when attempting to copy content from the editor.

**To Reproduce**
- Open [BlockNote](https://www.blocknotejs.org/) using Firefox
- Attempt to copy any text from the editor
- `Uncaught (in promise) DOMException: Modifications are not allowed for this document` in the console

**Workaround**
I noticed that [createInternalHTMLSerializer](https://github.com/TypeCellOS/BlockNote/blob/459a07439d32d287e7a535c91e6b8cffd7e66967/packages/core/src/api/exporters/html/internalHTMLSerializer.ts#L43) and [cleanHTMLToMarkdown](https://github.com/TypeCellOS/BlockNote/blob/459a07439d32d287e7a535c91e6b8cffd7e66967/packages/core/src/api/exporters/markdown/markdownExporter.ts#L15) aren't actually async. Therefore, it seems like [selectedFragmentToHTML](https://github.com/TypeCellOS/BlockNote/blob/459a07439d32d287e7a535c91e6b8cffd7e66967/packages/core/src/api/exporters/copyExtension.ts#L13C16-L13C38) could be converted to a synchronous function by removing the call to `initializeESMDependencies`.

In our environment, I was able to do this and tested it successfully with a custom copyToClipboard extension while disabling the default one.

That said, I'm unsure of the exact circumstances when these dependencies are required, or their purpose, so I'm not certain if this is a universally viable solution.

For anyone interested, here is a [StackBlitz example](https://stackblitz.com/edit/github-n9nmex?file=App.tsx) demonstrating the workaround.

**Comment by matthewlipski** [comment]
Awesome, thanks for providing your code! We did notice this was an issue when first implementing copy/paste but couldn't find a workaround at the time (hence why e2e tests for copy/paste on Firefox are disabled), so even if it requires tweaking it's great to have a something to reference for a fix.

**Comment by Dartoxian** [comment]
Thanks @luukbox - this workaround works for me. One minor change I needed was to use `const editor: typeof schema.BlockNoteEditor` as I'm using a custom schema.

**Comment by carlonicora** [comment]
@Dartoxian I tried the same workaroud, but it does not work for me. Is there anything specific you do to make it work?

I have something like this
```
const schema = BlockNoteSchema.create({
    inlineContentSpecs: {
      ...defaultInlineContentSpecs,
    },
  });

  const editor: typeof schema.BlockNoteEditor = useCreateBlockNote({
    schema,
    initialContent: initialContent
      ? (JSON.parse(initialContent) as PartialBlock[])
      : undefined,
    uploadFile: uploadImage,
  });
```
and it still does not work.

Thanks a lot

**Comment by carlonicora** [comment]
Sorry, in 0.15.9 that works!
