### ISSUE TITLE
Coping whole table cell is not possible

### ISSUE THREAD

**Issue by piotrbaldych-cr** [TypeCellOS/BlockNote#1064]
**Describe the bug**
When highlighting whole cell in a table block and pressing CTRL+C error is logged in console, the content of the cell is not copied

```TypeError: Cannot read properties of undefined (reading 'children')```

**To Reproduce**

1. Go to https://www.blocknotejs.org/examples/basic/minimal
2. Add table block
3. Triple click inside of a cell in the table block to highlight it
4. Press CTRL+C

Expected behavior: 
Content of the cell or cell is copied to clipboard and can be pasted elsewhere

Actual behavior:
Content is not copied
Error is logged in console

**Misc**
- Node version: n/a
- Package manager: n/a
- Browser: Chrome 128
- [ ] I'm a [sponsor](https://github.com/sponsors/YousefED) and would appreciate if you could look into this sooner than later 💖

**Comment by izr8809** [comment]
I'm waiting too

**Comment by mjp0** [comment]
Yeah, this is terrible UX and my number 1 gripe right now.

**Comment by matthewlipski** [comment]
Yep tables are a bit rough atm, should have some fixes coming soon, mainly for the selection issues and UX improvements.
