### ISSUE TITLE
Cannot read properties of undefined (reading 'Generic')

### ISSUE THREAD

**Issue by julzheng** [TypeCellOS/BlockNote#1079]
**Describe the bug**
When using `<components.Generic.Menu.Item>` from component context hook `const components = useComponentsContext()!`;
, it complain can't read properties of undefined. I don't know if it's a bug or mishaps in my part.

**To Reproduce**
Just put `<components.Generic.Menu.Item>` into use, and it will show such error.

**Misc**
- Node version: Node 22.4.1
- Package manager: NPM 10.8.1
- Browser: Chrome Version 128.0.6613.119

**Comment by matthewlipski** [comment]
Haven't encountered this issue, make sure you only use `useComponentsContext` inside components that are descendants of `BlockNoteView`, that most likely seems to be the issue
