### ISSUE TITLE
BlockNote doesn't work with Next.js

### ISSUE THREAD

**Issue by antonenko-anton** [TypeCellOS/BlockNote#1083]
The example doesn't work. 

```
"@blocknote/core": "^0.15.7",
"@blocknote/mantine": "^0.15.7",
"@blocknote/react": "^0.15.7",
"next": "^14.2.11",
```

<img width="865" alt="Screenshot 2024-09-17 at 15 01 01" src="https://github.com/user-attachments/assets/d4216147-a170-4403-95ff-46b447d5658d">
<img width="983" alt="Screenshot 2024-09-17 at 15 01 14" src="https://github.com/user-attachments/assets/c348facc-212a-4d88-821c-e04e05d12813">
<img width="703" alt="Screenshot 2024-09-17 at 15 01 08" src="https://github.com/user-attachments/assets/72c7aea8-6e5e-49f7-9385-26e535f143bf">

**Comment by Nostromos** [comment]
I"m having the same issue from a clean install.

**Comment by I-Atlas** [comment]
Have a same issue here

`TypeError: Cannot read properties of undefined (reading 'plugins')`

**Comment by AhmadAlHallak** [comment]
Is there any workaround to get it working for now, even the most basic example in the docs with a completely new NextJS projects doesn't work .
Is there a known working version? I tried downgrading BlockNote but I kept getting the same error!

**Comment by kyen99** [comment]
I'm not sure what is causing this, but I just ran into the same issue after upgrading packages. I rolled them back and now it's working again. In case this helps someone, here are the versions that are working for me:
`
    "@blocknote/core": "^0.14.5",
    "@blocknote/react": "^0.14.6",
    "@blocknote/shadcn": "^0.14.6",
    "next": "14.2.5"
`
