### ISSUE TITLE
Custom block with content-type="none" formatting toolbar appears as small dot

### ISSUE THREAD

**Issue by jehaad1** [TypeCellOS/BlockNote#1093]
**Describe the bug**
When selecting a custom block content-type="none" with no default props (align, text color, bg color), the formatting toolbar appears as a small dot, when it should be hidden

**To Reproduce**
I have this custom hr block with no default values, check this when I select it
<img width="651" alt="image" src="https://github.com/user-attachments/assets/3b0bdc6c-da94-49e1-8e92-65794f7bf647">
Take a closer look at this zoom image
<img width="41" alt="image" src="https://github.com/user-attachments/assets/6f68e649-5f0e-4ff8-a2a0-3e5027d65386">

**Misc**
- Node version: Latest
- Package manager: NPM
- Browser: Arc
- [ ] I'm a [sponsor](https://github.com/sponsors/YousefED) and would appreciate if you could look into this sooner than later 💖

**Comment by matthewlipski** [comment]
Kind of odd since there should already be this CSS in the BlockNote styles that handles this:
```css
.bn-mantine .bn-toolbar:empty {
  display: none;
}
```
Either way, try adding it manually to see if it fixes it

**Comment by jehaad1** [comment]
I tried
.bn-mantine .bn-toolbar {
  @apply !hidden !opacity-0 !bg-transparent;
}
it worked but hide all the formatting toolbars

and I tried
.bn-mantine .bn-toolbar:empty {
  @apply !hidden !opacity-0 !bg-transparent;
}

but sadly it doesn't work (my browser is Arc)

**Comment by jehaad1** [comment]
I came with another solution that's more supported by browsers:
```css
.bn-mantine .bn-toolbar:empty,
.bn-mantine .bn-toolbar:not(:has(*)) {
  @apply !hidden !opacity-0 !bg-transparent;
}
```

Since your code is already in the core of the library css, it doesn't work for me because my browser (Arc) doesn't support ":empty" pseudo-class yet, but support ":not(:has(*))".

you can add it to the library css
