### ISSUE TITLE
JS removing style prop from data while sending to backend

### ISSUE THREAD

**Issue by techAffinate** [TypeCellOS/BlockNote#1096]
**Describe the bug**
While sending the editor.document data to backend(mongoDb) onChange, js is auto removing the style prop as its empty and when user refresh and we fetch the data from backend api, nothing gets displayed as there is not style parameter.  We are using Nextjs, typescript and Mongodb in backend

**To Reproduce**
`"use client";

import { url } from "@/redux/AppReducer/action-types";
import { Block, BlockNoteEditor, PartialBlock } from "@blocknote/core";
import "@blocknote/core/fonts/inter.css";
import { BlockNoteView } from "@blocknote/mantine";
import "@blocknote/mantine/style.css";
import axios from "axios";
import { usePathname } from "next/navigation";
import Cookies from "js-cookie";
import { useEffect, useMemo, useState } from "react";
import { useDispatch } from "react-redux";
import { getsingleNode } from "@/redux/AppReducer/action";

const token = Cookies.get("accessToken");
const headers = {
    Authorization: ⁠ Bearer ${token} ⁠,
    "Content-Type": "application/json",
};

// Save editor data to storage
async function saveToStorage(id: string, data: any) {
    console.log("dc", data.data.content);
    try {
        const response = await axios.patch(⁠ ${url}/nodes/update-node-data/${id} ⁠, data, { headers });
        console.log("Response from server:", response);
    } catch (error: any) {
        console.log("Error message:", error.message);
    }
}

// Load editor content from storage
async function loadFromStorage(id: string, courseID: string) {
    try {
        const response = await axios.post(⁠ ${url}/nodes/get-single-node ⁠, { id, courseID }, { headers });
        const storageString = response.data.data.content;
        console.log("Fetched content:", response);
        // return storageString ? (storageString) : undefined;
    } catch (error: any) {
        console.log("Error loading content:", error);
        return undefined;
    }
}

export default function RichTextNew({ params }: any) {
    const path = usePathname();
    const pathname = path.split("/");
    const dispatch = useDispatch();
    const [initialContent, setInitialContent] = useState<PartialBlock[] | undefined | "loading">("loading");
    const [blocks, setBlocks] = useState<Block[]>([]);

    // Load initial content based on params and pathname
    useEffect(() => {
        const courseID = pathname.includes("view") ? pathname[3] : pathname[2];
        loadFromStorage(params.id, courseID).then((content) => {
            setInitialContent(content);
        })
        // dispatch(
        //     getsingleNode(
        //         params,
        //         pathname.includes("view") ? pathname[3] : pathname[2],
        //         setInitialContent,
        //         () => { }
        //     ) as any
        // );
    }, []);

    // Create the BlockNoteEditor instance
    const editor = useMemo(() => {
        if (initialContent === "loading") {
            return undefined;
        }
        return BlockNoteEditor.create({ initialContent });
    }, [initialContent]);

    // Prevent rendering if editor is still loading
    if (!editor) {
        return "Loading content...";
    }

    // Handle editor changes and save to storage
    return (
        <>
            <BlockNoteView
                editor={editor}
                editable={true}
                theme={"light"}
                onChange={() => {
                    setBlocks(editor.document);
                    // setInitialContent(editor.document)
                    saveToStorage(pathname[3], {
                        courseID: pathname[2],
                        data: { content: editor.document },
                        edited_at: new Date(),
                    });
                }}
            />
            <pre>{JSON.stringify(initialContent, null, 2)}</pre>
        </>
    );
}`

**Comment by matthewlipski** [comment]
This sounds like an issue with how the JSON is being uploaded to the backend - getting `editor.document` preserves the styles, so the issue is probably occurring somewhere else.
