### ISSUE TITLE
Using `editor.updateBlock` while changing the content of the block deletes the children

### ISSUE THREAD

**Issue by mfanselmo** [TypeCellOS/BlockNote#1101]
**Describe the bug**

When using the editor API `editor.updateBlock` and changing the block's content, the children are removed. I think this is unexpected behavior but please let me know if there is a reason for this, I have not looked very into detail in the code

**To Reproduce**

https://github.com/user-attachments/assets/441e3b99-1541-455c-943f-1d8d371c3d2e

https://stackblitz.com/edit/github-7jn7g7?file=SideMenuItems.tsx

**Comment by matthewlipski** [comment]
Nice find! Fortunately it's a one line fix (passing `content` replaces the content of the whole block including children). Will make a PR shortly👍
