### ISSUE TITLE
Manually created collaboration fragment structure and editor deletes all blockcontainer nodes

### ISSUE THREAD

**Issue by kegesch** [TypeCellOS/BlockNote#1102]
**Describe the bug**
I am transitioning from a custom built editor to BlockNote and thus have to migrate the yjs document structure to the one that BlockNote / TipTap uses. 
I build a migration script that creates a fragment with the following structure:
```html
<blockgroup>
  <blockcontainer id="5180266c-a3b7-4ae0-b6d6-abb8c39b2515" backgroundcolor="default" textcolor="default">
    <heading level="1">test</heading>
  </blockcontainer>
</blockgroup>
```
This is exactly the same structure as a fragment that is created manually with the editor.

Upon rendering the editor, it seems like that it deletes all those `<blockcontainer>` nodes after another. 
At least that's what I am observing when I `console.log` with `document.on('update')`.

I wonder if there is a component that detects somehow nodes that were not added with the editor and then deletes them?

**To Reproduce**
1. Create a yjs document with a `Y.XmlFragment`
2. Add the structure to the fragment with something like this:
```typescript
createBlock(id: string, element: Y.XmlElement): Y.XmlElement {
        const blockContainer = new Y.XmlElement('blockcontainer');
        blockContainer.setAttribute("id", id)
        blockContainer.setAttribute("backgroundColor", "default")
        blockContainer.setAttribute("textColor", "default")

        blockContainer.push([element])
        return blockContainer;
}

const body = doc.getXmlFragment('body');
let group = new Y.XmlElement('blockgroup');
const section = new Y.XmlElement('heading')
section.setAttribute('level', "1")
const text = new Y.XmlText()
text.insert(0, "test")
section.push([text])
group.push([createBlock(crypto.randomUUID(), section)])
body.push([group])
```

**Misc**
- Node version: v18.17.1
- Package manager: pnpm
- Browser: Edge
- [ ] I'm a [sponsor](https://github.com/sponsors/YousefED) and would appreciate if you could look into this sooner than later 💖

**Comment by YousefED** [comment]
The structure looks right indeed. When / where do you call this code? On the server / client? Has the editor already been rendered / the Y.Doc already been "initiated" earlier? Have you tried this code also without any Yjs providers connected?

**Comment by kegesch** [comment]
It is called on the client after the document was fetched from the server via a provider and before the editor is rendered. 
Once it is loaded, the editor is rendered and then the document structure is cleared. 

I just tried if without the connected provider and it still has the same problem.

**Comment by YousefED** [comment]
Could you try:
- capitalize the nodenames (blockContainer and blockGroup)
- compare `doc.toJSON()` with the manual one (but sounds like you already did this)
- if the above two options don't work, I'll need a stackblitz example that reproduces this

PS: what are you building?

**Comment by kegesch** [comment]
Wow, that worked! Thank you very much @YousefED.
Seems like the `doc.toJSON()` / `fragment.toDOM()` methods print out the elements with lowercasing.

I am working on a collaborative app called [chordel ](https://chordel.com) to edit songs / lyrics and chords. 
I started to build the editor completely based on `textareas` but soon realized that it will be much work to have the basic functionality of a block-based editor. So by using BlockNote I hope that I can put more effort in contributing to projects like this instead of putting effort into building the editor from ground up.

**Comment by YousefED** [comment]
Great to hear!
