### ISSUE TITLE
Add callout block option on / command

### ISSUE THREAD

**Issue by virgile-dev** [TypeCellOS/BlockNote#1121]
**Is your feature request related to a problem? Please describe.**
Sometimes I want a block to standout to give a warning a provide an info.

**Describe the solution you'd like**
Notion has a nice solution for this, they call it callout. It's available from the / menu in the editor.
The block displays differently from the others (more margin, different background color, starts with an emoji), the text color and background color can still be chosen by the user.
![Capture d’écran du 2024-10-02 17-07-00](https://github.com/user-attachments/assets/eeedd10a-6880-44c5-a4f4-dc54d65e26c5)
![Capture d’écran du 2024-10-02 17-05-32](https://github.com/user-attachments/assets/e608ce8a-728f-4104-afa7-0d4edb3eeedd)

**Describe alternatives you've considered**
Using background color for a block to stand out

**Additional context**

**Comment by YousefED** [comment]
You can achieve this easily with custom blocks. There's an example here: https://www.blocknotejs.org/examples/custom-schema/alert-block. Does that help?

Would love to learn what you're building by the way!

**Comment by virgile-dev** [comment]
Hey thanks for the tip !
I'm working on Docs with Samuel at the French state.
Do you want me to close the issue ?

**Comment by YousefED** [comment]
Ah nice! I'll close it for now :). If creating a custom block for some reason doesn't cut it, let's reopen and discuss!
