### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by DrChhun** [TypeCellOS/BlockNote#1124]
**Describe the bug**
My code on browser work well, but in my terminal it show this message :
" ⨯ ReferenceError: document is not defined
    at Editor (./src/components/playground/Editor.js:92:88)
digest: "1694807815"
 GET /playground 500 in 634ms"
 
 here is my whole code : 
 `"use client";

import "@blocknote/core/fonts/inter.css";
import { BlockNoteView } from "@blocknote/mantine";
import "@blocknote/mantine/style.css";
import { DragHandleButton, getDefaultReactSlashMenuItems, SideMenu, SideMenuController, SuggestionMenuController, useCreateBlockNote } from "@blocknote/react";
import { RemoveButton } from "./RemoveButton";
import { useEffect, useState } from "react";
import { RiAlertFill } from "react-icons/ri";
import { BlockNoteSchema, defaultBlockSpecs, filterSuggestionItems, insertOrUpdateBlock } from "@blocknote/core";
import { Alert } from "./Alert";
import { CodeBlock, insertCode } from "./Codeblock";

const uploadFile = async (file) => {
    const body = new FormData();
    body.append("file", file);
    const ret = await fetch("https://tmpfiles.org/api/v1/upload", {
        method: "POST",
        body: body,
    });
    return (await ret.json()).data.url.replace(
        "tmpfiles.org/",
        "tmpfiles.org/dl/"
    );
};

const schema = BlockNoteSchema.create({
    blockSpecs: {
        ...defaultBlockSpecs,
        alert: Alert,
        procode: CodeBlock,
    },
});

const insertAlert = (editor) => ({
    title: "Alert",
    onItemClick: () => {
        insertOrUpdateBlock(editor, {
            type: "alert",
        });
    },
    aliases: [
        "alert",
        "notification",
        "emphasize",
        "warning",
        "error",
        "info",
        "success",
    ],
    group: "Other",
    icon: <RiAlertFill />,
});

const defaultBlock = [
    {
        id: "default-block", // unique ID for this block
        type: "paragraph",
        content: [
            {
                text: "Start writing here...",
                bold: false,
                italic: false,
                underline: false,
            },
        ],
    },
];

export const Editor = () => {
    let savedBlocks = defaultBlock;

    // Check if we're in the browser environment before using localStorage
    if (typeof window !== "undefined") {
        savedBlocks = JSON.parse(localStorage.getItem("blocks") || "[]");
    }

    const [blocks, setBlocks] = useState(savedBlocks);

    useEffect(() => {
        if (typeof window !== "undefined") {
            localStorage.setItem("blocks", JSON.stringify(blocks));
        }
    }, [blocks]);

    const editor = useCreateBlockNote({
        initialContent: blocks,
        uploadFile,
        schema,
    });

    return (
        <div>
            <BlockNoteView onChange={() => setBlocks(editor?.document)} editor={editor} slashMenu={false} sideMenu={false} theme={'light'}>
                <SideMenuController
                    sideMenu={(props) => (
                        <SideMenu {...props}>
                            <RemoveButton {...props} />
                            <DragHandleButton {...props} />
                        </SideMenu>
                    )}
                />
                <SuggestionMenuController
                    triggerCharacter={"/"}
                    getItems={async (query) =>
                        filterSuggestionItems(
                            [...getDefaultReactSlashMenuItems(editor), insertAlert(editor), insertCode(editor)],
                            query
                        )
                    }
                />
            </BlockNoteView>
            <div>
                <pre>
                    <code>{JSON.stringify(blocks, null, 2)}</code>
                </pre>
            </div>
        </div>
    );
};
`

**To Reproduce**
<clear steps to reproduce are super helpful! Best is to provide an online sandbox, [click to create one](https://stackblitz.com/github/TypeCellOS/BlockNote/tree/main/examples/01-basic/01-minimal?file=App.tsx)>

**Misc**
- Node version: 18.20
- Package manager: pnpm
- Browser: arc
- [ ] I'm a [sponsor](https://github.com/sponsors/YousefED) and would appreciate if you could look into this sooner than later 💖

**Comment by YousefED** [comment]
Please share a stackblitz so we an reproduce this
