### ISSUE TITLE
How to conditionally prevent drag and drop actions in BlockNote editor?

### ISSUE THREAD

**Issue by GersonDantas** [TypeCellOS/BlockNote#1135]
## Description
Hello! I've been exploring the drag and drop functionality in the BlockNote editor and I'm trying to implement a feature that conditionally blocks drag and drop actions based on specific business rules. I'd like to know if there's already a built-in or recommended way to intercept or prevent drag actions on specific blocks.

### What I'm trying to achieve
- Ability to conditionally disable drag and drop for certain blocks
- Implementation that doesn't require modifying the core library
- Ideally, a solution that integrates well with existing BlockNote APIs

### Questions
1. Is there an existing API to handle this use case?
2. If not, what would be the recommended approach to implement this functionality?
3. Are there any known limitations or considerations I should be aware of?

### Dependencies
- "@blocknote/core": "^0.13.5"
- "@blocknote/mantine": "^0.13.5"
- "@blocknote/react": "^0.13.5"
- "@mantine/core": "^7.11.2"

### System Info
- **Browser**: Google Chrome 129.0.6668.100 (Official Build) 64-bit
- **React Version**: 18.2.0

## Additional Information
Any guidance on how to effectively implement this without modifying the core library would be greatly appreciated! If you need any clarification or additional details, please let me know.

Thank you for your help!

**Comment by YousefED** [comment]
Theres no built in API to do this at the monent. Could you dhare more about the use case? Why shouldnt the user be allowed to move certain blocks?

Also curious what kind of app you're building!

**Comment by GersonDantas** [comment]
In our application, we have a block that would be a divider of the internal blocks. We call these "divider" blocks page blocks, they need to be in the root of the editor and have the other blocks inside them. Which brings us to the drag restrictions, since they need to be in the root of the editor and there could not, in theory, be another block in the root.

**Comment by YousefED** [comment]
Clear! Unfortunately, at this moment it's not possible. You'd need to write a custom Prosemirror plugin or modify the dragging code to implement this.

For which app is this?
