### ISSUE TITLE
Does it support embedding Office suite

### ISSUE THREAD

**Issue by Ambercssa** [TypeCellOS/BlockNote#1136]
Does it support previewing uploaded PDFs in Word format

**Comment by YousefED** [comment]
can you explain a bit more what you need exactly? Also, what kind of app are you building?

**Comment by Ambercssa** [comment]
> 您能详细解释一下您到底需要什么吗？另外，您正在开发什么类型的应用程序？
When adding files, if you choose PPT, Excel, or Word files, you can use OnlyOffice to open the preview, just like images and videos

**Comment by Ambercssa** [comment]
When adding files, if you choose PPT, Excel, or Word files, you can use OnlyOffice to open the preview, just like images and videos

**Comment by YousefED** [comment]
You can implement this yourself by following this example: https://www.blocknotejs.org/examples/custom-schema/pdf-file-block

**Comment by Ambercssa** [comment]
We are developing a knowledge management platform

**Comment by Ambercssa** [comment]
I would prefer to be able to customize blocks for implementation, such as customizing an iframe to load the content I need
