### ISSUE TITLE
Property 'url' does not exist on type

### ISSUE THREAD

**Issue by zacharymichaelmoore** [TypeCellOS/BlockNote#1138]
**Describe the bug**
In my own project I am trying to write a function which detects when a specific image block is removed, so that I can send a delete request to a storage bucket with the image to be removed urls. The url property is not being recognized. An image block should have this property but it's saying it doesn't exist on the type.

**To Reproduce**
https://stackblitz.com/edit/github-3pkkxc?file=App.tsx

<img width="1045" alt="Screenshot 2024-10-10 at 11 11 42 AM" src="https://github.com/user-attachments/assets/49572646-09c6-4f71-b75b-5ee317365430">

<img width="755" alt="Screenshot 2024-10-10 at 11 12 19 AM" src="https://github.com/user-attachments/assets/634aa390-33ee-46fe-bf69-eaf90eeb7ba4">

**Misc**
Maybe I am not understanding something but it looks like url property does exist.

**Comment by YousefED** [comment]
first assert that it's an image block:

`obj.type === "image" && obj.props.url !== imageURLAtCursorPosition`

**Comment by zacharymichaelmoore** [comment]
thanks
