### ISSUE TITLE
Custom block in Slash menu bug when using Shadcn and Tailwind styling

### ISSUE THREAD

**Issue by hpk992** [TypeCellOS/BlockNote#1139]
**Describe the bug**

Styling bug with a custom block in the slash menu when using the Shadcn styling.

![image](https://github.com/user-attachments/assets/15714dec-02c2-40be-92d7-05ce9688560d)
<img width="1211" alt="image" src="https://github.com/user-attachments/assets/6677bcc3-678c-4b52-a348-ffecab96463b">

**To Reproduce**
https://stackblitz.com/edit/github-6jxjbr-vquqjo?file=App.tsx

**Misc**
- Node version: v22.2.0
- Package manager: npm v10.7.0
- Browser: Chrome
- [ ] I'm a [sponsor](https://github.com/sponsors/YousefED) and would appreciate if you could look into this sooner than later 💖

**Comment by YousefED** [comment]
Disable the default slashmenu by passing `slashMenu={false}` to blocknoteview. What kind of app are you building?

**Comment by hpk992** [comment]
I'm building a project management tool that is like Jira + Notion.
