### ISSUE TITLE
Uncaught RangeError: Position -1 out of range when creating a new editor instance

### ISSUE THREAD

**Issue by Akshdhiwar** [TypeCellOS/BlockNote#1145]
**Description:**
I encountered an Uncaught RangeError: Position -1 out of range error while creating a new editor instance in my project. This happens when a new editor is initialized in "editing mode." Below is the stack trace:

```
chunk-LTEZDJSH.js?v=1bc2ccfc:7965 Uncaught RangeError: Position -1 out of range
    at _ResolvedPos.resolve (chunk-LTEZDJSH.js?v=1bc2ccfc:7965:13)
    at _ResolvedPos.resolveCached (chunk-LTEZDJSH.js?v=1bc2ccfc:7991:63)
    at _Node.resolve (chunk-LTEZDJSH.js?v=1bc2ccfc:8251:24)
    at new MouseDown (chunk-LTEZDJSH.js?v=1bc2ccfc:19892:33)
    at handlers.mousedown (chunk-LTEZDJSH.js?v=1bc2ccfc:19869:28)
    at view.dom.addEventListener.view.input.eventHandlers.<computed> (chunk-LTEZDJSH.js?v=1bc2ccfc:19660:9)
```

**Steps to Reproduce:**

Create a new editor instance using the following code:
```

// Editor instance
const editor = useMemo(() => {
    let editor: any
    if (isEditing) {
        const doc = new Y.Doc();
        const provider = new YPartyKitProvider(
            "blocknote-dev.yousefed.partykit.dev",
            project?.Id! + selectedFolder?.id,
            doc,
        );
        editor = BNE.create({
            collaboration: {
                provider,
                fragment: doc.getXmlFragment("document-store"),
                user: {
                    name: user?.GithubName!,
                    color: getRandomColor() // blue color
                }
            }
        });
    } else {
        editor = BNE.create({
            initialContent: pageContent
        });
    }

    return editor;
}, [selectedFolder, isEditing, pageContent]);

```

**Expected Behavior:**
The editor should initialize properly and allow user interaction without any errors.

**Actual Behavior:**
The error Position -1 out of range occurs when trying to resolve a position within the document, possibly related to mouse input handling.

It works normal after a re-render of component but on initialization it throws a error.
Please free to give your suggestion on this if I'm doing something wrong or so.

**Comment by Akshdhiwar** [comment]
Hey @trival Thanks for comment but I'm using react. Do you know what same can be done in react ?

**Comment by trival** [comment]
> Hey @trival Thanks for comment but I'm using react. Do you know what same can be done in react ?

I am not sure. It seems the error is raised somewhere in ProseMirror, because some event is not propagated correctly. In my application, NextJS 14 was working just fine. The error started after updating to Next 15 and dissappeared after the configuration change. Apparently the configuration is somehow related to [StrictMode](https://react.dev/reference/react/StrictMode). Maybe you or some of your downstream dependencies are using it? Other than that I don't have more clues...

**Comment by trival** [comment]
Also from StrictMode Docs: 

> Strict Mode enables the following development-only behaviors:
> 
>     Your components will [re-render an extra time](https://react.dev/reference/react/StrictMode#fixing-bugs-found-by-double-rendering-in-development) to find bugs caused by impure rendering.
>     Your components will [re-run Effects an extra time](https://react.dev/reference/react/StrictMode#fixing-bugs-found-by-re-running-effects-in-development) to find bugs caused by missing Effect cleanup.
>     Your components will [be checked for usage of deprecated APIs.](https://react.dev/reference/react/StrictMode#fixing-deprecation-warnings-enabled-by-strict-mode)

Maybe your code does something like that?

**Comment by Akshdhiwar** [comment]
Yes there is a re-render when switches into editing mode 

```
// Editor instance
const editor = useMemo(() => {
    let editor: any
    if (isEditing) {
        const doc = new Y.Doc();
        const provider = new YPartyKitProvider(
            "blocknote-dev.yousefed.partykit.dev",
            project?.Id! + selectedFolder?.id,
            doc,
        );
        editor = BNE.create({
            collaboration: {
                provider,
                fragment: doc.getXmlFragment("document-store"),
                user: {
                    name: user?.GithubName!,
                    color: getRandomColor() // blue color
                }
            }
        });
    } else {
        editor = BNE.create({
            initialContent: pageContent
        });
    }

    return editor;
}, [selectedFolder, isEditing, pageContent]);
```

I think I should look into re-rendering part.
Thanks btw

**Comment by Akshdhiwar** [comment]
> Also from StrictMode Docs:
> 
> > Strict Mode enables the following development-only behaviors:
> > Your components will [re-render an extra time](https://react.dev/reference/react/StrictMode#fixing-bugs-found-by-double-rendering-in-development) to find bugs caused by impure rendering.
> > Your components will [re-run Effects an extra time](https://react.dev/reference/react/StrictMode#fixing-bugs-found-by-re-running-effects-in-development) to find bugs caused by missing Effect cleanup.
> > Your components will [be checked for usage of deprecated APIs.](https://react.dev/reference/react/StrictMode#fixing-deprecation-warnings-enabled-by-strict-mode)
> 
> Maybe your code does something like that?


Yes there is a re-render when switches into editing mode

```
// Editor instance
const editor = useMemo(() => {
    let editor: any
    if (isEditing) {
        const doc = new Y.Doc();
        const provider = new YPartyKitProvider(
            "blocknote-dev.yousefed.partykit.dev",
            project?.Id! + selectedFolder?.id,
            doc,
        );
        editor = BNE.create({
            collaboration: {
                provider,
                fragment: doc.getXmlFragment("document-store"),
                user: {
                    name: user?.GithubName!,
                    color: getRandomColor() // blue color
                }
            }
        });
    } else {
        editor = BNE.create({
            initialContent: pageContent
        });
    }

    return editor;
}, [selectedFolder, isEditing, pageContent]);

```

I think I should look into re-rendering part.
Thanks btw

**Comment by Akshdhiwar** [comment]
Hey @trival Thanks for suggesting me the solution. Yes you were correct the thing was the editor was re-rendered multiple times and that caused this issue. Thanks for helping me out and I would like to connect with you on other platforms and lets be friend. Already followed you on X. Once again thank you mate.
