### ISSUE TITLE
Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by jehaad1** [TypeCellOS/BlockNote#1164]
**Describe the bug**
When using focus function sometimes the block is undefined.
<br/>
```js
if(editor) editor.focus()
```
I also tried
```js
if (editor) editor._tiptapEditor.commands.focus();
```
<br/>
 But both causing the same bunch of errors.

<br/>
<br/>
<img width="904" alt="image" src="https://github.com/user-attachments/assets/9ff58228-0ba8-465b-80b5-3011c1bcf395">
<img width="904" alt="image" src="https://github.com/user-attachments/assets/2b2f25fc-dea2-46f3-844b-388d950d279f">
<br/>
<br/>

I think the easiest solution is replace

```js
i.block.id;
```

with

```js
i.block?.id;
```

**Misc**
- Node version: latest
- Package manager: NPM
- Browser: Arc
- [ ] I'm a [sponsor](https://github.com/sponsors/YousefED) and would appreciate if you could look into this sooner than later 💖

**Comment by YousefED** [comment]
A big part of this code has been changed in this PR: https://github.com/TypeCellOS/BlockNote/pull/1132/files

Can you upgrade to v0.17 and reopen an issue if it still occurs?

**Comment by jehaad1** [comment]
I just upgraded to v0.17 and still facing the same bug.
