### ISSUE TITLE
blocksToFullHtml renders null for numbered lists

### ISSUE THREAD

**Issue by entropi** [TypeCellOS/BlockNote#1168]
**Describe the bug**
When using editor.blocksToFullHtml, numbered lists list `null` instead of the actual number.

**To Reproduce**
generate some blocks (in my case from `tryParseMarkdownToBlocks`) which contain numbered list items and then attempt to render those blocks to html using the `blocksToFullHTML`. Null is there instead of the number.

**Misc**

- [x] I'm a [sponsor](https://github.com/sponsors/YousefED) and would appreciate if you could look into this sooner than later 💖

(PoggioLabs is the sponsor)

**Comment by YousefED** [comment]
Thanks! We'll look into this next week 👍
