### ISSUE TITLE
Feedback for “Rendering static documents”

### ISSUE THREAD

**Issue by brokenashish** [TypeCellOS/BlockNote#1170]
When centering an image this doen't seem to work.

It renders the output as 
```html
<img src="image.jpg" alt="67a22de179c1f987629ebf5944b73919.jpg" width="208" data-text-alignment="center" data-name="67a22de179c1f987629ebf5944b73919.jpg" data-url="image.jpg" data-preview-width="208">
```
data-text-alignment="center" exits but it won't work because the the alignment has to be applied to the parent and not to the image

**Comment by brokenashish** [comment]
Sorry. I was using blocksToHTMLLossy.
It get's centered but the image doesn't show up because there is no src attribute in the image tag

**Comment by YousefED** [comment]
There should be a src attribute. can you provide a stackblitz reproduction that shows there's no src output?
