### ISSUE TITLE
Regression: Sticky tool buttons

### ISSUE THREAD

**Issue by serpent213** [TypeCellOS/BlockNote#1171]
Block's tool buttons don't scroll with content on 0.17.1:

https://github.com/user-attachments/assets/1bd8d75f-0c6a-4802-8055-25e0888c15c7

I'm using *shadcn* components. Buttons behave as expected on 0.16.0.

Please let me know if you need more information and/or a sandbox.

**Misc**
- Browser: Tried latest Firefox and Brave on macOS

**Comment by YousefED** [comment]
Thanks, seems like a regression indeed

**Comment by YousefED** [comment]
> Just noticed another small glitch when extending the slash menu, following the Alert example.
> 
> 0.16.0: <img alt="Screenshot 2024-10-28 at 11 55 51" width="392" src="https://private-user-images.githubusercontent.com/106662/380684987-b66a0b7e-8ee6-45a1-8cac-a32bcb19508c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxMTM3NDUsIm5iZiI6MTczMDExMzQ0NSwicGF0aCI6Ii8xMDY2NjIvMzgwNjg0OTg3LWI2NmEwYjdlLThlZTYtNDVhMS04Y2FjLWEzMmJjYjE5NTA4Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOFQxMTA0MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMGE0MjJhZWQxNjNiNWRkMmVhZDg1NTZkZmYyYmJhZTMzMmIyOTI3OGFmNzhlZGRiZTZjMTQ3ZTY0ZDkwM2YyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JKzNwau8NKqf_8BxZ3yY0o9ke55dK0qZWSPa0Zu8XCQ">
> 
> 0.17.1: <img alt="Screenshot 2024-10-28 at 11 43 52" width="392" src="https://private-user-images.githubusercontent.com/106662/380684974-02e24465-ed07-4bd7-9238-2e3ac75a9f66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxMTM3NDUsIm5iZiI6MTczMDExMzQ0NSwicGF0aCI6Ii8xMDY2NjIvMzgwNjg0OTc0LTAyZTI0NDY1LWVkMDctNGJkNy05MjM4LTJlM2FjNzVhOWY2Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOFQxMTA0MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MmE3YjExN2VkMDkxOGJhYjFiNTc3ODAxY2RhNDM3NTdmNzcwMWY4ZjA4NmMxODM5NWRhMGJjM2QxM2E4MGY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.d64hdvs_HQ056Am9BE4eyVhbLv-0KXP20tUawq9CQoI">

this seems unrelated and you just need to pass `slashMenu=false` to the view

**Comment by serpent213** [comment]
My code looks like this:
```js
    return (
        <BlockNoteView
            editor={editor}
            emojiPicker={false}
            slashMenu={false}
            theme="light"
            onChange={() => {
                debouncedPushEvent(editor.document as Block[])
            }}
        >
            <SuggestionMenuController
                triggerCharacter={"/"}
                getItems={async (query) =>
                    // Gets all default slash menu items and `insertAlert` item.
                    filterSuggestionItems([...getDefaultReactSlashMenuItems(editor), insertAlert(editor)], query)
                }
            />
        </BlockNoteView>
    )
```
Also, the Emoji Picker is still visible, even though set to `false`.

Did I get it wrong?

**Comment by YousefED** [comment]
@serpent213 this should be ok. Could you create a separate issue with a link to a reproducible sandbox (stackblitz), and remove your comments from this issue?

**Comment by serpent213** [comment]
Sure, will do!

**Comment by serpent213** [comment]
Managed to set up a BlockNote dev environment. Cannot reproduce the original bug there with the latest version, so closing this for good.  🙂
