### ISSUE TITLE
Background color on table do not work

### ISSUE THREAD

**Issue by virgile-dev** [TypeCellOS/BlockNote#1176]
**Describe the bug**
Background color on table in the editor does not work correctly.
![](https://private-user-images.githubusercontent.com/25994652/371038357-51663ec7-772e-4042-8434-1fe06a44851e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2MDczOTQsIm5iZiI6MTcyOTYwNzA5NCwicGF0aCI6Ii8yNTk5NDY1Mi8zNzEwMzgzNTctNTE2NjNlYzctNzcyZS00MDQyLTg0MzQtMWZlMDZhNDQ4NTFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDE0MjQ1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1OGNkYzdjMDYzNDUxMDhhN2Y5YzhhMDgwMDlhN2Q5MDUwZGVmMGRjMjAyOTkxMDNlNjJjZjU2ZmQ0NDRlODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-vlcRu9__b0Unw-7cuP9TVxtqhyMbBDn8w-qr9269Gw)

**Comment by YousefED** [comment]
I think it would make most sense to disable to bg color here

**Comment by virgile-dev** [comment]
![Capture d’écran du 2024-11-13 11-14-30](https://github.com/user-attachments/assets/0b1fe5a0-a3b7-4456-b279-6631c0c5959d)
Agreed, it does not look great
