### ISSUE TITLE
Use with React 19 fails with error "Cannot read properties of undefined (reading 'ReactCurrentOwner')"

### ISSUE THREAD

**Issue by ryleyrandall22** [TypeCellOS/BlockNote#1187]
**Describe the bug**
When using the library with a default config, the following error is thrown "Cannot read properties of undefined (reading 'ReactCurrentOwner')". This looks like a piece from React internals that was removed in react 19. This appears to be a common issue with apps in React 19. Interestingly, NextJS uses this as well so the must patch the change.

**To Reproduce**
https://stackblitz.com/edit/github-2amsyj?file=package.json

**Misc**
- Node version:20.18
- Package manager:PNPM
- Browser: Chrome
- [ ] I'm a [sponsor](https://github.com/sponsors/YousefED) and would appreciate if you could look into this sooner than later 💖

**Comment by irakli2206** [comment]
Really hope this issue gets addressed soon. This looks like the best block-based rich text library out there.

**Comment by YousefED** [comment]
duplicate and fix wip #1188
