### ISSUE TITLE
Prop 'editor' does not exist on 'BlockNoteView' in React 17.

### ISSUE THREAD

**Issue by Svring** [TypeCellOS/BlockNote#1191]
**Describe the bug**
I see this issue has been reported in #775, the [quickstart](https://www.blocknotejs.org/docs/quickstart) does not work because of a type error as below.

<img width="873" alt="Screenshot 2024-10-27 at 12 03 09" src="https://github.com/user-attachments/assets/f875fe42-9a9d-4855-a2a4-e63ac74f8483">

The reason is quite straightforward: BlockNote has a requirement of React18 which has been specified in package.json, change the React version to 17 and it crashes.

This situation happens when React17 is already installed before BloackNote, which could be a little confusing as the quickstart example doesn't emphasize the supported React version issue.

Maybe there could be a reminder on the quickstart page?

**To Reproduce**
run this command in the terminal.
`npm install react@17 react-dom@17 @types/react@17 @types/react-dom@17`

**Misc**
- Node version:v22
- Package manager:npm

**Comment by mwonng** [comment]
I believe after restart dev server, this compiler will be failed. 

It seems that due to React 18 change for React DOM Client [here:](https://github.com/facebook/react/blob/main/CHANGELOG.md#1800-march-29-2022),

> These new APIs are now exported from react-dom/client:

This could be a warm warning about support only React 18+.

**Comment by YousefED** [comment]
At this moment, we don't support React 17 and unfortunately don't have plans to add this (we we are shipping React 19 compatibility this week, though). @Svring  You're welcome to add a note to the docs, or see if you can implement React 17 support

**Comment by ChrisCates** [comment]
@YousefED, it'll still work with React 19.

Just do this:

```typescript
const TempViewFix: any = BlockNoteView
...
<TempViewFix
  ...
/>
```

I'm curious what happened? Thanks for working on the project.

**Comment by xxxstasiek** [comment]
updating @types/react to 18.3 and @types/react-dom to 19.0.2 fixed this issue for me
