### ISSUE TITLE
editor.tryParseMarkdownToBlocks

### ISSUE THREAD

**Issue by Ambercssa** [TypeCellOS/BlockNote#1208]
`Sure!  Below  is  a comprehensive example document  in English that includes  various formatting elements such  as headings, sub headings, paragraphs, lists, quotes, tables, andimage references.\r\n\r\n---\r\n\r\n# Comprehensive Example Document\r\n\r\n## Introduction\r\n\r\n This document aims to  demonstrate the various formatting  elements that can be  used to enhance the  readability and professionalism of  a document.By  following this example,  you can learn how  to effectively use these  formatting tools in yourown documents.\r\n\r\n### Document Objectives\r\n\r\n- Provide basic guidanceon formatting\r\n-  Showcase practical applications ofdifferent formatting elements\r\n- Enhance the  visual appeal and information  delivery efficiency of thedocument\r\n\r\n## MainBody\r\n\r\n### 1.Paragraphs\r\n\r\n Paragraphs are  one of the most  fundamental components of any  document.A well-structured paragraph should  focus on a central  idea and develop it  through clear and logical  language.For example, when introducing a  new technology, you  can discuss its background, `

This is a markdown returned by an AI model
But I cannot convert the editor.tryParseMarkdownToBlocks to blocks in normal format

**Comment by YousefED** [comment]
Can you add information about the error you're getting? will close for now
