### ISSUE TITLE
Google Chrome version compatibility issue

### ISSUE THREAD

**Issue by Ambercssa** [TypeCellOS/BlockNote#1222]
![b21c1f1e5847fdda801c2b8f0f9cc67](https://github.com/user-attachments/assets/6b50af1e-f823-4206-b222-22bea86d2888)

This error will be prompted in Google Chrome version 84.0.4115.1，
Due to certain reasons within the company, it is not possible to upgrade the browser

**Comment by Ambercssa** [comment]
is a state-owned enterprise in China,
What is the minimum version supported by Google Chrome?

**Comment by YousefED** [comment]
Best to be on a recent version, but I'm pretty sure any version from last 2 years should be ok

**Comment by Ambercssa** [comment]
If want to be compatible with versions from the past five years, is the cost of modification high

**Comment by Ambercssa** [comment]
Are you going to abandon the browser from two years ago

**Comment by YousefED** [comment]
Hi,

> If want to be compatible with versions from the past five years, is the cost of modification high

We can't guarantuee old-browser support. What we can do is look on a per issue basis what the work required is that you need fixed, and then you can either contribute this or hire us to add the compatibility or a workaround. Let me know if you're interested in this!

**Comment by Ambercssa** [comment]
const getBaseSelector = (additionalSelectors = "") => {
          if (supportsHasPseudo()) {
            return `.bn-block-content${additionalSelectors} .bn-inline-content:has(> .ProseMirror-trailingBreak:only-child):before`;
          } else {
            const blocks = document.querySelectorAll(`.bn-block-content${additionalSelectors} .bn-inline-content > .ProseMirror-trailingBreak`)
            if (blocks && blocks.length === 1) {
              return `.bn-block-content${additionalSelectors} .bn-inline-content:before`;
            } else {
              return null
            }
          }
        };
        const supportsHasPseudo = (): boolean => {
          try {
            document.querySelector(":has(*)");
            return true;
          } catch {
            return false;
          }
        };
       
     I tried to modify it, and it seems to work too

**Comment by Ambercssa** [comment]
for (const [blockType, placeholder] of Object.entries(placeholders)) {
          const mustBeFocused = blockType === "default";

          styleSheet.insertRule(
            `${getSelector(
              blockType,
              mustBeFocused
            )}{ content: ${JSON.stringify(placeholder)}; position: absolute; pointer-events: none; color: var(--bn-colors-side-menu); height: 0; }`
          );

          // For some reason, the placeholders which show when the block is focused
          // take priority over ones which show depending on block type, so we need
          // to make sure the block specific ones are also used when the block is
          // focused.
          if (!mustBeFocused) {
            styleSheet.insertRule(
              `${getSelector(blockType, true)}{ content: ${JSON.stringify(
                placeholder
              )}; }`
            );
          }
        }
        
      And modify the style of the placeholders here
