### ISSUE TITLE
bug: Selecting empty cells causes error in prosemirror

### ISSUE THREAD

**Issue by mkarbo** [TypeCellOS/BlockNote#123]
After initializing the editor, before creating any blocks, selecting the empty placeholder block causes an error in prosemirror
![image](https://user-images.githubusercontent.com/38499319/225001944-bc914e48-6e85-4ab2-b9c0-148754bb6ea8.png)

**Comment by YousefED** [comment]
This is likely to be a dependency installation issue. Could you share a reproducible project?

**Comment by mkarbo** [comment]
https://github.com/mkarbo/BlockNote-bug-123 reproduces it on a blank next project with latest alpha.

My original test was on 0.4.3

**Comment by YousefED** [comment]
I don't see the error using this project. Could you try clearing node_modules?

**Comment by mkarbo** [comment]
Just to be clear - the error doesn't automatically pop up for me on first render. I can provoke it by trying to select empty row, and sometimes it pops up when e.g., switching tabs.

I replicated this from a clean install, nothing to do with node modules I believe

**Comment by YousefED** [comment]
Thanks. Could you try  `0.4.6-alpha.4` for a possible workaround?

**Comment by mkarbo** [comment]
Sure, will do

**Comment by mkarbo** [comment]
No longer able to provoke the issue manually! 👏

**Comment by YousefED** [comment]
nice!
