### ISSUE TITLE
Add "disableUploads"/"embeddedOnly" option on Media blocks?

### ISSUE THREAD

**Issue by bleafman** [TypeCellOS/BlockNote#1230]
**Is your feature request related to a problem? Please describe.**

Hi BlockNote folks! We would like to be able to support Image uploads but only allow embeds for other media formats (video, audio, etc.).  

**Describe the solution you'd like**

I'd like for Media blocks to accept some sort of configuration option (ex. `embedOnly`) that will not show the `Upload` option.

![Screenshot 2024-11-08 at 3 08 28 PM](https://github.com/user-attachments/assets/638524bb-6d08-4f56-9c59-1e4c5d3f07b1)

The "Upload" option is currently all or nothing for all Media blocks if you provide an `uploadFile` function in the [FilePanel](https://github.com/TypeCellOS/BlockNote/blob/11b330b2e604495782023cd607452c75564b867f/packages/react/src/components/FilePanel/FilePanel.tsx#L45).

**Describe alternatives you've considered**

I can build my own custom blocks but because the control for FilePanel is so deep I'm copying a LOT of code to keep the same UX for all Media blocks.

**Additional context**

Happy to put up a PR, just wanted to check to make sure it wouldn't violate any design decisions with the component APIs to add more configuration.

**Bonus**
[ ] I'm a [sponsor](https://github.com/sponsors/YousefED) and would appreciate if you could look into this sooner than later 💖

**Comment by YousefED** [comment]
Thanks!

> I can build my own custom blocks but because the control for FilePanel is so deep I'm copying a LOT of code to keep the same UX for all Media blocks.

Curious what you're running into exactly. Could you just pass a different set of tabs depending on the block? Haven't tried this, but my first thoughts are along these lines:

```typescript
// pseudo code
const MyFilePanel(props) {
if(props.block.type === "xxx") {
 return <FilePanel tabs={[{
      name: dict.file_panel.embed.title,
      tabPanel: <EmbedTab block={props.block} />,
    }]}
}
return <FilePanel />
}

```

**Comment by bleafman** [comment]
Oh nice! I didn't see that `EmbedTab` was exported.

I ended up rolling my own placeholder + add video modal so that I could do more narrow validation for video sources but I think this would have worked.

Here's my (fragile) file placeholder for anyone looking in the future.

```tsx
const ActionButton = ({
  buttonIcon,
  buttonText,
  onClick,
  type,
}: {
  buttonIcon: React.ReactNode;
  buttonText: string;
  onClick: () => void;
  type: string;
}) => (
  <div
    className='bn-block-content'
    data-content-type={type}
    data-file-block=''
    contentEditable={false}
  >
    <div className='bn-file-block-content-wrapper'>
      <div className='bn-add-file-button' onClick={onClick}>
        <div className='bn-add-file-button-icon'>{buttonIcon}</div>
        <p className='bn-add-file-button-text'>{buttonText}</p>
      </div>
    </div>
  </div>
);
```

**Comment by YousefED** [comment]
> Oh nice! I didn't see that `EmbedTab` was exported.
> 
> I ended up rolling my own placeholder + add video modal so that I could do more narrow validation for video sources but I think this would have worked.
> 
> Here's my (fragile) file placeholder for anyone looking in the future.
> 
> ```tsx
> const ActionButton = ({
>   buttonIcon,
>   buttonText,
>   onClick,
>   type,
> }: {
>   buttonIcon: React.ReactNode;
>   buttonText: string;
>   onClick: () => void;
>   type: string;
> }) => (
>   <div
>     className='bn-block-content'
>     data-content-type={type}
>     data-file-block=''
>     contentEditable={false}
>   >
>     <div className='bn-file-block-content-wrapper'>
>       <div className='bn-add-file-button' onClick={onClick}>
>         <div className='bn-add-file-button-icon'>{buttonIcon}</div>
>         <p className='bn-add-file-button-text'>{buttonText}</p>
>       </div>
>     </div>
>   </div>
> );
> ```

Thanks for sharing and glad it worked out! Btw, what are you using BlockNote for?
