### ISSUE TITLE
How to change the placeholder 

### ISSUE THREAD

**Issue by brijal091** [TypeCellOS/BlockNote#1242]
there is an placeholder which is Enter text or type'/' for commands how can we change it ?

**Comment by Blapi** [comment]
```
    const editor = useCreateBlockNote({
      dictionary: {
        ...locales.en,
        placeholders: {
          ...locales.en.placeholders,
          default: placeholder ?? locales.en.placeholders.default,
        },
      }
    })
```

Depending on your locale obviously

**Comment by YousefED** [comment]
/bounty 10 for adding an example that shows how to change the default placeholder and the placeholder for Headings

**Comment by hunxjunedo** [comment]
@YousefED hey can I get assigned please?

**Comment by ezhil56x** [comment]
/attempt #1242
Started working
