### ISSUE TITLE
How to change placeholder "Enter text or type '/' for commands" to different text

### ISSUE THREAD

**Issue by sccsspnk** [TypeCellOS/BlockNote#1251]
https://discord.com/channels/928190961455087667/1305736656317583484
![image](https://github.com/user-attachments/assets/916f1fbd-163b-41bf-a8ea-d4928476875a)

how use useCreateBlockNote to change that placeholder?

**Comment by sccsspnk** [comment]
I have this:
```
import { useCreateBlockNote } from "@blocknote/react";
import { BlockNoteView } from "@blocknote/mantine";

import "@blocknote/core/fonts/inter.css";
import "@blocknote/mantine/style.css";

export default function BlockNoteEditor({ setIssue }) {
  const editor = useCreateBlockNote();

  return (
    <BlockNoteView
      //@ts-ignore
      editor={editor}
      sideMenu={false}
      theme="light"
      onChange={() => {
        setIssue(editor.document);
      }}
    />
  );
}
```

**Comment by hsingh-ds** [comment]
@sccsspnk here is the [example](https://www.blocknotejs.org/examples/basic/custom-placeholder) which shows how to set custom placeholder. let me know if it works for you.
