### ISSUE TITLE
Copy from Word into Blocknote

### ISSUE THREAD

**Issue by zohayb96** [TypeCellOS/BlockNote#1258]
Hi BlockNote Team,

I noticed that in the example template posted online, I can copy and paste content from a Microsoft Word document into the editor, and it renders the text as expected. However, when I try to do the same in my own deployed application using the starting code template, the pasted content doesn’t appear at all.

Could you let me know if there are any restrictions or additional configurations required to enable this feature?

Thank you for your help!

Best regards,

**Comment by YousefED** [comment]
Can you share the content that you're trying to paste? Also, are you on the most recent version of blocknote?
