### ISSUE TITLE
Collaborating on the same line sometimes creates a linebreak

### ISSUE THREAD

**Issue by virgile-dev** [TypeCellOS/BlockNote#1265]
**Describe the bug**
When two people are editing the same line it can create a line break in the block which is annoying as you get 2 different renderings and it can make collaboration difficult as things move around as user move  their cursor on the line

**To Reproduce**
Go on the same line create a line long enough and then move your cursor along the line with the keyboard. You'll see a linebreak being made that shouldn't appear
[Capture vidéo du 21-11-2024 18:07:52.webm](https://github.com/user-attachments/assets/245c8a30-db77-4a7a-8ccc-8bdc6c9516d8)

**Misc**
- Node version:
- Package manager:
- Browser: Firefox Version 131.0.3 (64 bits) (Ubuntu 22.04)
- [x] I'm a [sponsor](https://github.com/sponsors/YousefED) and would appreciate if you could look into this sooner than later 💖

**Comment by YousefED** [comment]
We've only seen this on Ubuntu, correct? i.e.: firefox on other OS didn't have this issue?

**Comment by virgile-dev** [comment]
Hey @YousefED just tested on iOS usig Firefox I have the same issue.
