### ISSUE TITLE
Firefox 115, the toolbar doesn't display

### ISSUE THREAD

**Issue by virgile-dev** [TypeCellOS/BlockNote#1286]
**Describe the bug**
On Firefox 115, the toolbar doesn't display at text selection nor when typing the / command

**To Reproduce**
Select a text on Firefox 115 select a text see no BlockNote toolbar.
![Capture d’écran du 2024-11-28 18-49-37](https://github.com/user-attachments/assets/9e1cd93b-f367-49d2-83f6-89aeae6d6c8a)
![Capture d’écran du 2024-11-28 18-55-31](https://github.com/user-attachments/assets/a5b39a6b-2c34-476a-b651-b8049c5e8311)

**Misc**
- Node version:
- Package manager:
- Browser: Firefox 115
- [x] I'm a [sponsor](https://github.com/sponsors/YousefED) and would appreciate if you could look into this sooner than later 💖

**Comment by Ambercssa** [comment]
I also encountered the same problem, hoping to be compatible with more browser versions~ 🙏🙏🙏

**Comment by virgile-dev** [comment]
@YousefED our users report that this is new for them, they used to be able to see the toolbar last week. So maybe it's with the latest upgrades

**Comment by YousefED** [comment]
Thanks, we'll check asap!

**Comment by AntoLC** [comment]
From the sentry logs: `exception Error: cleanHTMLToMarkdown requires ESM dependencies to be initialized`
Seems to touch only old Firefox <= 115.

https://github.com/TypeCellOS/BlockNote/blob/a7bf806d71c330cb0c7b9a149a4d9d57ed4e53c5/packages/core/src/api/exporters/markdown/markdownExporter.ts#L22-L26
