### ISSUE TITLE
Copy paste content from the doc doesn't work on Firefox 115

### ISSUE THREAD

**Issue by virgile-dev** [TypeCellOS/BlockNote#1296]
**Describe the bug**
When I copy paste content from the doc it doesn't work on Firefox 115

**To Reproduce**
Simulate a Firefox 115, type in content in the doc, try and copy paste it inside the doc.

**Misc**
- Browser: Firefox 115
- [x] I'm a [sponsor](https://github.com/sponsors/YousefED) and would appreciate if you could look into this sooner than later 💖

**Comment by YousefED** [comment]
If this is the error: https://github.com/TypeCellOS/BlockNote/issues/1286#issuecomment-2510846831, then there likely was  a regression here: https://github.com/TypeCellOS/BlockNote/pull/1160/files: we made copy sync, but do not initialize the markdown dependencies anymore.

**Comment by matthewlipski** [comment]
Fixed in #1300
