### ISSUE TITLE
copy paste tables to excel / google sheets

### ISSUE THREAD

**Issue by YousefED** [TypeCellOS/BlockNote#1298]
A common workflow involves copying data between tables and Excel.

**Expectation**: When users copy a (part of a) table to Excel or google sheets, they should see it displayed exactly as it appeared in the notebook.
**Actual**: When users copy a  table to Excel, it pastes as a single column with irregular spacing.

https://github.com/user-attachments/assets/5a8a5f2e-a215-4fff-8b42-14734794a0d4

**Comment by matthewlipski** [comment]
Closed in #1319
