### ISSUE TITLE
Copy pasting an Emoji insert a page break

### ISSUE THREAD

**Issue by virgile-dev** [TypeCellOS/BlockNote#1321]
**Describe the bug**
When I copy paste an emoji from Emojipedia, for [ex](https://emojipedia.org/sparkles)

**To Reproduce**
![paste](https://github.com/user-attachments/assets/b6b9758b-9420-4a8e-8abb-0dcab3a7006a)

**Misc**
- Node version:
- Package manager:
- Browser: Firefox 133 
- [x] I'm a [sponsor](https://github.com/sponsors/YousefED) and would appreciate if you could look into this sooner than later 💖

**Comment by YousefED** [comment]
@virgile-dev how do you copy the emoji? When I hit the "copy" button (e.g. [here](https://emojipedia.org/dizzy)) it works fine when pasting in blocknote

**Comment by virgile-dev** [comment]
Yep same as you.  Doesn't seem to be firefox related, just tested on chromium. The line break appears to be created when I copy paste the emoji at the end of a line not when I copy paste at the beginning of a line.
[Capture vidéo du 16-12-2024 11:10:17.webm](https://github.com/user-attachments/assets/ba9438b2-71bd-4a2d-8613-ee24080b16d0)
