### ISSUE TITLE
Example code: Uncaught TypeError: Cannot read properties of undefined (reading 'isInGroup')

### ISSUE THREAD

**Issue by GracieRen** [TypeCellOS/BlockNote#1327]
**Describe the bug**
[<what's going wrong!?>](https://www.blocknotejs.org/examples/basic/block-manipulation)

**To Reproduce**
<clear steps to reproduce are super helpful! Best is to provide an online sandbox, [click to create one]
Example code: editor.replaceBlocks()

**Comment by YousefED** [comment]
You're probably on an outdated version of `prosemirror-view`
