### ISSUE TITLE
Demo + API for loading and saving state

### ISSUE THREAD

**Issue by YousefED** [TypeCellOS/BlockNote#139]
I think this is an important basic req: https://discord.com/channels/928190961455087667/1015169282444894219/1085917095583297606

**Comment by slyguy5646** [comment]
Hey there, wanted this feature for a project I'm working on and I think I have coded up a pretty decent solution.

**Comment by YousefED** [comment]
This should have been closed here: https://github.com/TypeCellOS/BlockNote/pull/154

See docs @ https://www.blocknotejs.org/docs/editor

**Comment by slyguy5646** [comment]
Is there a way to load this initial content from raw html or the json that tiptap gives back? For me it was awkard having to create the blocks and then pass it to the editor as the initial content.

**Comment by YousefED** [comment]
It's possible to convert to/from HTML, but not recommended. See https://www.blocknotejs.org/docs/converting-blocks

**Comment by slyguy5646** [comment]
> This should have been closed here: #154
> 
> See docs @ https://www.blocknotejs.org/docs/editor

This shows how to store it, thanks.

**Comment by slyguy5646** [comment]
Hey there, sorry to bother again. The only problem I see with this method of loading initial data is doing it with asynchronous data. I tried it utilizing a useEffect hook for data fetching which then sets the data to a state variable. This doesn't load because the  editor is instantiated before the data can be fetched. Is there a better way to accomplish this?

**Comment by YousefED** [comment]
two options

a) you could create the editor only after the data has been fetched
b) you could replace the initial content with `replaceblocks` when the data has been loaded: https://www.blocknotejs.org/docs/manipulating-blocks#replacing-blocks (little less nice imo)

**Comment by slyguy5646** [comment]
Got it thanks so much.
