### ISSUE TITLE
Customizing BlockNote Editor Styles

### ISSUE THREAD

**Issue by steven-tey** [TypeCellOS/BlockNote#144]
I've been trying to customize the editor's fonts using `_tiptapOptions` but it doesn't seem to work:

```
const editor: BlockNoteEditor | null = useBlockNote({
    onEditorContentChange: debouncedChanges,
    _tiptapOptions: {
      editorProps: {
        attributes: {
          class: "prose font-vercel text-red-600",
        },
      },
    },
  });
```

The goal is to handle all the styling via `@tailwind/typography`.

**Comment by mkarbo** [comment]
+1 for tailwind support

**Comment by YousefED** [comment]
You should now be able to pass `class: "prose font-vercel text-red-600",` to `editorDOMAttributes`, and set `defaultStyles` to false!

**Comment by steven-tey** [comment]
Wonderful! Thanks a lot @YousefED!

**Comment by steven-tey** [comment]
Works flawlessly <picture data-single-emoji=":chefs-kiss:" title=":chefs-kiss:"><img class="emoji" width="20" height="auto" src="https://single-emoji.vercel.app/api/emoji/eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..9Y0_eaxm29yIh0kM.59-5S4laxYjTmyuHLRl8RfNi7TE6-q2U6yLn4zUdZRcwTIqMBx1OPkQVeWgf9eaR3SZHVurT5W-PDADW6flnVhBDzUdDLtthn09FUWcfN16Mz1Ygqgo5dog.Xs_lXM29S5em0jAKVrcVvA" alt=":chefs-kiss:" align="absmiddle"></picture> thank you!
