### ISSUE TITLE
Image Support

### ISSUE THREAD

**Issue by d4mr** [TypeCellOS/BlockNote#145]
Does BlockNote have img capabilities yet? If not, does it have plugin/custom block development capabilities that would allow for adding img capabilities without forking?

PS: Incredible work on the project! I would love to contribute for adding image support, custom block support, or otherwise. Would greatly appreciate it if you could let me know where can I get started.

**Comment by Axibord** [comment]
I want to do the same thing, I was developing a similar library for my SaaS, then I discovered this 😲

**Comment by YousefED** [comment]
At this moment, we don't have Image support yet. I think we should include this soon :)

For UX, I think we should aim for a Notion-like UX where:
- images can be resized
- an (optional) caption can be added
- Options to align the image
- We can drag / drop images into documents

Nice to have:
- make it easy to include images from apis such as Giphy / Unsplash

The Atlaskit Prosemirror image element comes pretty close. See: https://atlaskit.atlassian.com/packages/editor/editor-core/example/kitchen-sink

The prosemirror element also supports text wrapping, but I doubt that works well (or is desirable) with our block-based design. Notion solves this by making it possible to have column-based block layouts - I think that should be our long-term solution.

Any other requirements you can think of?

**Comment by horacioh** [comment]
here's another example I found for an image component: https://gitlab.com/emergence-engineering/prosemirror-image-plugin

it has all the features you listed there @YousefED, I might try to hack it into BlockNote :)
