### ISSUE TITLE
Any ideas for react native implementation?

### ISSUE THREAD

**Issue by guifischer** [TypeCellOS/BlockNote#159]
Would love to be able to use that inside mobile apps as well

**Comment by YousefED** [comment]
I think a really native implementation is out of scope for now. However, it should be doable to create a react native webview wrapper around BlockNote. This would make it possible to interface with BlockNote from React Native, while we can still rely on the existing codebase for rendering, interactions, etc.

I'd be happy to help guide anyone interested in contributing this!
