### ISSUE TITLE
Support For Read-Only Mode?

### ISSUE THREAD

**Issue by thomasdohyunkim** [TypeCellOS/BlockNote#162]
Hi everyone.

Love the package and how beautiful the UI is. I was wondering if there is any way to enable "read-only" mode? I love writing content with the package but would love some way to publish my work and allow BlockNote to render it, but only provide edit permissions to specific users only.

Any support for this right now or any plans to support it in the future?

**Comment by YousefED** [comment]
Coming soon! follow along here; https://github.com/TypeCellOS/BlockNote/pull/135

**Comment by YousefED** [comment]
Closed by https://github.com/TypeCellOS/BlockNote/pull/135
