### ISSUE TITLE
Support for darkmode

### ISSUE THREAD

**Issue by stefan-krajnik** [TypeCellOS/BlockNote#169]
Are you planning to implement darkmode support ? I wanted to use the editor in my mantine app but in dark mode it doesn't look good at all. I saw some commented out theme related code. Are you planning to support it and if yes do you have any estimate when it may be available ?

Thanks a lot

**Comment by YousefED** [comment]
@stefan-krajnik this is WIP @ https://github.com/TypeCellOS/BlockNote/pull/171!

**Comment by stefan-krajnik** [comment]
great thanks
