### ISSUE TITLE
TODO items

### ISSUE THREAD

**Issue by YousefED** [TypeCellOS/BlockNote#18]
Add support for TODO items:

- TODO items should show a checkbox on the side
- The checked state should be stored in the prosemirror state
- If possible, content of checked todo items should appear strikethrough (I think we can do this directly from CSS)
- show "To-do" as placeholder

We currently store a listType attribute on Blocks. On first thought, we could:
a. use `listType="todo-checked"` and `listType="todo-unchecked"`
b. use `listType="todo"` and `todo-checked="true"` as attributes

Option B seems cleaner, but option A has other benefits (we don't need to clean for "invalid" Prosemirror states, for example, what does `listType="li"` and `todo-checked` mean? In that case `todo-checked` should be removed. What do you think is the best architecture for this?

**Comment by frogman544** [comment]
Any ETA for this?
