### ISSUE TITLE
Nextjs BlockNoteEditor TypeError

### ISSUE THREAD

**Issue by indrazm** [TypeCellOS/BlockNote#181]
Hey Folks. 

I am trying to use BlockNote with NextJS 13 (AppDir). 
I am using MacOs Ventrua 13.2.1

<img width="500" alt="image" src="https://user-images.githubusercontent.com/114550938/235290073-d9afa3a1-c443-469f-8958-49fcea96b6ea.png">

The way i am using it, i exactly did like the documentation. 

```js
"use client"

import { BlockNoteEditor } from "@blocknote/core"
import { BlockNoteView, useBlockNote } from "@blocknote/react"
import "@blocknote/core/style.css"

export default function PageEditor() {
    // Creates a new editor instance.
    const editor: BlockNoteEditor | null = useBlockNote({})

    // Renders the editor instance using a React component.
    return <BlockNoteView editor={editor} />
}
```
Please help.
Many Thanks :)

**Comment by YousefED** [comment]
closed by https://github.com/ProseMirror/prosemirror-view/pull/157.

Should be fixed when you upgrade the dependencies and use prosemirror-view 1.31.1

**Comment by Rimantovas** [comment]
Could you provide more context? Tried installing prosemirror-view 1.31.1, but that didn't change anything

**Comment by YousefED** [comment]
Can you try clearing node_modules and your lock file, and then doing a new npm install?

**Comment by Rimantovas** [comment]
Clearing all the node_modules and lock file fixed it. Thanks for the help
