### ISSUE TITLE
Block Side Menu still visible on hover when editor parent has visibility:hidden

### ISSUE THREAD

**Issue by empiriker** [TypeCellOS/BlockNote#185]
I used the BlockNote editor in my NextJS project where I placed the editor inside the content of an MUI Accordion. 

When the Accordion is closed, I still get the BlockSideMenu when hovering over the (invisible) blocks in the (invisible) editor.

Here is a screenshot of when my mouse hover over where the block element would be:

![image](https://user-images.githubusercontent.com/46843049/235469917-0f737aaa-3e64-44f9-ac8b-551481d959f5.png)

The fact that it's an MUI Accordion doesn't matter. It's still the same behaviour whenever the editor is a descendent of an element with visibility:hidden.

Here is a minimal example:
```
import { BlockNoteEditor } from '@blocknote/core';
import { BlockNoteView, useBlockNote } from '@blocknote/react';
import '@blocknote/core/style.css';

const App = () => {
  // Creates a new editor instance.
  const editor: BlockNoteEditor | null = useBlockNote({});

  // Renders the editor instance using a React component.
  return (
    <div style={{ visibility: 'hidden' }}>
      <BlockNoteView editor={editor} />
    </div>
  );
};

export default App;
```

My hacky solution is to use a useEffect hook based on the property that controls the accordion state (and thereby the css property visibility:hidden of the editors ancestor). 

  ```
useEffect(() => {
    const tippyElement: HTMLElement | null = document.querySelector('#tippy-1');
    if (tippyElement && !expanded) {
      tippyElement.style.visibility = 'hidden';
    }
  }, [expanded]);

```
But ideally this issue should be dealt with by BlockNote itself.

Thanks!

Edit: Issue #172 should probably fix what I describe here as well.

**Comment by YousefED** [comment]
Thanks, we'll look into this!
