### ISSUE TITLE
Tables support ?

### ISSUE THREAD

**Issue by AhmedRyad22** [TypeCellOS/BlockNote#194]
hi everyone, by any chance can we have tables in the editor ? or is there any way to add it as a block currently ?

thanks <3

**Comment by YousefED** [comment]
Hi @AhmedRyad22 ! This is on our roadmap, but we'll first focus on Custom Blocks and Images

**Comment by hsingh-ds** [comment]
@matthewlipski do you have any timeline for the table block? Because we need it asap, so I was thinking to create a custom block for table. Any thoughts?

**Comment by matthewlipski** [comment]
> @matthewlipski do you have any timeline for the table block? Because we need it asap, so I was thinking to create a custom block for table. Any thoughts?

We're currently working on fixing/improving HTML and Markdown conversions so table blocks are unfortunately gonna be a while still. Also you may have trouble implementing a table as a custom block as each BlockNote block has a single corresponding ProseMirror node, meaning it can only have a single piece of editable content.

**Comment by metaYogeshBhutkar** [comment]
@YousefED @matthewlipski by when can we expect the tables feature to roll out? The project that we are working on requires the use of Tables right now, I thought of implementing the tables feature all by myself using custom components, but that won't be feasible I think. It's just not possible to do it that way.

If you can let us know when are you going to merge the above PR #426, I can plan my proceedings accordingly.
