### ISSUE TITLE
Is there any way to hide block side menu or plus button?

### ISSUE THREAD

**Issue by jthw1005** [TypeCellOS/BlockNote#197]
Hi, Thank you so much for making this epic editor. This is just what I was looking for!

But by any chance, is there any way to hide block side menu or plus button?
I want sentences to stick to the left side of the editor.

Thanks again! :)

**Comment by YousefED** [comment]
Hi @jthw1005 ,

You can do this by setting `blockSideMenuFactory` to `undefined` (https://www.blocknotejs.org/docs/vanilla-js)

This will be easier after https://github.com/TypeCellOS/BlockNote/pull/219 is merged
