### ISSUE TITLE
Failed to load source map

### ISSUE THREAD

**Issue by nb312** [TypeCellOS/BlockNote#203]
when i run ·npm run start·
has an error:
`[vite] Failed to load source map for /@fs/home/nb/workspace/BlockNote/packages/core/src/extensions/UniqueID/UniqueID.ts.
`
do not have solve it .

system: ubuntu 20.04
Editor: VSCode

**Comment by YousefED** [comment]
@nb312 are you still running into this on the latest release?

**Comment by jerrycompal** [comment]
> @nb312 are you still running into this on the latest release?

I also encountered this issue. I am using the latest release of the system: Ubuntu 20.04 and the editor: VSCode.
