### ISSUE TITLE
Are there any custom tutorials related to buttons?

### ISSUE THREAD

**Issue by jerrycompal** [TypeCellOS/BlockNote#206]
I need to add a checkbox before the plus icon, and trigger its display and selection through Custom Items in the Slash Menu. This way, I can precisely select which contents need to be exported, quoted, set to read-only in real-time collaboration mode, and passed on to some AI models for further functions.

**Comment by YousefED** [comment]
@jerrycompal this is possible by [customizing](https://www.blocknotejs.org/docs/vanilla-js) the `blockSideMenuFactory`. The default React implementation is here: https://github.com/TypeCellOS/BlockNote/blob/496e20b7132f6c635b4e45833474f6c9bfd8f79d/packages/react/src/hooks/useBlockNote.ts#L70 

This is a bit advanced, there is no documentation related to this yet. I'll keep this issue open and would be great to hear if customizing this way works for your scenario

**Comment by matthewlipski** [comment]
Docs are now available for customizing both the side menu and slash menu, should hopefully be what you're looking for:
https://www.blocknotejs.org/docs/slash-menu#custom-slash-menu-item-list
https://www.blocknotejs.org/docs/side-menu
