### ISSUE TITLE
How do I control the 'editable: boolean' state via a button?

### ISSUE THREAD

**Issue by jerrycompal** [TypeCellOS/BlockNote#209]
How can I control the 'editable: boolean' state in real-time on an HTML page through a button?
Are there any sample codes related to this?
Here is my code, where did I make a mistake?

`function App() {
  const [isEditable, setIsEditable] = useState(true);
  const editor: BlockNoteEditor | null = useBlockNote({
    theme: "light",
    editable: isEditable,
    // ...
  });
  const toggleEditable = () => {
    setIsEditable(!isEditable);
  }
  useEffect(() => {
    console.log(`isEditable: ${isEditable}`);
    console.log(editor);
  }, [isEditable, editor]);
  // ...
  return (
    <div>
      <BlockNoteView editor={editor} />
      <button onClick={toggleEditable}>
        {isEditable ? "Lock Editor" : "Unlock Editor"}
      </button>
    </div>
  );`

**Comment by YousefED** [comment]
You can use `editor.isEditable = false`. We should add this to the docs

**Comment by YousefED** [comment]
fixed in 0.12, see BlockNoteView
