### ISSUE TITLE
[Suggestion] Sticky formatting tool bar

### ISSUE THREAD

**Issue by kienmatu** [TypeCellOS/BlockNote#212]
Currently, in our application, users need to select the text first in order for the toolbar to appear.

I'd like to propose an alternative mode where the format toolbar remains sticky at the header, like this:

![Sticky toolbar example](https://github.com/TypeCellOS/BlockNote/assets/38078992/9134a95a-89ab-447d-b1e0-e0496df80a1f)

In addition, can we toggle the slash menu on / off by specific user?

You can refer to the [Mantine v2 editor](https://v2.mantine.dev/others/rte/) for a visual representation of this feature.

**Comment by YousefED** [comment]
Hi @kienmatu ,

You could try disabling the formatting toolbar, by passing `formattingToolbarFactory: undefined` to `uiFactories` (see https://www.blocknotejs.org/docs/vanilla-js)

You should then be able to render the React `<FormattingToolbar />` in a place you should see fit.

Would love the here if this works for you, as it's an advanced scenario and I hope the current API is able to accommodate this

**Comment by kienmatu** [comment]
Thank you! @YousefED, It really helps!

**Comment by YousefED** [comment]
> Thank you! @YousefED, It really helps! But I think it would be a nice case if we support this case on some simple configuration.

Agree. Could you let us know if you can figure it out or share an example of this? Then we can decide whether it makes sense to make this a built-in option

**Comment by kienmatu** [comment]
I mean, this editor's purpose is for some people like me, who want a stable and enough-to-use editor without cusomize the code too much. 

So, It would be great if we do have a config like this, then we can save the setting for every single user's favorite.

```tsx
  const editor: BlockNoteEditor | null = useBlockNote({
    customStickyToolbar: FormattingToolbar,
    // and
    stickyToolbar: true,
    slashCommand: true,
    inlineToolbar: false,
  });
```

**Comment by YousefED** [comment]
@kienmatu that's a good proposal. It's not on our immediate roadmap, but I've tagged it as a good issue for contributors if people are interested in picking this up.

**Comment by vincelwt** [comment]
@kienmatu did you figure out how to make this work? Disabling the formattingToolbarFactory and then rendering it via `<FormattingToolbar editor={editor} />` returns a lot of error like this:

<img width="662" alt="image" src="https://github.com/TypeCellOS/BlockNote/assets/5092466/02f4b192-0251-4f6b-a2ea-4f84c4a02443">

Thanks!

**Comment by matthewlipski** [comment]
There's now an example on the docs website for making custom UI elements, including a static/sticky formatting toolbar - check it out here: https://www.blocknotejs.org/examples/custom-ui
