### ISSUE TITLE
editor.markdownToBlocks parse incorrectly

### ISSUE THREAD

**Issue by Adonis0123** [TypeCellOS/BlockNote#226]
```
const markdown = `
- 📝 item1
- ⚙️ item2
- 🔗 item3

# h1
`
const blocks: Block[] = await editor.markdownToBlocks(markdown);
console.log(blocks, "blocks");
```
I get the blocks.length is 3 , it seems look like lost  `# h1`

however, when the `# h1` is in the top
```
const markdown = `
# h1
- 📝 item1
- ⚙️ item2
- 🔗 item3
`
const blocks: Block[] = await editor.markdownToBlocks(markdown);
console.log(blocks, "blocks");
```
I get the blocks.length is 4 , it can correctly parsed `# h1` and list

[codesandbox](https://codesandbox.io/s/delicate-pond-ekb6pc?file=/App.tsx)

Is this a bug?

**Comment by thantos** [comment]
Seeing this too. Any content after a numeric or bulleted list when the markdown starts with the list is lost on conversion.
