### ISSUE TITLE
Could not find module in path: '@babel/runtime/helpers/interopRequireDefault' relative to '/index.tsx'

### ISSUE THREAD

**Issue by Hat52** [TypeCellOS/BlockNote#227]
On the website if you go the https://www.blocknotejs.org/docs/editor and scroll to the bottom of the page you we see this error

![image](https://github.com/TypeCellOS/BlockNote/assets/44437268/48d0c2ed-702a-47b3-9db4-14c82189fc12)

If you think this issue needs to be worked on, then I would Like to work on it .

**Comment by YousefED** [comment]
Hi,

It seems to work fine here. It could be that cleaning your browser cache solves the issue. If not, let me know
