### ISSUE TITLE
Problem with Nextjs (node:crypto)

### ISSUE THREAD

**Issue by wojtekolek** [TypeCellOS/BlockNote#228]
Hey, since I decided to update from `0.6.2` to the newest one (0.8.0) I'm struggling with the following issue:
<img width="786" alt="Screenshot 2023-06-01 at 09 13 06" src="https://github.com/TypeCellOS/BlockNote/assets/39329169/04e19864-524f-4f4a-ab85-29a0f17246dd">
Any idea what can cause this? Or maybe this is related directly to the `y-prosemirror`?

Mac M1 Max,
Node 20.1.0
Nextjs 13.4.4
Of course editor rendered on the client side 😄

**Comment by AhmedRyad22** [comment]
having same issue here, did you solve this ?

**Comment by YousefED** [comment]
Hi,

I can't seem to reproduce this on node 20 + latest nextjs. Could you try cleaning your node_modules? If you still have this issue, could you provide a reproducible example / sandbox?

**Comment by YousefED** [comment]
I'm closing this as we don't have a reproducible example. We're adding some more guidance on nextjs that might resolve this: https://github.com/TypeCellOS/BlockNote/pull/274

Let us know if you're still having this issue!
