### ISSUE TITLE
 Error [ERR_REQUIRE_ESM]: require() of ES Module while using NX monorepo

### ISSUE THREAD

**Issue by hitwill** [TypeCellOS/BlockNote#241]
**Describe the bug**
Error on compile while using NX mono-repo
![image](https://github.com/TypeCellOS/BlockNote/assets/2501079/22f0540d-b86e-42d2-bf9d-2249b7274c20)

This issue does not happen with a vanilla NextJS app. However, it happens on NX  Monorepo

**To Reproduce**
Install [NX](https://nx.dev/getting-started/intro)
Create a new app: `nx g @nx/next:app my-app`
Install BLocknote: `npm i @blocknote/react`

Add the code to index.tsx of your app
```javascript
import styles from './index.module.css';
import { Inter } from 'next/font/google';
import { BlockNoteView, useBlockNote } from '@blocknote/react';
import '@blocknote/core/style.css';

const inter = Inter({ subsets: ['latin'] });

export function Index() {
  const editor = useBlockNote({
    onEditorContentChange: (editor) => {
      // Log the document to console on every update
    },
  });
  return (
    <div className={styles.page}>
      <div className="wrapper">
        <div className="container">
          <div id="welcome">
            <h1>
              <span> Hello there, </span>
            </h1>
          </div>
          <div>
            {' '}
            <BlockNoteView editor={editor} />
          </div>
        </div>
      </div>
    </div>
  );
}

export default Index;
````

**Misc**
- Node version:18.11.0 and 20.3.0
- Package manager: tried with NPM and Yarn

**Comment by hitwill** [comment]
I am not sure whether to list this as a bug since it happens specifically with NX.

**Comment by guptabhaskar** [comment]
I'm also facing the same issue, is there a good way to fix/avoid this?

I added this to my next.config.js which fixed the issue but I don't think this is a good idea for the long term:
`experimental: { esmExternals: true }`

**Comment by YousefED** [comment]
This should be addressed here! https://github.com/TypeCellOS/BlockNote/pull/274

Let me know if you're still running into this issue

**Comment by YousefED** [comment]
Are you using the latest version of blocknote @Ianduha13 ?

**Comment by hitwill** [comment]
@Ianduha13 If you are on NextJS, please see this: https://www.blocknotejs.org/docs/nextjs
