### ISSUE TITLE
Documentation website is down

### ISSUE THREAD

**Issue by gpawlik-cais** [TypeCellOS/BlockNote#244]
Website https://www.blocknotejs.org/ is not reachable

<img width="694" alt="Screenshot 2023-06-16 at 10 09 07" src="https://github.com/TypeCellOS/BlockNote/assets/133682010/2496d2f1-e321-43ee-90aa-f15a56f54dab">

**Comment by YousefED** [comment]
Seems online again?

**Comment by gpawlik-cais** [comment]
Yes, that's right 👍
