### ISSUE TITLE
Positioning of Slash Menu according to cursor.

### ISSUE THREAD

**Issue by ishpaul207** [TypeCellOS/BlockNote#251]
When the cursor is positioned too low or too far to the right, slash menu goes out of screen and acts weird, same is the case when cursor is in right side of screen. is there a workaround to place it according to the cursor position?

![Untitled video - Made with Clipchamp](https://github.com/TypeCellOS/BlockNote/assets/123591487/14a7e02d-5b4f-41af-a09c-f53ee833650b)

**Comment by YousefED** [comment]
@matthewlipski can you see if you can reproduce this and whether this is also fixed in #250 ?

**Comment by matthewlipski** [comment]
Fixed in v8.0.2!
