### ISSUE TITLE
insertText support？

### ISSUE THREAD

**Issue by tsl1127** [TypeCellOS/BlockNote#252]
Is there support for insertText(or whatever) in currentBlock?

**Comment by YousefED** [comment]
At this moment there is only support for `updateBlock` to update an entire block. You can use it to change the text in the `content` field of a block. 

I think inserting text at a particular point is a valid request, especially because it will work better with multi-user collaboration

**Comment by tsl1127** [comment]
1、thanks for reply
2、Not only in terms of multi-user collaboration, but also from a code perspective, automatically inserting text can be quite useful. For example, when a block's content consists of multiple texts, if the cursor is placed within a particular text, applying the style of that text and automatically adding more text (through code) can be achieved.
3、Will this be added to the roadmap in the future?

**Comment by YousefED** [comment]
@tsl1127 Yes, we definitely want to add this to BlockNote. Thanks for extra details in (2)

**Comment by WoetDev** [comment]
Also in need of this feature! 💯

**Comment by YousefED** [comment]
see https://www.blocknotejs.org/docs/editor-api/manipulating-inline-content#inserting-inline-content
