### ISSUE TITLE
Use inside inline iframe

### ISSUE THREAD

**Issue by nilooy** [TypeCellOS/BlockNote#254]
I have an ui editor inside iframe and i tried to add BlockNote in it. It's getting an error when i try to use slash menu

**`getBoundingClientRect of undefined`** i guess which is because in iframe it needs to have iframe's document access.
is it possible at the moment to switch the global window context to a custom one (in this case to the iframe one)

i'm using `react-frame-component` for iframe and added BlockNote in it. following the basic tutorial from the docs, i tested without iframe, where it works beautifully.

**Comment by nilooy** [comment]
> Thanks @nilooy . Do you happen to have a codesandbox or other repl that reproduces this?

Yes here it is https://codesandbox.io/s/kind-https-lnmgzw?file=/src/App.js

**Comment by YousefED** [comment]
Let me know if this still occurs in 0.12, closing for now
