### ISSUE TITLE
marks are lost when merging blocks

### ISSUE THREAD

**Issue by horacioh** [TypeCellOS/BlockNote#255]
**Describe the bug**
When I have a block content with marks applied and the cursor at the beginning of the block, when pressing Backspace the marks disappears

**To Reproduce**
1. create an empty block and a block below with some content with formatting
2. move the cursor to the beginning of the second block
3. press backspace

**Misc**

https://github.com/TypeCellOS/BlockNote/assets/725120/461632f0-701d-4a7f-8a93-d51783de9d36

**Comment by horacioh** [comment]
I see the TODO comment about using Slices, but not sure if this could be solved by taking the content fragment and insert it ar the end of the previous available content fragment?

is Fragment and Slices the same thing?

**Comment by matthewlipski** [comment]
Fixed in v8.0.2, thanks!
