### ISSUE TITLE
Empty text causes parsing errors when pasting text from other sites or media

### ISSUE THREAD

**Issue by asplin39** [TypeCellOS/BlockNote#258]
**Describe the bug**
An error occurs when copying LINE chat text and pasting it into the editor.

**To Reproduce**
Official LINE Chat screen.:
<img width="531" alt="スクリーンショット 2023-06-23 18 43 40" src="https://github.com/TypeCellOS/BlockNote/assets/27346932/80bdb27e-e4be-4502-8949-3406d606ea1f">

content data is:
[{"id": "b9064255-9890-471f-bd90-d669a0f6cc92", "type": "paragraph", "props": {"textColor": "default", "textAlignment": "left", "backgroundColor": "default"}, "content": [{"text": "Empty text causes parsing errors when pasting text from other sites or media", "type": "text", "styles": {}}, {"text": "", "type": "text", "styles": {}}, {"text": "**Describe the bug**", "type": "text", "styles": {}}, {"text": "", "type": "text", "styles": {}}, {"text": "An error occurs when copying LINE chat text and pasting it into the editor.", "type": "text", "styles": {}}], "children": []}, {"id": "9f298e5a-20f9-4c03-ab64-7370246e52c9", "type": "paragraph", "props": {"textColor": "default", "textAlignment": "left", "backgroundColor": "default"}, "content": [], "children": []}]

**Misc**
- Node version: 16.16.0
- "@blocknote/core": "^0.7.1-alpha.0",
- "@blocknote/react": "^0.7.1",

**Comment by YousefED** [comment]
What is the error you are getting?
