### ISSUE TITLE
undo/redo support？

### ISSUE THREAD

**Issue by tsl1127** [TypeCellOS/BlockNote#261]

**Comment by matthewlipski** [comment]
Is this not working with ctrl+z and ctrl+shift+z? What issues are you running into?

**Comment by tsl1127** [comment]
use tiptap command will be ok；you can close this issue thank you!  @matthewlipski

**Comment by YousefED** [comment]
@matthewlipski do you think it makes sense to add undo / redo methods to the editor?

**Comment by sindras** [comment]
> Is this not working with ctrl+z and ctrl+shift+z? What issues are you running into?

@matthewlipski @YousefED This would be a useful feature for mobile web users, as they won't use keyboard. Try looking at excalidraw or Slack for reference - they have nice undo/redo buttons.

**Comment by YousefED** [comment]
@sindras it seems like you want to be able to add undo / redo buttons and need a function to access this functionality. Makes sense. Could you create a new issue for this?

Also, curious to hear what you're building!
