### ISSUE TITLE
Customizing the Background Color, Padding, & Default Text Color of the Editor

### ISSUE THREAD

**Issue by sylviangth** [TypeCellOS/BlockNote#262]
**Is your feature request related to a problem? Please describe.**
I wanted to change the the background color of the BlockNoteEditor to align with my app's color. However, the background of the current version of BlockNoteEditor is always either white (light theme) or black (dark theme).

<img width="463" alt="Screen Shot 2023-06-27 at 14 18 26" src="https://github.com/TypeCellOS/BlockNote/assets/111867146/56cf143f-9da7-466b-8a77-f50177502e71">

**Describe the solution you'd like**
I would appreciate if I can customize the **background color of the editor by specifying the color** when calling useBlockNote() or just leave the background of the editor **transparent** so it can fit perfectly with the background color of my app. Besides, it would be great if I can also customize the padding and the default text color.

**Comment by YousefED** [comment]
Agree, we should pick this up! Have you tried doing this directly with CSS?

**Comment by sylviangth** [comment]
> Agree, we should pick this up! Have you tried doing this directly with CSS?

I've tried using CSS mix blend modes to blend the background of the editor with the background with my app. It... sort of works, but still the result's colors are no longer pure like before. I think this is only a temporary solution. Still really hope that I have the option to customize the background color, padding and default text color.

**Comment by sylviangth** [comment]
Hi, any update on this?

**Comment by matthewlipski** [comment]
Sorry for the delay! You can add a class to the editor using the `editorDOMAttributes` option (https://www.blocknotejs.org/docs/editor#editor-options):
```
editorDOMAttributes: {
  class: "blockNoteEditor"
}
```
Right now you have to use `!important` to override default styling, but we're looking to revamp editor styling in the near future:
```
.blockNoteEditor {
  background-color: red !important;
}
```

**Comment by sylviangth** [comment]
> Sorry for the delay! You can add a class to the editor using the `editorDOMAttributes` option (https://www.blocknotejs.org/docs/editor#editor-options):
> 
> ```
> editorDOMAttributes: {
>   class: "blockNoteEditor"
> }
> ```
> 
> Right now you have to use `!important` to override default styling, but we're looking to revamp editor styling in the near future:
> 
> ```
> .blockNoteEditor {
>   background-color: red !important;
> }
> ```

That works! Thank you so much!
