### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'execute')

### ISSUE THREAD

**Issue by enqtran** [TypeCellOS/BlockNote#269]
**Describe the bug**
There was an error with command / when there was no item

<img width="242" alt="image" src="https://github.com/TypeCellOS/BlockNote/assets/10077246/554ad791-7667-4413-b2ad-d824e991385a">

<img width="663" alt="image" src="https://github.com/TypeCellOS/BlockNote/assets/10077246/580ab09b-e975-4c9b-833f-0903cb9bb26a">

Version:
"@blocknote/core": "^0.8.2",
"@blocknote/react": "^0.8.2",

**Comment by matthewlipski** [comment]
Thanks for reporting this one, will be fixed soon!
