### ISSUE TITLE
Block IDs not being preserved during drag & drop

### ISSUE THREAD

**Issue by matthewlipski** [TypeCellOS/BlockNote#273]
Currently, dragging and dropping a block anywhere in the editor resets its ID. The drag start handler gets the entire `blockContainer` element, so BlockNote should be able to read the ID from the `data-id` attribute. It seems like something might be going wrong in the UniqueID plugin that's causing this to happen.

**Comment by bryanmylee** [comment]
Where would we start to look to fix this?

**Comment by bryanmylee** [comment]
In the meantime, a simple workaround is to store the real `id` in props and rely on that for your source of truth.

**Comment by bryanmylee** [comment]
Actually, this might be intended (or at least unintentionally useful) behaviour.

I'm noticing an odd behaviour where dragging and dropping a block in some cases leaves behind an empty paragraph block with the original ID.

By storing the actual ID in props, I can look up the previous location of a moved block using `editor.getBlock` then perform custom cleanup code between the drag start and end locations, but ideally we'd have a better interface for this.

**Comment by matthewlipski** [comment]
The current drag/drop handling just changes the clipboard data that gets cut & pasted during drag & drop. I think it might make sense to instead use the existing `editor.removeBlocks` and `editor.insertBlocks` functions on drop. This would be nice as we could re-use existing code and it shouldn't cause this bug with leaving behind an empty block.

I think it's worth trying at least, pretty much all the necessary code should go in `DraggableBlocksPlugin.tsx`.
