### ISSUE TITLE
Style not getting applied to all the selected blocks

### ISSUE THREAD

**Issue by suryansh-wattoai** [TypeCellOS/BlockNote#278]
**Describe the bug**
When selecting multiple blocks at the same time and then applying a style like bulleted or numbered list, the style only gets applied to the first block. Ideally, it should get applied to all the blocks. 

**To Reproduce**
As described above.

**Misc**
- Node version: v20.3.0
- Package manager: npm@9.6.7
- Browser: Google chrome
- [ ] I'm a [sponsor](https://github.com/sponsors/YousefED) and would appreciate if you could look into this sooner than later 💖

**Comment by matthewlipski** [comment]
This is an intended design decision that we made previously, but I agree that the block type should be applied to all selected blocks since that's how styles and text alignment already works. @YousefED agree with this?

**Comment by YousefED** [comment]
Yes, I think that makes sense
