### ISSUE TITLE
Bug of drag dragHandleMenu

### ISSUE THREAD

**Issue by I-am-old-wang** [TypeCellOS/BlockNote#283]
**Describe the bug**
When I drag dragHandleMenu, I get the following error:
Uncaught TypeError: Cannot destructureproperty 'node' of 'g( ...)' as it is undefined. at BlockNoteEditor.ts:352
**To Reproduce**
Code Example:
> const editor = useBlockNote({
>    customElements: {},
>    initialContent: undefined,
>    onEditorContentChange: (editor) => {},
>    onTextCursorPositionChange: (editor) => {
>      // This is the source of the error. 
>  ` const hoveredBlock = editor.getTextCursorPosition().block;`
> },
>   });

**Misc**
- Node version:18.16.0
- Package manager:
- Browser:

**Comment by matthewlipski** [comment]
@I-am-old-wang Should be fixed in 0.8.3
