### ISSUE TITLE
License idea

### ISSUE THREAD

**Issue by junoriosity** [TypeCellOS/BlockNote#284]
@YousefED The current license is MLP-2. However, for the success of this editor, I believe it would be advantageous, if we have a more permissive license like MIT or Apache-2.

Is there a reason we the license for Prosemirror and TipTap is MIT and this one is MLP-2?

**Comment by YousefED** [comment]
@junoriosity thanks for the feedback. I've added some more detail about this in #287. The MPL-2 license is quite permissive and allows you to use the project in commercial applications. The parts we like about the license is that if anyone makes a lot of changes / improvements to the BlockNote source files for his / her project, the rest of the community can benefit as well.

If the license is a blocker for you, let me know!

**Comment by junoriosity** [comment]
@YousefED Many thanks for getting back to me. Speaking for myself and likely for many others, one sometimes feels very insecure about that license, simply, because one is not quite sure of how the legal requirements do look like. 

That question does not arise for MIT and Apache-2, simply because everyone knows them (as they are used quite often) and they are very nice in terms of permissiveness. 

From my perception, idealistic people are way more abundant than the opposite, which is why a license like MIT or Apache-2 will attract more people to it, simply because they are more familiar with it. Then that larger number is likely going to make such huge progress by pull requests etc. (count me in), that anybody who would clone the code and work for himself, would not be able to keep up the pace.

Hence, if you could change it to MIT and Apache-2, you would likely do many people a huge favor and benefit the project a lot at the same time. :)
