### ISSUE TITLE
Bundle Size is really big, Better to get Rid of Mantine Lib and write our own code

### ISSUE THREAD

**Issue by ursnj** [TypeCellOS/BlockNote#286]
**Describe the bug**

Bundle Size is really big, Better to get Rid of Mantine Lib and write our own code

**To Reproduce**

Build the project and see the output with and without blocknote.

**Misc**
- Node version:
- Package manager:
- Browser: 
- [ ] I'm a [sponsor](https://github.com/sponsors/YousefED) and would appreciate if you could look into this sooner than later 💖

**Comment by YousefED** [comment]
@ursnj I think this is good feedback. It would make sense to extract the Mantine code, and make it available as a separate package (e.g.: blocknote-react-mantine). 

We could then also support different UI frameworks in different packages. Would be interesting to hear what UI libraries people might be interested in. For example:

- React Spectrum / React Aria: https://react-spectrum.adobe.com/
- Ariakit: https://ariakit.org/
- Headless UI: https://headlessui.com/
- ...

Imo these would also be great candidates for the community to collaborate on!

**Comment by horacioh** [comment]
I'm vote for changing to either React Spectrum or Ariakit...

the main issue here I believe is balance supporting a cleaner and accessible solution and a headless/no styles solution for folks who want to adapt to their app styles...

not sure what is the best approach yet..

**Comment by ursnj** [comment]
@YousefED Shadcn also promising in this kind of cases, as it exposes independent components and fully accesible, we can only bundle the components we are using so it will be more independent and bundle size is absolutely lean.

**Comment by NiluK** [comment]
yeah shadcn is ideal imo

**Comment by gooooooooney** [comment]
I think shadcn is cool

**Comment by meetshukla** [comment]
shadcn would be the best for this type of application

**Comment by florisbosch** [comment]
+1 for this 👍 
shadcn is awesome

**Comment by horacioh** [comment]
It seems that chadcn is the most popular answer here. I would like to understand how are you using it in your apps? because as far as I know this is not a real NPM UI Library but a set of "examples" you need to copy paste into your app.

am I missing something?
