### ISSUE TITLE
How do I add in margin / padding from the x-axis?

### ISSUE THREAD

**Issue by eRuaro** [TypeCellOS/BlockNote#310]
**Describe the bug**
I can't add margin or padding from the x-axis. Here's a screenshot:
![image](https://github.com/TypeCellOS/BlockNote/assets/69240261/434ff4aa-65fa-4b1d-89ef-f4426b9ba65f)

As you can see, the `ml-10` can't be seen from the `inspect` tool.

**To Reproduce**
Use this code:
```
<main>
	<div className="py-6">
		<div className="mt-10 ml-10">
			<BlockNoteView editor={editor} />
		</div>
	</div>
</main>
```

**Misc**
- Node version: 19.6
- Package manager: NPM
- Browser: Firefox

**Comment by matthewlipski** [comment]
A better way of doing this is using the `domAttributes` editor option - try:
```ts
const editor = useBlockNote({
  domAttributes: {
    editor: {
      class: "mt-10 ml-10",
    },
  },
});
```
This will set the class on the editor element. You can also do:
```ts
return <BlockNoteView className={"py-6"} editor={editor} />
```
Which will set the class on the editor wrapper, i.e. the `div` containing the editor and all menus/toolbars.

**Comment by eRuaro** [comment]
Works for me, thanks! 🫡
