### ISSUE TITLE
TypeError: node_modules\linkifyjs\dist\linkify.es.js: set.clone is not a function.

### ISSUE THREAD

**Issue by amol-cubyts** [TypeCellOS/BlockNote#317]
**Describe the bug**
Getting the following error while trying to run the Blocknote code in [Ant Design Pro 4.5.0](https://v4-pro.ant.design/) javascript project. 
```
Module build failed (from ./node_modules/@umijs/deps/compiled/babel-loader/index.js):
TypeError: D:\React App\antd-pro-4.5.0-sample\node_modules\linkifyjs\dist\linkify.es.js: set.clone is not a function
```
![image](https://github.com/TypeCellOS/BlockNote/assets/106859162/4ee9b67c-f75a-4d4d-980f-dc39c97ec703)

Code 
```
import React from "react";
import { BlockNoteView, useBlockNote } from "@blocknote/react";

export default () => {
  const editor = useBlockNote({});
  return (
    <div>
      <h1>Block Editor</h1>
      <div style={{ border: "2px solid red" }}>
        <BlockNoteView editor={editor} />
      </div>
    </div>
  );
};
```

**To Reproduce**
- Checkout to [antd-pro-4.5.0-sample](https://github.com/amol-cubyts/antd-pro-4.5.0-sample) repo.
- yarn install 
- yarn start 
- It will be through above error
- File path to Blocknode code 
    - `antd-pro-4.5.0-sample\src\pages\blockEditor\BlockEditor.jsx`
- Localhost URL of the application
    - `http://localhost:8000/result/blockeditor`
- Without Block notes code this react application works fine.    

**Misc**
- Node version: 16.0.0
- Package manager: 7.10.0
- Browser: Chrome 
- React: 16.14.0
- Antd Pro: 4..5.0

**Comment by matthewlipski** [comment]
Can you try using node v18 and see if the error still persists?

**Comment by amol-cubyts** [comment]
@matthewlipski Thanks, but getting the same error with node v18 as well.

**Comment by YousefED** [comment]
Let me know if you still have this with 0.12. Closing for now
