### ISSUE TITLE
How to use BlockNoteEditor in node js

### ISSUE THREAD

**Issue by boopeshmahendran227** [TypeCellOS/BlockNote#319]
**Is your feature request related to a problem? Please describe.**
I would like to use the `BlockNoteEditor` in node js, so that I can send the steps to backend and apply the changes using schema in backend. I am using nest js

I tried this below code

```typescript
import { BlockNoteEditor } from '@blocknote/core';
const editor = new BlockNoteEditor();
const schema = editor._tiptapEditor.schema;
```

but I was getting the below error 

`Error [ERR_REQUIRE_ESM]: require() of ES Module` related to rehype-parse, then I overrided all dependencies similar to rehype to the version that supported common js using pnpm overrides

But now I am getting `window is not defined` error in UniqueID, so how should I use the schema in backend so that I can make changes in the backend using the prosemirror schema.

**Comment by YousefED** [comment]
closed by https://github.com/TypeCellOS/BlockNote/pull/303

**Comment by boopeshmahendran227** [comment]
Thanks a lot @YousefED Any tentative timeline on when it will be released?

**Comment by matthewlipski** [comment]
Probably end of this week or the next👍
