### ISSUE TITLE
Perf issues with a large document

### ISSUE THREAD

**Issue by boopeshmahendran227** [TypeCellOS/BlockNote#320]
**Describe the bug**
When we create a large document, editing is becoming very slow, we ran some profiling and found out that placeholder extension causes it, so can we expose an option to disable this

**Comment by boopeshmahendran227** [comment]
I would greatly appreciate it if you could provide me with any updates on this issue. Thank you!

**Comment by YousefED** [comment]
Can you describe what's considered a "large" document in your use-case? How large approximately?
