### ISSUE TITLE
Table Support

### ISSUE THREAD

**Issue by aismartchat** [TypeCellOS/BlockNote#330]
**Is your feature request related to a problem? Please describe.**
You've built a great library. Do you plan to add table support? 

**Describe the solution you'd like**
Today modern editors need tables. 

**Describe alternatives you've considered**
We either consider taking notitap because it has embedded table support.

**Comment by ursnj** [comment]
Yeah table support is much needed one

**Comment by matthewlipski** [comment]
We're planning to implement table blocks soon! Gonna close this issue though since it's a duplicate of #194
