### ISSUE TITLE
Blocknote menu cannot be summoned after it is dismissed without creating a block

### ISSUE THREAD

**Issue by teyc** [TypeCellOS/BlockNote#353]
**Describe the bug**
 Blocknote menu cannot be summoned after it is dismissed without creating a block

**To Reproduce**

1. Open Firefox / Chrome / Edge
2. Go to https://www.blocknotejs.org/
3. use the mouse hover over the left hand side of the block note, 
4. click on it to reveal the menu
5. click outside the menu area to dismiss the menu
6. now use the mouse to hover over the left hand side of the block note

Observe that the menu hover is no longer visible. Now type into the blocknote, and move mouse again, the menu hover reappears as expected

**Misc**
- Node version:
- Package manager:
- Browser: 
- [ ] I'm a [sponsor](https://github.com/sponsors/YousefED) and would appreciate if you could look into this sooner than later 💖

**Comment by matthewlipski** [comment]
Hi, if I understand correctly - the behaviour you're seeing is that the [side menu](https://www.blocknotejs.org/docs/side-menu) doesn't show on block hover after the drag handle menu is opened and then closed?

**Comment by teyc** [comment]
Yes that’s right, the menu is re-enabled once you type something into the block note

**Comment by matthewlipski** [comment]
Hmm I'm not seeing this behaviour on https://www.blocknotejs.org/ - we published version 0.9.4 on Tuesday which may have fixed it. Can you check if this is still happening and provide a gif/video if it is?

**Comment by matthewlipski** [comment]
Gotcha, thought the issue was with the drag handle menu instead, which explains why I couldn't reproduce it👍
