### ISSUE TITLE
how can i reinitialize editor content

### ISSUE THREAD

**Issue by Ayan-Amir** [TypeCellOS/BlockNote#374]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by matthewlipski** [comment]
You can call `editor.replaceBlocks(editor.topLevelBlocks, newContent)` to replace all blocks with a set of new ones, where `newContent` is an array of `Block` objects.

**Comment by 18601673727** [comment]
> You can call `editor.replaceBlocks(editor.topLevelBlocks, newContent)` to replace all blocks with a set of new ones, where `newContent` is an array of `Block` objects.

Hi @matthewlipski, how to remove all blocks when I don't have the access of `editor` from parent component in next.js environment? I simply want to wipe clean after user submitted a form. Thank you!
