### ISSUE TITLE
onEditorContentChange is not being called when updating alert type in Alert block example ( custom blocks )

### ISSUE THREAD

**Issue by GiladVyzer** [TypeCellOS/BlockNote#377]
**Describe the bug**
After adding onEditorContentChange functionality to the Alert Block example (https://www.blocknotejs.org/examples/alert-block),
 the function is not being called when changing the alert type.

Additionally, after editing the inline content that triggers the 'onEditorContentChange' function, the block props have wrong type.

<img width="581" alt="image" src="https://github.com/TypeCellOS/BlockNote/assets/75206171/8cd65186-ce1b-4a9d-bd31-32d80c56a144">

**To Reproduce**
1. Visit https://codesandbox.io/s/hardcore-meitner-cvh3kl
2. Change the type of the alert.

**Misc**
- Package manager: npm
- Browser: Chrome

**Comment by matthewlipski** [comment]
Thanks! This is fortunately just a bug in the Alert block's component rather than an internal BlockNote issue. PR with the fix is up and will be merged soon👍
