### ISSUE TITLE
image resizing is possible when editable is false

### ISSUE THREAD

**Issue by GrahamQuan** [TypeCellOS/BlockNote#384]
**Describe the bug**
<what's going wrong!?>
When useBlockNote is set to `{ editable: false }`
1. image resizing is still possible
2. the `onEditorContentChange` function will still be called when doing step 1

**To Reproduce**
<links to a sandbox or clear steps to reproduce are super helpful!>
none

**Misc**
- Node version: v18.12.1
- Package manager: 
    + "@blocknote/core": "^0.9.5",
    + "@blocknote/react": "^0.9.5",
- Browser: Edge 118.0.2088.46 
- [ ] I'm a [sponsor](https://github.com/sponsors/YousefED) and would appreciate if you could look into this sooner than later 💖

simple code
``` js
  const editor: BlockNoteEditor = useBlockNote({
    editable: false, // public preview mode here
    initialContent,
    onEditorContentChange: () => {
      console.log('runs when resize image')
     // API calls need to be authenticated
    },
    uploadFile,
  })
```

**Comment by Lodimup** [comment]
discovered the same problem

**Comment by eademir** [comment]
Same here. blocknote core + react 9.5 and 9.4 and 9.3 have the same problem. Nextjs 13.4.12 and 13.5.6. imported via dynamic/next.
