### ISSUE TITLE
Side menu is incorrectly positioned in the middle of a block

### ISSUE THREAD

**Issue by lucasfcosta** [TypeCellOS/BlockNote#386]
**Describe the bug**

On Notion, the position of the side menu is positioned at the start of each block, as shown below.

<img width="756" alt="Screenshot 2023-10-19 at 16 27 33" src="https://github.com/TypeCellOS/BlockNote/assets/6868147/d0ca3e4d-9147-4a97-ae71-6af5932612f2">

In BlockNote, the side menu is positioned in the _middle_ of each block, which is inconsistent with the notion-like behaviour it aims to be similar to.

![incorrectpos](https://github.com/TypeCellOS/BlockNote/assets/6868147/00cc6773-80b9-40ac-870a-0ad713e38f6e)

**To Reproduce**

Just create a multi-line block and hover over the paragraph.

**Comment by matthewlipski** [comment]
This is a good point, since we do want BlockNote to offer as similar UX to Notion as possible. I think the reason we originally decided not to do this, is that it looks a bit off for blocks which aren't very tall (e.g. headings). But this is something we can look into changing. @YousefED what's your opinion on this?

**Comment by man-shar** [comment]
hello hello, was there any updates to this feature request?

**Comment by YousefED** [comment]
> This is a good point, since we do want BlockNote to offer as similar UX to Notion as possible. I think the reason we originally decided not to do this, is that it looks a bit off for blocks which aren't very tall (e.g. headings). But this is something we can look into changing. @YousefED what's your opinion on this?

I think top alignment is definitely better. If it looks weird on any of the blocks (test this), then let's discuss here

**Comment by man-shar** [comment]
Thank you for checking in again!

I also prefer top as a fix for the taller blocks.

Is it possible at all to give a prop with, say, three options: `top`, `middle` and `bottom`? (Or even provide a custom function which is given the relevant block and drag handle's dom?). 

I understand if the code for placing the drag-handle is super deep inside a plugin to make this infeasible though.
