### ISSUE TITLE
Custom inline tags in a block

### ISSUE THREAD

**Issue by hsingh-ds** [TypeCellOS/BlockNote#388]
I am using block tunes in my react app. I want to add custom inline tags inside a block. How can I do that from custom toolbar menu? For example I want to add custom toolbar button which will add the selected text to a custom html tag and replaces that text content with created tag inside the block.

**Comment by matthewlipski** [comment]
Unfortunately this isn't possible rn as it requires being able to define custom inline nodes. This is something we're planning to implement in the future.

**Comment by sahilpohare** [comment]
can I add this using the exposed tiptap editor??
@matthewlipski
