### ISSUE TITLE
Ability to add custom editorProps in _tiptapOptions

### ISSUE THREAD

**Issue by man-shar** [TypeCellOS/BlockNote#389]
Currently the editorProps get overwritten in [BlockNoteEditor](https://github.com/TypeCellOS/BlockNote/blob/c448aac923543e85dd7638d8536e5f0e6db1d1d1/packages/core/src/BlockNoteEditor.ts#L287).

Perhaps I'm overlooking something, but should be a tiny fix of adding `...newOptions.editorProps` within that object?

Currently used a hack `editor.prosemirrorView._props.handleDrop = ...`

Thank you!

**Comment by matthewlipski** [comment]
Good point! Though since this is directly accessing the TipTap API, you'll probably instead pass them to `_tiptapOptions.editorProps`
