### ISSUE TITLE
Starting a new block sometimes removes the last character of the preceding line

### ISSUE THREAD

**Issue by RegisFrey** [TypeCellOS/BlockNote#39]
- Starting a new block with the + button on a line that doesn't yet have a block
- while text cursor is on a line above
- removes the last character of the line above

<img width="413" alt="YousefED_BlockNote_Bug_Eating-letter-1" src="https://user-images.githubusercontent.com/156893/187290709-71775485-b1d9-4f35-95eb-a1648806c3e7.png">
<img width="413" alt="YousefED_BlockNote_Bug_Eating-letter-2" src="https://user-images.githubusercontent.com/156893/187290730-05968dc3-9c7b-424f-8449-a85461b4f9b6.png">

Google Chrome: Version 104.0.5112.101 (Official Build) (x86_64)
Module: https://blocknote-main.vercel.app/assets/index.5682e973.js

**Comment by RegisFrey** [comment]
Issue aside this seems a very neat effort to build some batteries included UI for TipTap. Thank you.

**Comment by YousefED** [comment]
Thanks for reporting this and the feedback! Will look into it for the next batch of fixes

**Comment by YousefED** [comment]
closed by https://github.com/TypeCellOS/BlockNote/pull/76

**Comment by inhanbyeol94** [comment]
@YousefED The above example is what happens when you are in Korean.

example)
typing: 안녕하세요
result: 안녕하세
