### ISSUE TITLE
could the default prop value be a callback?

### ISSUE THREAD

**Issue by man-shar** [TypeCellOS/BlockNote#394]
Would look pretty straightforward, not sure how hard it is to implement though.

```
...
propSchema: {
  id: {
    default: () => `id-${Math.random()}`
  }
}
...
```

Thank you!

**Comment by matthewlipski** [comment]
I think this should be doable, thanks for the suggestion👍

**Comment by YousefED** [comment]
@man-shar do you still need this? If so, could you share more details about the use-case?

**Comment by man-shar** [comment]
Definitely not a must have. My use case was that the props had to be randomised/created, for eg:

```jsx
{
  propSchema: {
        creationTimeStamp: {
          default: () => new Date().toISOString(),
        },
      },
}
```

But no issues if it's not a good use of your time.

I can definitely do it the normal way: have a null default and a check inside the render method:
```jsx
{
    propSchema: {
      creationTimeStamp: {
        default: null,
      },
    },
    content: "none",
  },
  {
    render: ({ block, editor }) => {
      if (block.props.creationTimeStamp == null) block.props.creationTime = new Date().toISOString();

     <Component creationTime={creationTime}/>
}
```

**Comment by YousefED** [comment]
Alright thanks! Will keep it in mind if it comes up more often. 

Looking at your code, assigning props like this (`block.props.creationTime = new Date().toISOString();` is not really supported, you probably want to use `updateBlock` instead. Would be a nice API though!

**Comment by man-shar** [comment]
> Alright thanks! Will keep it in mind if it comes up more often.
> 
> Looking at your code, assigning props like this (`block.props.creationTime = new Date().toISOString();` is not really supported, you probably want to use `updateBlock` instead. Would be a nice API though!

ah yes, that's what I used. then I tried using in a docker but didn't work and filed it here: https://github.com/TypeCellOS/BlockNote/issues/514

Thank you Yusef! Looking at that issue, I realise I never got back to you when you'd asked what I was building:

I work at https://defog.ai/ and we're using blocknote for one of our AI agents products ❤️  Which is why all the dockerization et al haha.
