### ISSUE TITLE
Templates/Section Blocks

### ISSUE THREAD

**Issue by nacho-villanueva** [TypeCellOS/BlockNote#406]
**Is your feature request related to a problem? Please describe.**
I need to build an editor where everything is sorted in sections. Every section needs a heading title and a body which can be anything (paragraph, image, list, etc..)

**Describe the solution you'd like**
A way of creating custom blocks which has a predefined structure of editable items.

**Describe alternatives you've considered**
I've tried using the children, but you can only drag and drop independent items, and not the entire section. 

**Additional context**
![image](https://github.com/TypeCellOS/BlockNote/assets/40722107/de0c8ce9-3e23-4a15-a8f0-643fc34dff3a)

**Comment by matthewlipski** [comment]
This is an interesting use case, but requires pretty significant changes to the underlying BlockNote document structure, which we aren't planning on supporting atm:(. While we're looking into some customization in this area (like having a persistent title), I think this is beyond our scope as a lot of the logic regarding menus & the API would have to be rewritten to work with both the default structure and this one.
