### ISSUE TITLE
Parsing nested bullet points HTML - Blocks

### ISSUE THREAD

**Issue by caioebueno** [TypeCellOS/BlockNote#431]
In my app I am persisting the state of the editor in HTML using the blocksToHTML function. If I parse from blocks to HTML and parse the HTML to blocks later, it looses the nested bullet points and all points become in the same level.

EXP: 
<img width="293" alt="Screenshot 2023-11-30 at 10 25 23 AM" src="https://github.com/TypeCellOS/BlockNote/assets/21995405/229abc99-9eee-4272-aa99-091826698ad7">

This input after parsed results in the following HTML (includes the nested items)

```html
<ul>
  <li>
    <p class="_inlineContent_nstdf_297">Point A</p>
    <ul>
      <li>
        <p class="_inlineContent_nstdf_297">Point A1</p>
      </li>
    </ul>
  </li>
  <li>
    <p class="_inlineContent_nstdf_297">Point B</p>
  </li>
</ul>
<p class="_inlineContent_nstdf_297"></p>
```

After parsing to blocks and using as initial content this is the result

<img width="309" alt="Screenshot 2023-11-30 at 10 28 35 AM" src="https://github.com/TypeCellOS/BlockNote/assets/21995405/e98ec430-0e58-451b-9422-6cbc6f24bac5">

This is the result of parsing blocks to HTML again

```html
<ul>
  <li>
    <p class="_inlineContent_nstdf_297">Point A</p>
  </li>
  <li>
    <p class="_inlineContent_nstdf_297">Point A1</p>
  </li>
  <li>
    <p class="_inlineContent_nstdf_297">Point B</p>
  </li>
</ul>
<p class="_inlineContent_nstdf_297"></p>
```

**Comment by YousefED** [comment]
It's recommended to store JSON to persist your blocks, see also the warning @ https://www.blocknotejs.org/docs/converting-blocks

Nevertheless, this will be fixed by #426
