### ISSUE TITLE
on Nextjs causing 500 in PageSpeed insight and Google Search Console

### ISSUE THREAD

**Issue by eademir** [TypeCellOS/BlockNote#454]
**Describe the bug**
<what's going wrong!?>
Normally server had responded 200 but when try it on page insight and the search console the pages I used BlockNote had returned 500.

**To Reproduce**
<links to a sandbox or clear steps to reproduce are super helpful!>
I just experienced it in production and just fixed it by replacing BlockNote to Interweave and exporting blocks as html. I have only this screenshot.
<img width="917" alt="Screenshot 2023-12-05 at 21 40 18" src="https://github.com/TypeCellOS/BlockNote/assets/36801647/16390e97-d2fa-42f1-b954-56e8bf6f94ec">

**Misc**
- Node version:
- Package manager:
- Browser: 
- [ ] I'm a [sponsor](https://github.com/sponsors/YousefED) and would appreciate if you could look into this sooner than later 💖

**Comment by YousefED** [comment]
Needs better way to reproduce, closing now

**Comment by YousefED** [comment]
Just in case, make sure to follow the nextjs guide: https://www.blocknotejs.org/docs/advanced/nextjs
