### ISSUE TITLE
global CSS error from prosemirror when upgrading to V0.10.0

### ISSUE THREAD

**Issue by Devoagency** [TypeCellOS/BlockNote#455]
**Describe the bug**
<what's going wrong!?>

When upgrading a Next.js application from 		

`"@blocknote/core": "^0.9.6",
"@blocknote/react": "^0.9.6",`

to 

`"@blocknote/core": "^0.10.0",
"@blocknote/react": "^0.10.0"`

I'm getting a global CSS error from prosemirror.

` [0] error - ./node_modules/prosemirror-tables/style/tables.css
[0] Global CSS cannot be imported from within node_modules.
[0] Read more: https://nextjs.org/docs/messages/css-npm
[0] Location: node_modules/@blocknote/react/node_modules/@blocknote/core/dist/blocknote.js
[0]
[0] Import trace for requested module:
[0] ./node_modules/prosemirror-tables/style/tables.css
[0] ./node_modules/@blocknote/react/node_modules/@blocknote/core/dist/blocknote.js
[0] ./node_modules/@blocknote/react/dist/blocknote-react.js`

**To Reproduce**

Follow the installation steps provided [here](https://www.blocknotejs.org/docs/quickstart) with a "next": "^13.1.6" application and try and run the application. 

**Misc**
- Node version:
- Package manager:
- Browser: 
- [ ] I'm a [sponsor](https://github.com/sponsors/YousefED) and would appreciate if you could look into this sooner than later 💖

**Comment by matthewlipski** [comment]
Seems to be fixed when using NextJS 14 - could you try updating and see if you can still reproduce this issue?

**Comment by matthewlipski** [comment]
Also make sure you follow the instructions here: https://www.blocknotejs.org/docs/nextjs

**Comment by Devoagency** [comment]
@matthewlipski I appreciate the response!

My project does not leverage the App router, but upgrading to NextJS 14 alone does not fix the issue.

**Comment by matthewlipski** [comment]
Hey, can you see if the issue is fixed for you in v0.10.1?

**Comment by Devoagency** [comment]
I just tested it and it worked! I appreciate you looking into this so quicky!
