### ISSUE TITLE
Visual bugs caused by editor.updateBlock function after upgrading to V0.10.0

### ISSUE THREAD

**Issue by marsee339** [TypeCellOS/BlockNote#461]
Either advice is needed or it's a bug)

My editor uses a lot of custom blocks and they have properties that need to be updated based on user actions. 

**A simple example is a block with mantine Textarea.**
![chrome_mYn4YCdjBO](https://github.com/TypeCellOS/BlockNote/assets/57190250/ac876626-5f85-4683-9b59-28fd1e3b9110)
As you can see on the gif, on entering each letter there is a visual bug (in this case, the cursor disappears from the block and it must be put there again to continue typing, and so every time. In more complex components, such as mantine RichTextEditor, the text completely disappears and then reappears, In blocks where you can change heights via onMouse events it becomes impossible at all).

This started happening after updating to V0.10.0. The reason, as I understand, is the call editor.updateBlock to update the block property. If this approach can no longer be used, what is the analog? Before V0.10.0 I did updateBlock => onEditorContentChange was called => from there I sent editor.topLevelBlocks to the server. I don't know what to do without editor.updateBlock.... It still works correctly, it just causes too serious bugs in my case(

**To Reproduce**
Full editor code with custom block example
[customBlockExample.txt](https://github.com/TypeCellOS/BlockNote/files/13589630/customBlockExample.txt)

**Comment by matthewlipski** [comment]
This seems like it's likely related to #464 - I tried the example in the provided file with the fix in #466 and am no longer seeing the issue with the cursor leaving the text area. Will be releasing a hotfix this week👍
