### ISSUE TITLE
Component gets remounted whenever block is updated.

### ISSUE THREAD

**Issue by hsingh-ds** [TypeCellOS/BlockNote#464]
**Describe the bug**
In earlier version of blocknote(0.9.6), I added custom blocks that uses internal react state and block props to manage the state component was mounting only on initial editor load which is right. Now, in recent released version(0.10.0) there is a problem with component mounting. Whenever I run editor.updateBlock(block, updatedBlockData), component gets remounted, which is a performance issue because the complete component get remounted instead of updating the affected part of component. It affects the functionality of the current developed plugin and also causes performance issue when more custom blocks are added. 

**To Reproduce**
I added a custom component to show the problem in below code sandbox. 
[CodeSandbox Example](https://codesandbox.io/p/sandbox/elated-borg-nyls7v?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clpulpy3000062v6ayp9s6w3g%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clpulpy2z00022v6a3tisvpi5%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clpulpy2z00032v6a3ghybvmt%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clpulpy2z00052v6avh4u3ndb%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clpulpy2z00022v6a3tisvpi5%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpulpy2y00012v6afs986ci6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clpulpy2z00022v6a3tisvpi5%2522%252C%2522activeTabId%2522%253A%2522clpulpy2y00012v6afs986ci6%2522%257D%252C%2522clpulpy2z00052v6avh4u3ndb%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpulpy2z00042v6antippxkh%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%2522%257D%255D%252C%2522id%2522%253A%2522clpulpy2z00052v6avh4u3ndb%2522%252C%2522activeTabId%2522%253A%2522clpulpy2z00042v6antippxkh%2522%257D%252C%2522clpulpy2z00032v6a3ghybvmt%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clpulpy2z00032v6a3ghybvmt%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)
1. add counter block.
2. try to use increase/decrease buttons.
3. after each change useEffect of the component will run which should only run on first render.

**Comment by debbbbie** [comment]
I has also similar issues when upgrade to 0.10.0

**Comment by YousefED** [comment]
Thanks! We'll fix this asap

**Comment by hsingh-ds** [comment]
@matthewlipski, I am facing the same issue in version 0.13.5.

**Comment by YousefED** [comment]
@matthewlipski can you see if this is still an issue?

**Comment by matthewlipski** [comment]
Everything looks ok to me tbh, I updated the counter code for 0.14.0 and the component only mounts on initial render and when changing the nesting. Updating the counter block's props doesn't trigger re-mounts.

```tsx
import {
  BlockNoteEditor,
  BlockNoteSchema,
  CustomBlockConfig,
  defaultBlockSpecs,
  DefaultInlineContentSchema,
  defaultProps,
  DefaultStyleSchema,
  filterSuggestionItems,
} from "@blocknote/core";
import "@blocknote/core/style.css";
import {
  createReactBlockSpec,
  getDefaultReactSlashMenuItems,
  ReactCustomBlockRenderProps,
  ReactCustomBlockImplementation,
  DefaultReactSuggestionItem,
  SuggestionMenuController,
  useCreateBlockNote,
} from "@blocknote/react";
import { BlockNoteView } from "@blocknote/mantine";
import { useEffect, useMemo } from "react";
import { RiText } from "react-icons/ri";

const counterBlockConfig = {
  type: "counter",
  propSchema: {
    ...defaultProps,
    count: {
      default: 0,
    },
  },
  content: "none",
} satisfies CustomBlockConfig;

const Counter = (
  props: ReactCustomBlockRenderProps<
    typeof counterBlockConfig,
    DefaultInlineContentSchema,
    DefaultStyleSchema
  >
) => {
  const { block, editor } = props;

  console.log({ block });
  const count = useMemo(
    () => (block.props?.count ? block.props?.count : 0),
    [block]
  );
  const onChange = (counterValue: number) => {
    console.log("On update block");
    editor.updateBlock(block, {
      props: {
        count: counterValue,
      },
    });
  };
  useEffect(() => {
    alert("Component mounted.");
  }, []);
  return (
    <div>
      <p>{count}</p>
      <button onClick={() => onChange(count + 1)}>Increase</button>
      <button onClick={() => onChange(count - 1)}>Decrease</button>
    </div>
  );
};

const counterImplementation = {
  render: Counter,
} satisfies ReactCustomBlockImplementation<
  typeof counterBlockConfig,
  DefaultInlineContentSchema,
  DefaultStyleSchema
>;

const counter = createReactBlockSpec(counterBlockConfig, counterImplementation);

const schema = BlockNoteSchema.create({
  blockSpecs: {
    ...defaultBlockSpecs,
    counter,
  },
});

const insertCounter = (
  editor: BlockNoteEditor<
    typeof schema.blockSchema,
    typeof schema.inlineContentSchema,
    typeof schema.styleSchema
  >
) =>
  ({
    title: "Insert Counter",
    onItemClick: () => {
      editor.insertBlocks(
        [
          {
            type: "counter",
          },
        ],
        editor.getTextCursorPosition().block,
        "after"
      );
    },
    aliases: ["c", "counter", "count"],
    group: "Other",
    icon: <RiText />,
  } satisfies DefaultReactSuggestionItem);

const getCustomSlashMenuItems = (
  editor: BlockNoteEditor<
    typeof schema.blockSchema,
    typeof schema.inlineContentSchema,
    typeof schema.styleSchema
  >
): DefaultReactSuggestionItem[] => [
  ...getDefaultReactSlashMenuItems(editor),
  insertCounter(editor),
];

export default function App() {
  const editor = useCreateBlockNote({
    schema,
  });

  return (
    <div>
      <BlockNoteView editor={editor} theme={"light"} slashMenu={false}>
        <SuggestionMenuController
          triggerCharacter={"/"}
          getItems={async (query) =>
            filterSuggestionItems(getCustomSlashMenuItems(editor), query)
          }
        />
      </BlockNoteView>
      <button
        onClick={() => {
          editor.updateBlock(editor.getTextCursorPosition().block, {
            type: "counter",
            props: {
              count: 100,
            },
          });
        }}>
        Update selected block
      </button>
    </div>
  );
}
```

@hsingh-ds Can you try this code and see if it's still broken for you?

**Comment by YousefED** [comment]
Closing, let me know if still an issue
