### ISSUE TITLE
Bug: List items are converted to paragraphs when copying BlockNote content to other editors

### ISSUE THREAD

**Issue by matthewlipski** [TypeCellOS/BlockNote#47]
The way BlockNote represents lists in HTML is by setting the `data-list-type` attribute to each list item. Therefore, list items don't need a parent list the way they normally do in HTML, which uses `ol`/`ul` tags. This non-standard way of representing list items means they are interpreted as paragraphs when copied to other editors, which only recognize that they are `div` elements.

**Comment by YousefED** [comment]
@matthewlipski I'm fairly sure this is fixed right?
