### ISSUE TITLE
InitialBlock ID is 'initialBlockId'.It will replace the initialEditorContent that contains the same id.

### ISSUE THREAD

**Issue by CharlieCho2017** [TypeCellOS/BlockNote#475]
**Describe the bug**
Editor has a InitialBlock  and the id is "initialBlockId". If my initial data has the same block(id is 'initialBlockId'). It will be replace by empty block.

**To Reproduce**
1. Input some text in the Initial block.
2. Put the data as the initial content. 

![image](https://github.com/TypeCellOS/BlockNote/assets/28870006/29fe88f1-4165-48da-8edc-c42faa675cf0)
![image](https://github.com/TypeCellOS/BlockNote/assets/28870006/aa57bf71-8429-4c9b-8112-c502aef46086)
https://codesandbox.io/p/sandbox/block-editor-alert-h5c5nk

**Comment by matthewlipski** [comment]
I don't think this is a big issue - can't you just use a different ID, or do you specifically need to use `initialBlockId`?

**Comment by CharlieCho2017** [comment]
If I don't delete the initial block, I input some text  in it, and save it to the database.  When I open the editor again, the text doesn't display.

**Comment by aargon007** [comment]
I have the same issue!

**Comment by roy-tamnoon** [comment]
Workaround that worked for me
```
    const blocks = editor.topLevelBlocks
      .map((block) => ({
        ...block,
        ...(block.id === 'initialBlockId' && { id: uuidv4() }),
      }));
```

**Comment by YousefED** [comment]
This seems like a critical bug indeed!

It seems to be because `replaceBlocks` does this, which causes the inserted block to be removed:

```
insertBlocks(blocksToInsert, blocksToRemove[0], "before", editor);
removeBlocks(blocksToRemove, editor._tiptapEditor);
```

@matthewlipski a simple fix could be to change this order (and find a fix for the insert position), right?
