### ISSUE TITLE
block edit on useEffect not working

### ISSUE THREAD

**Issue by davidliudev** [TypeCellOS/BlockNote#486]
**Describe the bug**

I have a sample code with a basic editor setup and a basic useEffect hook which tries to insert into the editor:

useEffect(() => {
     editor.insertBlocks(
        [{ content: 'Hello!' }],
        editor.getTextCursorPosition().block,
        'after'
      );
     },[])

However, nothing happens.

When I add setTimeout like this then it works:

  useEffect(() => {
    setTimeout(() => {
      editor.insertBlocks(
        [{ content: "Hello!" }],
        editor.getTextCursorPosition().block,
        "after"
      );
    }, 0);
  }, []);

Is this a bug?

**To Reproduce**
https://codesandbox.io/p/sandbox/charming-rgb-2ghlqq (without setTimeout)
https://codesandbox.io/p/sandbox/friendly-cookies-ljwkk6 (with setTimeout)

I know that for loading initial content there is a property but this is a simplified version for a bigger project and the use case for that is more complicated so it need a hook to do some preprocessing first before sending to the editor. This is not working as intended

**Misc**
- Node version:
- Package manager:
- Browser: 
- [ ] I'm a [sponsor](https://github.com/sponsors/YousefED) and would appreciate if you could look into this sooner than later 💖

**Comment by i-am-chitti** [comment]
@davidliudev, the useEffect runs even before the blocknote editor is ready. Have a look at this snippet - 

```
const editor = useBlockNote({
    domAttributes: {
      editor: {
        class: "editor",
        "data-test": "editor",
      },
    },
    uploadFile: uploadToTmpFilesDotOrg_DEV_ONLY,
    onEditorReady: () => console.log("Editor is ready now"),
  });

  useEffect(() => {
    console.log("From useEffect");
    editor.insertBlocks(
      [{ content: "Hello!" }],
      editor.getTextCursorPosition().block,
      "after"
    );
  }, [editor]);
```

We get this output in console -
```
From useEffect
Editor is ready now
```

As BlockNote editor takes little time to initialize and after it's ready the `onEditorReady` callback is triggerred. But useEffect is synchronous due to which it's triggerred immediately. Since, `editor` isn't ready, the block insertion doesn't work and replaced by what's used to during initialization. 

To avoid this, you can use the `onEditorReady` callback to insert the block. The code is - 

```
const editor = useBlockNote({
    domAttributes: {
      editor: {
        class: "editor",
        "data-test": "editor",
      },
    },
    uploadFile: uploadToTmpFilesDotOrg_DEV_ONLY,
    onEditorReady: (edtior) => {
      editor.insertBlocks(
        [{ content: "Hello!" }],
        editor.getTextCursorPosition().block,
        "after"
      );
    },
  });
```

Also, note that the `onEditorReady` accepts an async function as well. For preprocessing, you can leverage it and pass the resolution further.

**Comment by davidliudev** [comment]
Umm...I see. This behavior is different from other editors. 
The reason I am doing this is that I have a file name string passed in as a prop and I need to load content from disk as the prop changes.

That's why I am putting it in useEffect...

But if the editor is not ready onMount then how to achieve this goal?
Like setting a isEditorReadyRef and then only update when the flag is true?
This may miss a few updates IMO...

**Comment by matthewlipski** [comment]
You shouldn't need to add an `isEditorReadyRef` - you can just check if the editor is ready using `editor.ready`. But yes I would use a `useEffect` hook with the file name prop in the dependency array, and inside the `useEffect` call `editor.insertBlocks` if `editor.ready` is `true`.
