### ISSUE TITLE
Block node attributes are applied to both inner and outer block HTML elements

### ISSUE THREAD

**Issue by matthewlipski** [TypeCellOS/BlockNote#49]
The way that TipTap [Block](https://github.com/YousefED/BlockNote/blob/main/packages/core/src/extensions/Blocks/nodes/Block.ts) nodes are rendered to HTML in the browser is through a `block` element which is wrapped in an `block-outer` element. Node attributes are added to both, which shouldn't be necessary.

Basically, this node:
```
{
  "type": "block",
  "attrs": {
    "headingType": "1"
  },
  "content": [
    {
      "type": "content",
      "attrs": {},
      "content": [
        {
          "type": "text",
          "text": "Heading"
        }
      ]
    }
  ]
}
```
Gets rendered as this HTML:
```
<div data-heading-type="1" class="..." data-node-type="block-outer">
  <div data-heading-type="1" class="..." data-node-type="block">
    <div class="..." data-node-type="block-content">
      <div>
        This is a heading
      </div>
    </div>
  </div>
</div>
```
Notice that the heading type attribute is present in both the `block` and `outer-block` elements. Currently, removing attributes from either causes issues with things like placeholders and styling, but it should be possible to only add attributes to one of the two.

**Comment by YousefED** [comment]
@matthewlipski is this still the case?
