### ISSUE TITLE
Editor Should not Flashing when Dependency Changed and There is no Content Change

### ISSUE THREAD

**Issue by jefrydco** [TypeCellOS/BlockNote#490]
## Current Behavior
Whenever dependency of `useBlockNote` changed from external source, the editor get re-rendered and flashing happen.

## Expected
It shouldn't be flashing

## To Reproduce
https://codesandbox.io/p/sandbox/blocknote-re-render-vhwqrg

## Misc
- Node version: v19.9.0
- Package manager: yarn
- Browser: Chrome 120
- [ ] I'm a [sponsor](https://github.com/sponsors/YousefED) and would appreciate if you could look into this sooner than later 💖

**Comment by YousefED** [comment]
I'm not sure, you do change the content every second. The variable changes to a new array, so I think it follows React patterns to interpret this as a change. We could do a deep comparison, but I'm not sure this is desirable

**Comment by jefrydco** [comment]
@YousefED My use case is I want to do side effect inside of `onEditorContentChange` like changing the status of the document from `Ready` into `Draft` automatically whenever user edit content. In order to do that, we need to know the latest status of the document, that's why we need to add into the `useBlockNote` dependency. The status can also be changed manually by the user.

Here's the updated reproduction link with correct use case:
https://codesandbox.io/p/sandbox/blocknote-re-render-vhwqrg

There is no flashing in there but there are 2 unexpected cases:

1. Editor will lost focus
Try to type something in the editor, editor will lost focus, editor should not lost focus

2. Can't Get Latest Dependency
Try to remove `status` from `useBlockNote` dependency, `onEditorContentChange` will not get the latest value of status.

**Comment by eatmoarrice** [comment]
@jefrydco If you include a variable in a hook's dependency array, the hook will reinitialize whenever that variable changes. This means the editor, including any modals and focus states, would be reset.

A straightforward solution for avoiding this is to use the functional update form of the useState hook:

```
 const editor: BlockNoteEditor = useBlockNote(
    {
      initialContent: content,
      onEditorContentChange(editor) {
        setStatus((prev) => (prev === "Ready" ? "Draft" : prev));
      },
    },
    [content, setStatus]
  );
```

For more complex situations (for example, API calls with conditions), consider using a combination of `useRef` and `useCallback`. This approach allows you to reference the latest state without including it in the dependency array, thus avoiding re-initialization of the hook when the state changes.

**Comment by YousefED** [comment]
I think in this case you can even remove `status` from the deps array completely. This seems to work right? : https://codesandbox.io/p/sandbox/blocknote-re-render-forked-zmrwxz

**Comment by YousefED** [comment]
In the latest release, the callbacks have moved from the hook to the `BlockNoteView` component. I think this would resolve most of the issues in this thread
