### ISSUE TITLE
Partial Block type "image" not available in insertBlocks()

### ISSUE THREAD

**Issue by jung0072** [TypeCellOS/BlockNote#494]
**Describe the bug**
I'm getting the error that it's not possible to use the following block as a blocksToInsert in insertBlocks method. My guess is that insertBlock method is missing image type block as a blocksToInsert.

**To Reproduce**
Code:
   ```
 let imageBlock = [
      {
        type: "image",
        props: {
          url: response.url,
        },
        content: [],
        children: [],
      },
    ];

    editor.insertBlocks(imageBlock, topLvBlocks[0].id, "before");

```
The error message: 
ts(2345) Error: Argument of type '{ type: string; props: { url: any; }; content: never[]; children: never[]; }[]' is not assignable to parameter of type 'PartialBlock<{ readonly paragraph: { node: TipTapNode<"paragraph", true, { domAttributes?: Partial<{ blockContainer: Record<string, string>; blockGroup: Record<string, string>; editor: Record<string, string>; blockContent: Record<...>; inlineContent: Record<...>; }> | undefined; }, any>; propSchema: { ...; }; }; rea...'. Type '{ type: string; props: { url: any; }; content: never[]; children: never[]; }' is not assignable to type 'PartialBlock<{ readonly paragraph: { node: TipTapNode<"paragraph", true, { domAttributes?: Partial<{ blockContainer: Record<string, string>; blockGroup: Record<string, string>; editor: Record<string, string>; blockContent: Record<...>; inlineContent: Record<...>; }> | undefined; }, any>; propSchema: { ...; }; }; rea...'. Type '{ type: string; props: { url: any; }; content: never[]; children: never[]; }' is not assignable to type '(Partial<{ id: string; type: "paragraph"; props: Partial<Props<{ backgroundColor: { default: "default"; }; textColor: { default: "default"; }; textAlignment: { default: "left"; values: readonly ["left", "center", "right", "justify"]; }; }>>; content: string | PartialInlineContent[]; }> & Partial<...>) | (Partial<......'. Type '{ type: string; props: { url: any; }; content: never[]; children: never[]; }' is not assignable to type 'Partial<{ id: string; type: "numberedListItem"; props: Partial<Props<{ backgroundColor: { default: "default"; }; textColor: { default: "default"; }; textAlignment: { default: "left"; values: readonly ["left", "center", "right", "justify"]; }; }>>; content: string | PartialInlineContent[]; }> & Partial<...>'. Type '{ type: string; props: { url: any; }; content: never[]; children: never[]; }' is not assignable to type 'Partial<{ id: string; type: "numberedListItem"; props: Partial<Props<{ backgroundColor: { default: "default"; }; textColor: { default: "default"; }; textAlignment: { default: "left"; values: readonly ["left", "center", "right", "justify"]; }; }>>; content: string | PartialInlineContent[]; }>'. Types of property 'type' are incompatible. Type 'string' is not assignable to type '"numberedListItem"'.

**Comment by jung0072** [comment]
I tried different approach and managed to handle the error

`
   // First approach
   // Type Error on imageBlock 
    let imageBlock = [{ type: "image", props: { url: response.url } }];
    editor.insertBlocks(imageBlock, topLvBlocks[0].id, "before");


   // Second approach    
   // No errors
    editor.insertBlocks(
      [{ type: "image", props: { url: response.url } }],
      topLvBlocks[0].id,
      "before"
    );
`

When I attempt the first approach, an error occurs. Could you provide insight into why this happens? 

I'm eager to help enhance blocknote by addressing this issue if it's a bug. Your explanation would be greatly appreciated. 

Thanks a lot!

**Comment by YousefED** [comment]
My guess is this should work:

`let imageBlock = [{ type: "image", props: { url: response.url } }] as const;`

Or even:

`let imageBlock = [{ type: "image" as const, props: { url: response.url } }];`

The cause is that `type` is interpreted as `string` without the const modifier
