### ISSUE TITLE
Type Error: Generic type 'Block' requires 3 type arguments

### ISSUE THREAD

**Issue by hs-07** [TypeCellOS/BlockNote#497]
**Describe the bug**
Facing error of typescript regarding Block[ ] 

![image](https://github.com/TypeCellOS/BlockNote/assets/87127387/3fcf738f-1848-4d07-a352-33143e1ef82a)

**Misc**
- Node version: latest
- Package manager: npm
- Browser: Google Chrome
- [ ] I'm a [sponsor](https://github.com/sponsors/YousefED) and would appreciate if you could look into this sooner than later 💖

**Comment by frostcraftventuresltd** [comment]
I've just been doing something like below for now until there's an update.

```typescript
const [blocks, setBlocks] = useState<Block<any, any, any>[]>([]);

    const insertHelloWorld = (editor: BlockNoteEditor) => {
        // Block that the text cursor is currently in.
        const currentBlock: Block<any, any, any> = editor.getTextCursorPosition().block;

        // New block we want to insert.
        const helloWorldBlock: PartialBlock<any, any, any> = {
            type: "paragraph",
            content: [{ type: "text", text: "Hello World", styles: { bold: true } }],
        };

        // Inserting the new block after the current one.
        editor.insertBlocks([helloWorldBlock as any], currentBlock, "after");
    };
```
The functionality still works fine just needed to get the error to no throw for me to publish it out to vercel.

Still wrapping my head around this project, hopefully can help contribute in the future as I'm going to heavily use this for other projects too.

**Comment by zcf0508** [comment]
I find a way to resolve this problem, [`ccec336` (#524)](https://github.com/TypeCellOS/BlockNote/pull/524/commits/ccec336373cf69185478d8570f5726b4025edda6)

What's important is that

1. `editor` need infer `blockSpecs` type correctly
2. `helloWorldBlock ` need declaration the type of block, like
```
const helloWorldBlock: PartialBlock<Pick<DefaultBlockSchema, 'paragraph'>, any, any> = {
    type: "paragraph",
    content: [{ type: "text", text: "Hello World", styles: { bold: true } }],
};
```

**Comment by YousefED** [comment]
For people facing this issue, most of this should be fixable removing the type annotation on the variable declaration. E.g. remove `: Block[]` in the original example.

When declaring Blocks, you can use `as const` to help the TS compiler. For example, see https://github.com/TypeCellOS/BlockNote/blob/ed772f12f907364020ad4fd52093f989cf683d12/packages/core/src/api/testUtil/cases/customBlocks.ts#L96

---

Background: BlockNote is designed to be as type-safe as possible, whilst being extensible. So in BlockNote, you can define your custom schema / types for blocks / inlinecontent / styles, and this will be reflected in the Type System. This is done using generics.

Whilst this is really powerful (you get proper code completion and error checking), sometimes it can be a bit cumbersome. The above tips should help!

In the meantime, I'll also look into the suggestions by @zcf0508 and other ways to make this a bit more easier!

**Comment by aressss1** [comment]
hi there, I'm facing a similar issue in PartialBlock. 

here's the issue 
```
Generic type 'PartialBlock' requires 3 type argument(s).ts(2314)
(alias) type PartialBlock<BSchema extends Record<string, BlockConfig>, I extends InlineContentSchema, S extends StyleSchema> = PartialBlocksWithoutChildren<BSchema, I, S>[keyof BSchema] & Partial<{
    children: PartialBlock<BSchema, I, S>[];
}>
``

**Comment by YousefED** [comment]
Hi all! This should be greatly improved with the new version. Lmk if you still run into issues!
