### ISSUE TITLE
`editable: false` deletes the whole content if collaboration is enabled

### ISSUE THREAD

**Issue by sradu** [TypeCellOS/BlockNote#511]
If I start writing a page which is saved via collaboration, and then I open the same page with `editable: false` blocknote deletes the whole content. Reproduced via this nextjs component with the latest version:

```
"use client";
import { BlockNoteEditor } from "@blocknote/core";
import { BlockNoteView, useBlockNote } from "@blocknote/react";
import "@blocknote/react/style.css";

import * as Y from 'yjs'

import { HocuspocusProvider } from '@hocuspocus/provider'

export default function Editor() {
  const ydoc = new Y.Doc()

  const provider = new HocuspocusProvider({
    url: "ws://localhost:1234",
    name: 'page~~c758cb5d-e8ab-425a-a79d-276711e9b572',
    document: ydoc
  })

  const editor = useBlockNote({
    editable: false, // If editable is false it deletes existing content
    collaboration: {
      provider,
      fragment: ydoc.getXmlFragment('document-store'),
      user: {
        name: 'My Username',
        color: '#ff0000'
      }
    },
  });

  return <BlockNoteView editor={editor} />;
}
```

**Comment by sradu** [comment]
@matthewlipski I feel bad saying this, but this bug deletes the whole contents with editable: false and collaboration enabled, perhaps it should be prio:high?

**Comment by YousefED** [comment]
@sradu thanks for reporting, I found the bug

Would be great to welcome you as a sponsor, so we can assign higher priority to items that are critical for you

**Comment by sradu** [comment]
@YousefED I know! I want that too, as soon as you know....
