### ISSUE TITLE
No ability to style links in 0.11.0

### ISSUE THREAD

**Issue by marsee339** [TypeCellOS/BlockNote#512]
Maybe I just couldn't find a way to solve it, but right now I'm struggling with several problems:

1) In version 0.11.0 the approach to styling has changed. And now componentStyles cannot be used to set colors. But how to style links? I don't see a CSS Variables for this, but before I could do it like this:
```
componentStyles: (theme) => ({
  Editor: {
    a: {
      color: defaultLinkColor,
      cursor: "pointer"
    },
    'a:hover': {
      color: defaultLinkColor
    },
    'a:visited': {
      color: defaultLinkColor
    }
}
```

2) It would also be great to be able to set a custom class for dragHandleMenu in domAttributes (https://www.blocknotejs.org/docs/theming#adding-dom-attributes), now it's not there, and I have to use the default (which can change unexpectedly)

**Comment by matthewlipski** [comment]
You can now just create CSS rules using various classes that BlockNote sets on DOM elements (these always start with `bn-`).  There are too many to really list so it's better to inspect the DOM when meking more complex rules, but to set styles on links in the editor, you can just do this:

```css
/* CSS */
.bn-editor a {
  ...
}

.bn-editor a:hover {
  ...
}

.bn-editor a:visited {
  ...
}
```

As for the drag handle menu, you should be able to use the `.bn-drag-handle-menu` selector to style it. Could you elaborate on the changing unexpectedly thing btw? Haven't encountered that before but might just be a bug.

**Comment by marsee339** [comment]
Thanks, I'll make a binding to classes then. And about drag handle menu, before its class was called `mantine-DragHandleMenu-root `and I used to bind to it, but after the update it became `bn-drag-handle-menu`, I didn't find it right away and had to find out the reason for the change in the styles
