### ISSUE TITLE
Hyperlink highlighting.

### ISSUE THREAD

**Issue by hsingh-ds** [TypeCellOS/BlockNote#532]
**Is your feature request related to a problem? Please describe.**
When a user adds a hyperlink, there is no highlighting to indicate that the word is a hyperlink.

**Describe the solution you'd like**
Proper highlighting, such as underscore or background color, should be applied to indicate that the word is a hyperlink.

**Comment by matthewlipski** [comment]
I think this is just a bug in the demo on the documentation page, seems like hyperlink styles are applied properly otherwise (e.g. docs sandboxes, prod environment, etc)

**Comment by YousefED** [comment]
fixed, this was an issue because tailwind removed the default links styles
