### ISSUE TITLE
VUE3 Support

### ISSUE THREAD

**Issue by makakken** [TypeCellOS/BlockNote#542]
I'm always frustrated when i search for block-editors in the vue3 sphere. it seems there is not a good one. i always end up using tiptap, but without a nice block functionality.

as a vue enthusiast, i would really like to have a block-based editor with an nice extensible API with VUE3 compatiblity.

**Comment by YousefED** [comment]
At this moment, we consider it out-of-scope.

This guide could be a good entry point to implement this: https://www.blocknotejs.org/docs/vanilla-js

We'd also be open for a sponsorship to deliver this feature, but at this moment we're focusing on improving the react editor
