### ISSUE TITLE
Another Example to Add Custom UI Block in React [ without TypeScript ] 

### ISSUE THREAD

**Issue by happycoder0011** [TypeCellOS/BlockNote#543]
**Describe the Contribution**
I wanted to contribute by adding another example to add a custom UI component in the slashMenu and block.

The sample block will be an Accordion. Currently, we just have one sample example (Alert). I am open to any other sample block implementation also.
It would be great I think to add more for users to refer from.

**Comment by matthewlipski** [comment]
Definitely! Though you might struggle with implementing an accordion if you want it to be editable, as custom blocks currently only support one editable field. If the accordion is non-editable though (and the data is passed via props), I think it would make a good example. Alternatively you could do an editable spoiler block, which is basically an accordion with one item.

**Comment by YousefED** [comment]
Docs have been updated significantly, hopefully this helps! 

We'd love to see community examples as well, see https://blocknotejs.org/examples/
