### ISSUE TITLE
How to add delete image options on image?

### ISSUE THREAD

**Issue by sundargautam18** [TypeCellOS/BlockNote#544]
When i successfully uploaded image using uploadFile, how can I implement the delete functionalities of image ?

I mean deleting images not only from blog but from server too

**Comment by DavidIlie** [comment]
Looking for a solution to this as well!

**Comment by ekangash** [comment]
Personally, at the moment I serialize all links into one collection and before updating the data in the database, compare it with the reference old value, delete the difference. Use it, so far at the moment this is the only way in my opinion

**Comment by YousefED** [comment]
At this moment, we don't have built-in support for this. I'm not sure it's something that can be easily implemented on the client:
- What if a user deletes an image, but then hits ctrl+z (undo)?
- What if the image is reused in other locations / documents?

There are probably ways to work around this, but I think the safest is to implement this server-side indeed.
