### ISSUE TITLE
Spinner showing in all icons

### ISSUE THREAD

**Issue by odufuwa-segun** [TypeCellOS/BlockNote#549]
**Describe the bug**
<what's going wrong!?>
Spinner icon is showing up beside all icon buttons, see image below:
<img width="1680" alt="Screenshot 2024-01-27 at 6 19 26 PM" src="https://github.com/TypeCellOS/BlockNote/assets/17216576/90c5a246-cc06-4b4e-a4a1-716989f77f50">

<img width="1680" alt="Screenshot 2024-01-27 at 6 19 32 PM" src="https://github.com/TypeCellOS/BlockNote/assets/17216576/e911dc1b-6958-4ba3-a1a4-13222ad28c62">

Environment: Nextjs

Edit:
I added a CSS style to the editor to hide the spinner, the icon buttons render correctly now. I do hope this isn't masking an issue.
.mantine-ActionIcon-loader {display: none}

**To Reproduce**
I followed the quick start instructions in https://www.blocknotejs.org/docs/quickstart

**Misc**
- Node version: 18.18.0
- Package manager: npm vs 9.8.1
- Browser: Chrome, Firefox
- [ ] I'm a [sponsor](https://github.com/sponsors/YousefED) and would appreciate if you could look into this sooner than later 💖

**Comment by odufuwa-segun** [comment]
Code:

`"use client";
import {BlockNoteEditor} from "@blocknote/core";
import {BlockNoteView, useBlockNote} from "@blocknote/react";
import "@blocknote/react/style.css";

export const Document = () => {
    const editor: BlockNoteEditor = useBlockNote({});

    // Renders the editor instance using a React component.
    return <div className="w-full h-full p-2 py-4 overflow-hidden"><BlockNoteView editor={editor}/></div>
}`

**Comment by hgogoi2012** [comment]
Has the problem been resolved? I am also experiencing the same issue.

**Comment by leighton-tidwell** [comment]
I am experiencing this issue as well

**Comment by matthewlipski** [comment]
This was kind of a pain to diagnose, but bottom line is that it should be fixed by updating Mantine from 7.4.2 to 7.5.0. I'm not sure exactly what's causing the issue, but there seem to be styles missing in `@mantine/core/styles.css` for the `.m-302b9fb1` selector that's used in the loader in 7.4.2. Using 7.5.0 and disabling these additional styles causes icons to have the loader visible next to them as in the screenshot.
