### ISSUE TITLE
Bubble menu button hints not disappearing after pressing arrow key

### ISSUE THREAD

**Issue by matthewlipski** [TypeCellOS/BlockNote#55]
The button hints that show what bubble menu buttons do currently do not disappear properly after pressing an arrow key. If the bubble menu is open, navigating with the arrow keys closes the bubble menu as intended (since the selection becomes empty), but any hints that were open at the time don't disappear, and instead move to the top-left of the viewport.
![ezgif-3-2ef98cf42d](https://user-images.githubusercontent.com/50169049/198343572-0e704883-1b6e-4d82-b01a-a0c41c37504f.gif)

**Comment by YousefED** [comment]
I couldn't reproduce this anymore
