### ISSUE TITLE
Cannot update a component (`to2`)

### ISSUE THREAD

**Issue by mawnir** [TypeCellOS/BlockNote#552]
**Describe the bug**
Warning: Cannot update a component (`to2`) while rendering a different component (`Editor`). To locate the bad setState() call inside `Editor`

**To Reproduce**
I don't know the name, but adding `[initialContent]` to `useBlockNote` hook trigger the error
```
const editor: BlockNoteEditor = useBlockNote({
        initialContent:
            initialContent
                ? JSON.parse(initialContent) //as PartialBlock[]
                : undefined,
        ...
    }, [initialContent]);
```

**Misc**
- Node version: v20.10.0
- Package manager: pnpm
- Browser: Firefox

**Comment by matthewlipski** [comment]
If I understand correctly, you put `initialContent` in the deps array to set the editor content whenever `initialContent` changes. However, you should instead use an effect hook to reset the editor content:

```jsx
useEffect(() => {
  editor.replaceBlocks(editor.topLevelBlocks, initialContent)
}, [editor, initialContent]);
```

**Comment by mawnir** [comment]
@matthewlipski i couldn't make to work with typescript : 
`Argument of type 'string | undefined' is not assignable to parameter of type 'PartialBlock<BlockSchemaFromSpec...`

**Comment by matthewlipski** [comment]
Ah ok the problem is more clear then - you should use an array of `Block` objects for `initialContent` instead of a string
