### ISSUE TITLE
Customized SlashMenuItems are not selected correctly when selected with the keyboard

### ISSUE THREAD

**Issue by hyuckkim** [TypeCellOS/BlockNote#554]
**Describe the bug**
My team made two custom blocks and insert to slash menu.

```typescript
slashMenuItems: [
      ...getDefaultReactSlashMenuItems(),
      insertCheckBoxBlock,
      insertChartBlock,
    ],
```
insertCheckBoxBlock's group is "Work", and insertChartBlock's group is "Media".
like that: 
![image](https://github.com/TypeCellOS/BlockNote/assets/53367179/59fd1bd3-c5c7-4d7f-857e-1c1b653ccde9)

As long as I selected everything with the mouse, there was no problems, but with keyboard, it insert incorrect thing.

I can work around this temporarily by matching the values in your code to the visible values.
like this: 
```typescript
slashMenuItems: [
      ...getDefaultReactSlashMenuItems(),
      insertChartBlock,
      insertCheckBoxBlock,
    ],
```
However, I am reporting this because it seems clear that this was not intended.

**To Reproduce**
1. Make some SlashMenuItem. Group must be "Headings".
like that:
```typescript
export const testBlock: ReactSlashMenuItem<
  BlockSchemaWithBlock<"test", typeof CheckBoxBlockSpec.config>
> = {
  name: "test",
  execute: () => {},
  group: "Headings",
  icon: <div />,
}
```
2. Insert the Item to slashMenutems.
like that:
```typescript
    slashMenuItems: [
      ...getDefaultReactSlashMenuItems(),
      testBlock,
    ],
```
3. Move to browser editor and add some 'basic blocks' by slash menu with 'keyboard'.
![pp](https://github.com/TypeCellOS/BlockNote/assets/53367179/1af3a9d9-c382-4936-8dba-d002f66dc170)

**Misc**
- Node version: v21.5.0
- Package manager: npm 10.2.4
- Browser: edge 121.0.2277.83, but I seems it is not important.
- [ ] I'm a [sponsor](https://github.com/sponsors/YousefED) and would appreciate if you could look into this sooner than later 💖

**Comment by matthewlipski** [comment]
Yep, the slash menu item ordering is indeed a bit wonky atm. We're going through a major overhaul of how the slash menu works to make it easier to add your own suggestion menus like mentions, so we're planning to fix issues like this there (#534 ).
