### ISSUE TITLE
"ListItem" is hardcoded.

### ISSUE THREAD

**Issue by hyuckkim** [TypeCellOS/BlockNote#558]
https://github.com/TypeCellOS/BlockNote/blob/6ce6e57efa32372522dcf334691ed1dfa0e5ec4a/packages/core/src/blocks/ListItemBlockContent/ListItemKeyboardShortcuts.ts#L13

I cannot how it works, but It works in custom block also.
I changed my custom block's type to JohnDoeListItem and use their feature.

I think it need to allow modification to boolean values in blockspec.

**Comment by matthewlipski** [comment]
Good point, didn't consider custom list item blocks which maybe shouldn't have the same behaviour as the default ones, will fix to only use the shortcut for `BulletListItem` and `NumberedListItem`.
