### ISSUE TITLE
Invalid initial content setting

### ISSUE THREAD

**Issue by lujdong** [TypeCellOS/BlockNote#559]
**Describe the bug**
<what's going wrong!?>
The initial value is not displayed correctly when using setState to set the initial value in useEffect
**To Reproduce**
<links to a sandbox or clear steps to reproduce are super helpful!>
https://codesandbox.io/p/devbox/cocky-rain-v26nqd?file=%2Fsrc%2FApp.tsx
**Misc**
- Node version: v20.10.0
- Package manager: pnpm 
- Browser: Chrome/121.0.6167.140
- [ ] I'm a [sponsor](https://github.com/sponsors/YousefED) and would appreciate if you could look into this sooner than later 💖

**Comment by matthewlipski** [comment]
Ah, you should wait for the editor to be ready before setting the initial React state:
```tsx
function App() {
  const [initialContent, setInitialContent] = useState<any>();

  const [data, setData] = useState<{
    content: string;
  }>({
    content: "",
  });

  useEffect(() => {
    if (data.content) {
      setInitialContent(data.content);
      const getBlocks = async () => {
        const blocks = await editor.tryParseHTMLToBlocks(data.content);
        // Normal printing results.
        console.log(blocks);
        setInitialContent(blocks);
      };
      getBlocks();
    }
  }, [data]);

  // Creates a new editor instance.
  const editor: BlockNoteEditor = useBlockNote({
    initialContent,
    onEditorReady: (editor) => {
        setData({ content: "<p>hello</p>" });
    }
  });

  // Renders the editor instance using a React component.
  return <BlockNoteView editor={editor} />;
}
```

**Comment by lujdong** [comment]
Cool, this solved my problem

**Comment by YousefED** [comment]
On v0.12 this should now
