### ISSUE TITLE
The toolbar style is incorrect.

### ISSUE THREAD

**Issue by lujdong** [TypeCellOS/BlockNote#563]
As shown in the picture, the layout is shifted and some buttons have loading icons.

I tried to remove all styles except for Blocknote and only leave <BlockNoteView editor={editor} />, but the result is still the same. Please see the image. Can someone tell me why?

​
![20240206151420](https://github.com/TypeCellOS/BlockNote/assets/39292981/015d5667-7e4d-4b28-8a44-5969f00bb062)
![20240206151441](https://github.com/TypeCellOS/BlockNote/assets/39292981/dffd4cb0-1299-48c7-a03b-f9e05b9e1ab0)

**Comment by matthewlipski** [comment]
Are you on 0.11.2? Should be fixed in the newest version

**Comment by lujdong** [comment]
My mistake, I'm still using v0.11.1 but it's fixed in v0.11.2
