### ISSUE TITLE
After removing a pasted link, and then editing the text (adding a space), it goes back to being a link.

### ISSUE THREAD

**Issue by troglodytto** [TypeCellOS/BlockNote#574]
**Describe the bug**
After removing a **pasted** link, and then editing the text (adding a space), it goes back to being a link.

https://github.com/TypeCellOS/BlockNote/assets/68903933/dcf0917c-b9e5-48b0-a32e-d83614adfc1f

**To Reproduce**
[Code Sandbox](https://codesandbox.io/p/sandbox/clever-tesla-7d3shp)
```javascript
import { useBlockNote, BlockNoteView } from "@blocknote/react";
import "@blocknote/react/style.css";

export default function App() {
  const editor = useBlockNote();

  return <BlockNoteView editor={editor} />;
}
```

1. Paste any link in the editor
2. Move cursor to the link and click "Remove Link"
3. Press the Space Key
4. The pasted content becomes a link again

**Possible Reason**
When pasting content, BlockNote detects whether the pasted content is a link or not, and converts a text node to a link node automatically. Perhaps this is happening for content (resembling a link) that already exists in the editor.

This line prevents the node from becoming a link again (as far as I can understand it), but it seems that it is not working as expected.

```javascript
// @blocknote/core/src/extensions/HyperlinkToolbar:175
.setMeta("preventAutolink", true)
```

**Misc**
- Node version: 18.8.2
- Package manager: pnpm@8.14.0
- Browser: Brave
- [ ] I'm a [sponsor](https://github.com/sponsors/YousefED) and would appreciate if you could look into this sooner than later 💖

**Comment by YousefED** [comment]
This happens because hitting space will detect for links. It's a bit confusing if you just removed the link, I agree, but I also don't see an easy fix

It seems Notion has the same behavior, so for now I'll mark this as closed
