### ISSUE TITLE
Open access to custom block's underlying component reference

### ISSUE THREAD

**Issue by khash** [TypeCellOS/BlockNote#578]
**Is your feature request related to a problem? Please describe.**
If you create a custom block that is not `inline` there is no way to access its `ref`. This is useful when you want to interact with the custom block's component via the side or slash menu.

**Describe the solution you'd like**
Add the ref to the parameters returned by the block schema.

**Describe alternatives you've considered**
Nothing I can think of now.

**Comment by YousefED** [comment]
Hi @khash ,

Could you explain more about what you're trying to achieve (more from a UX perspective)?

Or technically, what do you want to do with the ref?

**Comment by khash** [comment]
Sure @YousefED 

So imagine the following scenario: I have a custom block that is rendered by a component I have in the app. This component has a function on it that I can call to change something in the component. For example, if my component is showing stock prices with some charts, I can call that `refresh` method to fetch the new prices. Now normally I'd get hold of the `ref` on my component and call the method on that ref. 

If I want to do the same, but via the Side menu (by adding a "Refresh" menu item in the side menu for example), I'd need to access the `ref` of the block in the custom side menu handler. I can't find a way to get hold of such ref.

**Comment by YousefED** [comment]
Thanks, that scenario makes sense. At this moment it's not supported - if we see more requests for this it would be interesting to explore further. I think it would be possible to workaround this by using a Context instead, and listen to a "refresh" event on the context for example.

Out of curiosity, what are you building? (would love to learn more how people are using BlockNote)
