### ISSUE TITLE
Custom Component For Slash Menu Styling

### ISSUE THREAD

**Issue by natti-tamnoon** [TypeCellOS/BlockNote#582]
**Is your feature request related to a problem? Please describe.**
Reviewing the documentation I see the ability to modify the order and groupings of the slash menu items, but I want to customize the styling of the Slash menu itself.

For example, be able to add vertical line separators between the grouped sections, and change the styling of the icons to remove the grey background.

Perhaps this is already possible, but I couldn't figure this out from the documentation.

**Describe the solution you'd like**
Requesting way to uniformly style the menu. If this feature exists, requesting a simple documentation example.

Thanks!

**Comment by YousefED** [comment]
See https://www.blocknotejs.org/docs/ui-components/suggestion-menus for the
new docs :)
