### ISSUE TITLE
BlockNote Discord link is invalid

### ISSUE THREAD

**Issue by kennyjwilli** [TypeCellOS/BlockNote#586]
**Describe the bug**

The Discord link on the [BlockNote website](https://www.blocknotejs.org/) takes you to https://discord.com/invite/Qc2QTTH5dF, which Discord states is an invalid invite. 
<img width="492" alt="Screenshot 2024-02-17 at 12 52 09 PM" src="https://github.com/TypeCellOS/BlockNote/assets/2453976/a6566618-68c3-432d-a20e-6ddb1abd2314">

**To Reproduce**

1. Navigate to https://www.blocknotejs.org/
2. Click the Discord link in the top right. <img width="586" alt="Screenshot 2024-02-17 at 12 52 45 PM" src="https://github.com/TypeCellOS/BlockNote/assets/2453976/3a1810e8-ae5c-4f33-85ac-704250c0be07">
3. Observe Invalid Invite on discord.com.

**Comment by YousefED** [comment]
Interesting, it seems to work well here. Maybe there was a temporary issue with discord?

@kennyjwilli is that link still broken for you?

**Comment by kennyjwilli** [comment]
@YousefED Oddly seems to be some sort of browser cookie issue. Trying again in an incognito tab seems to work. Thanks.
