### ISSUE TITLE
Option to disable toolbar to nest blocks

### ISSUE THREAD

**Issue by natti-tamnoon** [TypeCellOS/BlockNote#589]
**Is your feature request related to a problem? Please describe.**
If developing logic that depends on certain blocks being only at the top level, need a way to prevent users from nesting.

**Describe the solution you'd like**
would like option to disable / remove the indent button over target existing block types
![image](https://github.com/TypeCellOS/BlockNote/assets/145366118/c4297428-dd6a-4d4f-9683-283933bc1dd9)

**Describe alternatives you've considered**
- Guards can be put in place with DFS searching through blocks to add validations, but very preferable to also block option completely from UI

**Comment by YousefED** [comment]
Would customizing the formatting toolbar help? See https://www.blocknotejs.org/docs/ui-components/formatting-toolbar or https://www.blocknotejs.org/examples/ui-components/formatting-toolbar-buttons

**Comment by natti-tamnoon** [comment]
Hi 

> Would customizing the formatting toolbar help? See https://www.blocknotejs.org/docs/ui-components/formatting-toolbar or https://www.blocknotejs.org/examples/ui-components/formatting-toolbar-buttons

Hi Yousef, thanks for info. That is close to what we need. The only thing is I don't want to remove nesting for all blocks, we want to keep it for standard text blocks. Just disable nesting on specific blocks (like images or other custom blocks).

Is there a prop that can be passed to the toolbar whereby conditional logic can be added based on the type of block?

Either hiding or disabling the nesting for certain blocks would work. I noticed for example the nesting is disabled when highlighting part of a line. Is this in the public api of the toolbar?
![image](https://github.com/TypeCellOS/BlockNote/assets/145366118/e5a2b3c6-1515-4c5e-a640-24ffdce8b372)

**Comment by YousefED** [comment]
Hi!

Have a look at the source code here: https://github.com/TypeCellOS/BlockNote/blob/8c22f79ec3b3897f8f78d25acc3e747ddb4b878c/packages/react/src/components/FormattingToolbar/mantine/DefaultButtons/NestBlockButtons.tsx#L26.

You could create your own buttons, that add some more custom logic (like what block type the selection is in) to achieve your goal.

On a schema level, at the moment it's not supported to define which blocks can / cannot have children (that would theoretically be the ideal solution).
