### ISSUE TITLE
Custom block inserted into HTML cannot be edited

### ISSUE THREAD

**Issue by lujdong** [TypeCellOS/BlockNote#595]
After creating a custom block and setting the `dangerouslySetInnerHTML` attribute, the inserted content cannot be edited

[code example](https://codesandbox.io/p/devbox/s5ls74?migrateFrom=gytq6q&embed=1&file=%2Fsrc%2FApp.tsx&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clt2cloq60006356lijup7clh%2522%252C%2522sizes%2522%253A%255B69.47437582%252C30.525624179999994%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clt2cloq50002356l7kaecnf3%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clt2cloq50004356l0ra80x5w%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clt2cloq60005356lf9sot0pt%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clt2cloq50002356l7kaecnf3%2522%253A%257B%2522id%2522%253A%2522clt2cloq50002356l7kaecnf3%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clt2cloq60005356lf9sot0pt%2522%253A%257B%2522id%2522%253A%2522clt2cloq60005356lf9sot0pt%2522%252C%2522activeTabId%2522%253A%2522clt2h8m3r017u356lbzjbrfia%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A5173%252C%2522taskId%2522%253A%2522Development%2522%252C%2522id%2522%253A%2522clt2gzq3e00hj356lab8zjujc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522SANDBOX_INFO%2522%252C%2522id%2522%253A%2522clt2h8m3r017u356lbzjbrfia%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clt2cloq50004356l0ra80x5w%2522%253A%257B%2522id%2522%253A%2522clt2cloq50004356l0ra80x5w%2522%252C%2522activeTabId%2522%253A%2522clt2cmgsm00ch356lmeqrpcll%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clt2cloq50003356lb0jlncjy%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clt2clmji000sdkf8cxar1y1b%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522Development%2522%252C%2522id%2522%253A%2522clt2clwvx0086356l2wfk5cm1%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522id%2522%253A%2522clt2cmgsm00ch356lmeqrpcll%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clt2cmdx60017dkf8cnsrcacs%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522clt2h6rnl00x4356lzm06ls1e%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

code like this:

```
import { BlockNoteView, useBlockNote, createReactBlockSpec } from "@blocknote/react";
import { defaultProps,defaultBlockSpecs } from '@blocknote/core';
import "@blocknote/react/style.css";

export default function App() {

  const DesignBlock = createReactBlockSpec(
    {
      type: 'design',
      propSchema: {
        ...defaultProps,
        html: {
          default: ''
        }
      },
      content: 'inline'
    },
    {
      render: ({ block, contentRef }) => {
        return (
          <section ref={contentRef} dangerouslySetInnerHTML={{ __html: block.props.html }}></section>
        );
      }
    }
  );
  
  const editor = useBlockNote({
    blockSpecs: {
      ...defaultBlockSpecs,
      design: DesignBlock
    },
  });

  const str = `
      <section style="width: 200px;height: 200px;border: 1px solid red">hello</section>
    `;

  return (
    <div>
      <button onClick={()=>{
        editor.insertBlocks(
          [{ type: 'design', props: { html: str } }],
          editor.getTextCursorPosition().block.id
        );
      }}>Insert HTML</button>
      <BlockNoteView className="root" editor={editor} />
    </div>
  );
}

```

**Comment by tcper** [comment]
When you use a custom block, all content in block is controlled by your code.
Just use changed like this, it will be like what you what
```
const str = `
      <section style="width: 200px;height: 200px;border: 1px solid red"><textarea>hello</textarea></section>
    `;
```

**Comment by YousefED** [comment]
I don't think this is a supported usecase. The content is controlled by blocknote (`contentRef`). You can't also set the innerHTML manually
