### ISSUE TITLE
Self XSS vulnerability in editor

### ISSUE THREAD

**Issue by FlyInk13** [TypeCellOS/BlockNote#601]
**Describe the bug**
There is a self xss vulnerability in the editor

**To Reproduce**
1) Open url: ```data:text/html,<body contenteditable>test1<img src=1 onerror=alert() />test2```
2) Select all content and copy
3) Paste in editor https://www.blocknotejs.org/

**Comment by YousefED** [comment]
Thanks for reporting, will be fixed in next release (https://github.com/TypeCellOS/BlockNote/pull/562/commits/fd3fa3df7b9eb44e7ab182d6d31d17714c5296d0)
