### ISSUE TITLE
Can I write multiline code block?

### ISSUE THREAD

**Issue by NaotoCoding** [TypeCellOS/BlockNote#615]
I found I can write inline code block on BlockNote.
I think it is amazing feature, thanks!
Can I write multiline code block on BlockNote?
Please see the attached video for details.

https://github.com/TypeCellOS/BlockNote/assets/65155272/8f9bbb43-0e81-4d19-97f6-a5d3a14ef033

**Comment by hsingh-ds** [comment]
@NaotoCoding try Shift+Enter in the block in which you want to add multiple lines then type. It will append the text in the same block.

**Comment by NaotoCoding** [comment]
@hsingh-ds 
Thank you! I get it!
