### ISSUE TITLE
Encouraging usage of useMemo in docs for themes object

### ISSUE THREAD

**Issue by jagjit-1** [TypeCellOS/BlockNote#630]
The docs under https://www.blocknotejs.org/docs/styling-theming/themes, show the usage of setting custom redTheme by creating lightRedTheme and darkRedTheme objects.

Without the usage of useMemo, new theme objects are created on every render which is pretty harmless on itself but when combined with other functionality can create unexpected behaviour

For example:
If useState is used to store the current blocks by attaching onChange on BlockNoteView as following
`const [blocks, setBlocks] = useState([]);`
`return (`
`<BlockNoteView
      editor={editor}`
      `onChange={() => setBlocks(editor.document)}`
      `theme={{
        light: lightRedTheme,
        dark: darkRedTheme,
      }}
    />`
`)`

This will result in editor loosing focus on every render.

**Comment by YousefED** [comment]
Thanks!

Opted to extract the variable, fixed here https://github.com/TypeCellOS/BlockNote/commit/e3520ed65d28ed58194d68adf8824a1770e71b95
