### ISSUE TITLE
Cannot read properties of undefined (reading 'dispatch')

### ISSUE THREAD

**Issue by hsingh-ds** [TypeCellOS/BlockNote#633]
**Describe the bug**
I am trying to use replaceBlocks function after initializing the editor. But it is giving an error "Cannot read properties of undefined (reading 'dispatch')"

**To Reproduce**
I have added the link of codesandox: [Link to sandbox](https://codesandbox.io/p/devbox/g9g5rs?migrateFrom=mmq3t5&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltm28yok00062v6bdta7l1rv%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltm28yoj00022v6bp7snprwc%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltm28yoj00042v6b5op5bf36%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltm28yoj00052v6byt9xc1x3%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltm28yoj00022v6bp7snprwc%2522%253A%257B%2522id%2522%253A%2522cltm28yoj00022v6bp7snprwc%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522cltm28yoj00052v6byt9xc1x3%2522%253A%257B%2522id%2522%253A%2522cltm28yoj00052v6byt9xc1x3%2522%252C%2522activeTabId%2522%253A%2522cltm29acd00a32v6b5jaeeqqw%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522Development%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522cltm29acd00a32v6b5jaeeqqw%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522cltm28yoj00042v6b5op5bf36%2522%253A%257B%2522id%2522%253A%2522cltm28yoj00042v6b5op5bf36%2522%252C%2522activeTabId%2522%253A%2522cltm28yoj00032v6bz9tuhyqr%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltm28yoj00032v6bz9tuhyqr%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cltm28zxp000hdcf89b3l5kst%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522Development%2522%252C%2522id%2522%253A%2522cltm297ly008h2v6b0g72u8j1%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by tolypash** [comment]
@YousefED I want to replace all blocks with new ones, so I need a way to control the data

Replace blocks doesnt seem to work

**Comment by rickyhonline** [comment]
Having same issues, any update on this? @YousefED  regarding your comment, I can't use initial content because I need to first convert markdown to blocks using editor.tryParseMarkdownToBlocks so I need my editor initialized first correct?

**Comment by zaaakher** [comment]
I'm also having the same problem and it's coming specifically from `editor.replaceBlocks()`

Here's a sample:

```tsx
  useEffect(() => {
    async function loadInitialHTML() {
      const blocks = await noteEditor.tryParseMarkdownToBlocks(
        "This is a normal text\n\n# And this is a large heading",
      );
      noteEditor.replaceBlocks(noteEditor.document, blocks);
    }
    loadInitialHTML();
  }, [isLoading]);
```

**Comment by YousefED** [comment]
closed by https://github.com/TypeCellOS/BlockNote/pull/909
