### ISSUE TITLE
List placeholder shows on top of pasted custom inline element

### ISSUE THREAD

**Issue by lucasavila00** [TypeCellOS/BlockNote#643]
**Describe the bug**
![image](https://github.com/TypeCellOS/BlockNote/assets/12750442/9b887f9b-ba4c-47b6-a1f7-0c161bfdd14d)

See that there's a gray "List" over Steve in this example

**To Reproduce**

https://www.blocknotejs.org/examples/custom-schema/suggestion-menus-mentions

- Create a list
- Add a mention
- Copy that mention and paste it

**Comment by YousefED** [comment]
Thanks! We'll look into this
