### ISSUE TITLE
Slash menu scrolls the page to top when triggered first time after loading document.

### ISSUE THREAD

**Issue by hsingh-ds** [TypeCellOS/BlockNote#656]
**Describe the bug**
Slash menu affecting scroll behaviour.

**To Reproduce**
Here is link of sandbox: [Link](https://stackblitz.com/edit/github-gvznsy?file=App.tsx). Try it on Firefox/chrome as sandbox is not working correctly on Safari.
1. Go to the given link.
2. wait until editor loads.
3. scroll to bottom of the document.
4. press slash(/) to trigger the slash menu.
5. Page will scroll to the top and user needs to scroll down to select the slash menu item.

**Misc**
I am using the latest version of blocknote.

**Comment by shyamtawli** [comment]
How to solve this I am also facing the same, Where ever I type slash the menu open and page scroll to top?
