### ISSUE TITLE
video embedding feature

### ISSUE THREAD

**Issue by ulisesAcosta27** [TypeCellOS/BlockNote#672]
I think this is one of the libraries that more come to look like notion along with the power that has the text editor of it, but I would like to know if in the future (hopefully in the near future) you can add the feature of embedding video, for example youtube video.

I don't know if it can be of help, but looking for other code editors I found a project of a guy called [yopta-editor](https://github.com/Darginec05/Yoopta-Editor) that does just that action, but I repeat I hope that someday you can add this feature to your library :))

**Comment by YousefED** [comment]
Yes, we plan on adding this, but you could probably also achieve this with custom blocks: https://www.blocknotejs.org/docs/custom-schemas

**Comment by VipinKumar1310** [comment]
I am not able to find the proper schema for adding more options to heading section, I want to add heading 4,5 and 6 also. Can you share how can I add more options to heading by custom blocks and is there any way to add the fontsize dropdown in the inline toolbar

**Comment by Pariola-droid** [comment]
@YousefED Hi, i've got a similar issue/question, if i create a custom block for type `image`, would it be possible to still use the upload handler

 ```
async function uploadFile(file: File) {
    const body = new FormData();
    body.append('file', file);

    const ret = await fetch('https://tmpfiles.org/api/v1/upload', {
      method: 'POST',
      body: body,
    });
    return (await ret.json()).data.url.replace(
      'tmpfiles.org/',
      'tmpfiles.org/dl/'
    );
  }

  const editor = useCreateBlockNote({
    schema,
    uploadFile,
  });

```

Thanks

**Comment by 0x213F** [comment]
This feature is now live on `0.13.4` 🎉

**Comment by matthewlipski** [comment]
> I am not able to find the proper schema for adding more options to heading section, I want to add heading 4,5 and 6 also. Can you share how can I add more options to heading by custom blocks and is there any way to add the fontsize dropdown in the inline toolbar

This is way more difficult than it sounds like atm unfortunately, as you have to create basically a whole new custom heading block to replace the default one:( Feel free to file an issue for this though since I think some people on Discord brought it up as well.

**Comment by YousefED** [comment]
Moved to https://github.com/TypeCellOS/BlockNote/issues/1028
