### ISSUE TITLE
Possible to create forms using BlockNote Editor Custom Blocks?

### ISSUE THREAD

**Issue by rakesh-eltropy** [TypeCellOS/BlockNote#673]
Is it possible to create forms similar to https://tally.so/ using [custom blocks](https://www.blocknotejs.org/docs/custom-schemas/custom-blocks)?

**Comment by YousefED** [comment]
We haven't tried this yet. I think theoretically it should be possible. I'm going to close this issue though as it's not really a bug / feature request
