### ISSUE TITLE
Programmable Visibility for Format Toolbar

### ISSUE THREAD

**Issue by laflechaenelaire** [TypeCellOS/BlockNote#676]
Currently, there is no way to control the visibility state of the format toolbar in Blocknotejs. This becomes a problem in situations where we have a custom formatting toolbar with a button, which, when clicked, displays a control component that needs to have focus on an input or a textarea, or the new component no longer needs the toolbar to be present for UI/UX reasons

I would like for Blocknotejs to offer an option to programmatically control the visibility of the format toolbar.

Here, I present a use case in which I have a custom formatting toolbar, with an AI-style button, similar to Notion. It can be seen how the custom formatting tool blocks the command component.

https://github.com/TypeCellOS/BlockNote/assets/44955121/2b1de3dc-a8a2-45ff-a5c6-4309be989c01

In this case, it would be appropriate to hide the custom formatting toolbar once the AI button has been clicked and the command component rendered.

**Comment by YousefED** [comment]
Makes sense! Awesome work on the editor btw, would love to learn more about what you're building.

I hope to look into this, thanks for reporting

**Comment by devmalcolm** [comment]
Hi, i've been encoutering the same issue with a same approach. Using a popup such as AI-Notion style or whatever makes the toolbar very annoying, i found some workaround, by tweaking the CSS styles of the toolbar but it might not be the best way to do that, i would love to have a function to direcly toggle / display the toolbar does it still in WIP ?

**Comment by matthewlipski** [comment]
You should be able to do this by implementing a [custom formatting toolbar](https://www.blocknotejs.org/examples/ui-components/formatting-toolbar-buttons). Most likely you will want to keep a React state which determines whether the regular toolbar should be shown or your custom component, and have your custom toolbar button change the state. You may also need to use the `useEditorContentOrSelectionChange` hook to reset the state as the user navigates and changes the document.
