### ISSUE TITLE
default style disabled

### ISSUE THREAD

**Issue by ZAJ0711** [TypeCellOS/BlockNote#681]
![企业微信截图_54f5daa4-e673-4aef-9e95-7b565af905a0](https://github.com/TypeCellOS/BlockNote/assets/42256148/41a9fd6e-96aa-4a41-be14-adc42b12e0b1)

**Comment by TrinhCamMinh** [comment]
I face the same problem too.

**Comment by ZAJ0711** [comment]
works thanks
