### ISSUE TITLE
`BlockNoteViewProps` type is not exported

### ISSUE THREAD

**Issue by i-am-chitti** [TypeCellOS/BlockNote#690]
**Describe the bug**
In docs, it is written that`BlockNoteViewProps` type is exported. But, on using it, it's not actually exported. So, its hard to create a generic component in Next.js based approach - https://www.blocknotejs.org/docs/advanced/nextjs where I'm trying to type the editor props. I can do a hardcode but it will have future issues whenever there is any update in props.

**To Reproduce**
Try write `BlockNoteViewProps` in code editor and it won't show up. Also, searched whole code base but it's only referenced in the docs.
<img width="370" alt="image" src="https://github.com/TypeCellOS/BlockNote/assets/60139930/8a7b56ca-d9c8-4dda-b2a6-6bf88d3af62b">

**Misc**
- Node version: 18.18
- Package manager: 9.8.1

**Comment by YousefED** [comment]
Thanks, we'll fix this!
