### ISSUE TITLE
🐛 blockIdentifier can be null

### ISSUE THREAD

**Issue by AntoLC** [TypeCellOS/BlockNote#697]
**Describe the bug**
In a collaborative way, if a user removes the block where another user is located it creates an error.

![image](https://github.com/TypeCellOS/BlockNote/assets/25994652/72dd7b4f-f1fe-47d9-8c07-f3367363c5de)

https://github.com/TypeCellOS/BlockNote/blob/8a5d845407e7bdf63b49fa3b6e4a6d8201e1213a/packages/core/src/editor/BlockNoteEditor.ts#L395

**Possible solution**
```ts
public getBlock(
    blockIdentifier?: BlockIdentifier
```

Thank you.

**Comment by matthewlipski** [comment]
Hi, could you give some more information on how to reproduce this issue?

**Comment by AntoLC** [comment]
Hi, I just checked, since the recent update I don't have the error actually, so all good.

Thank you for your great work!
