### ISSUE TITLE
Space Disappears in Custom Block with Inline Content(Firefox)

### ISSUE THREAD

**Issue by hsingh-ds** [TypeCellOS/BlockNote#705]
**Describe the bug**
When you try to add a space within a custom block with inline content on firefox, the space disappears, and any text added after the space gets concatenated without it. This is working in Chrome.

**To Reproduce**
Here is the [link](https://www.blocknotejs.org/docs/custom-schemas/custom-blocks) of the example that is given on the blocknote website

**Comment by YousefED** [comment]
I think this is a duplicate of https://github.com/TypeCellOS/BlockNote/issues/659
