### ISSUE TITLE
Change font size option in Formatting Toolbar

### ISSUE THREAD

**Issue by keotic** [TypeCellOS/BlockNote#711]
**Describe the solution you'd like**
Add Font Size selection button to the Formatting Toolbar

**Comment by YousefED** [comment]
You can do this yourself by customizing the formatting toolbar: https://www.blocknotejs.org/examples/ui-components/formatting-toolbar-buttons

**Comment by fiderosado** [comment]
i try add or build a custom button to change the text size, but i dont now how start, i recive multiples error about the param fontSize is not on schema, and later, i have a nother error , fontSize on mask, getMaskType ...

https://github.com/TypeCellOS/BlockNote/issues/1619

**Comment by fiderosado** [comment]
Please add font size to styleSchema
