### ISSUE TITLE
Default gray "List" text overlays list item text when having pressed shift + enter on that item

### ISSUE THREAD

**Issue by jelares** [TypeCellOS/BlockNote#713]
**Describe the bug**
On numbered lists, the default gray "List" text will sometimes appear even when the list item is not empty (overlaying).

**To Reproduce**
1. Create a numbered list.
2. Make an item in the numbered list.
3. Press shift + enter.
4. Make a new, second, item in that list.
5. The default gray "List" will be overlaying item one.

Images:
**No bug - list items without shift + enter.**
<img width="194" alt="Screenshot 2024-04-24 at 12 23 50 PM" src="https://github.com/TypeCellOS/BlockNote/assets/43612169/84654a52-8e8b-4d94-ba5e-f5b8edc27174">

**Bug - list items with shift + enter.**
<img width="223" alt="Screenshot 2024-04-24 at 12 23 58 PM" src="https://github.com/TypeCellOS/BlockNote/assets/43612169/8c7dc356-0ce2-434d-a281-fcac7d550feb">

**Misc**
- Node version: v16.19.0
- Package manager: npm
- Browser: Arc browser

**Comment by levonbrunson** [comment]
+1

**Comment by matthewlipski** [comment]
Fixed in 0.14.0! (see #784)

**Comment by jelares** [comment]
Awesome! Thanks for your help guys! Blocknotes is the best!
