### ISSUE TITLE
[Collaboration] Make yjs provider composable

### ISSUE THREAD

**Issue by bojieyang** [TypeCellOS/BlockNote#714]
**Is your feature request related to a problem? Please describe.**

Currently the collaboration structure only support one yjs provider. But the yjs providers are composable. 

For example, I may want to compose y-indexeddb and y-partykit/provider to support offline editing and automatic sync to the server when it is online. yjs support this feature in [it's document](https://docs.yjs.dev/getting-started/allowing-offline-editing), but it can't used in blocknote.
 

**Describe the solution you'd like**

Allow set multi providers in the collaboration structure or other way to make the provider composable .

**Comment by YousefED** [comment]
I'm pretty sure this is supported; just add multiple providers to the document
