### ISSUE TITLE
File drag-and-drop upload

### ISSUE THREAD

**Issue by justicecurcian** [TypeCellOS/BlockNote#715]
**Is your feature request related to a problem? Please describe.**
I want to build an extension to drop files in the editor (images/videos/pdf), upload them to my server and create a block where the file was dropped. There is no way of doing this on the blocknote level as i can see, tiptap extension with this functionality is behind a paywall, and doing this in prosemirror is kinda tricky: you need to replace dropcursor with the new block, and so you need a specific dropcursor for files because dropcursor works inside blocks too. 

**Describe the solution you'd like**
It would be perfect is there was a file drop plugin in blocknote that would handle the file drop itself and the editor would accept a function like 

```javascript
{ // BlockNoteEditorOptions
    fileDropHandler: (file: File) => {
        // User creates the node he needs, or a notification that
        // the editor can't handle a file of that type, handles upload, etc.
    }
}
```

**Describe alternatives you've considered**
`enableBlockNoteExtensions` is kinda useless right now and to make it useful it needs to disable specific extensions. If I can disable dropcursor extension without disabling all other extensions, I will be able to create my own tiptap extension that will handle dropcursor and file upload.

**Comment by justicecurcian** [comment]
I just remembered that blocks have dropcursor only between blocks and it might help me to implement this. I am searching for this in the source and would be happy if anyone tells me where to look more specificly, if i find it i will update this comment.

**Comment by YousefED** [comment]
Hi! Would welcome a PR that makes `enableBlockNoteExtensions` more useful for your scenario. Meanwhile, we'll also be working on better file uploads so that might also address your requirements

**Comment by matthewlipski** [comment]
Seems like we forgot to close this a while ago, should be possible now using the [`uploadFile`](https://github.com/TypeCellOS/BlockNote/pull/1304) editor option
