### ISSUE TITLE
When using the default Mantine components. The theme parameter is invalid.

### ISSUE THREAD

**Issue by unexpectedxx** [TypeCellOS/BlockNote#724]
**Describe the bug**
When using the default Mantine components. The theme parameter is invalid.

**To Reproduce**
[https://stackblitz.com/edit/github-7fmx8f?file=App.tsx](https://stackblitz.com/edit/github-7fmx8f?file=App.tsx)

**Misc**
- Node version:
- Package manager:
- Browser: 
- [ ] I'm a [sponsor](https://github.com/sponsors/YousefED) and would appreciate if you could look into this sooner than later 💖

**Comment by YousefED** [comment]
Seems to be working here? Maybe the stackblitz was using an outdated
version?

If you still hve the issue, can you add a screenshot?

**Comment by YousefED** [comment]
IT wasn't clear what the error was that you were getting. I now see that you're getting a dark editor instead of a light one. Should be fixed in 0.13.1

**Comment by unexpectedxx** [comment]
Okay, thanks.
