### ISSUE TITLE
The Documentation crashed (Got client-side exception)

### ISSUE THREAD

**Issue by Dadangdut33** [TypeCellOS/BlockNote#727]
https://github.com/TypeCellOS/BlockNote/assets/57717531/c0a28deb-1f8a-4435-be83-5ce5ba91609c

<details><summary>Console Log</summary>
<p>
<img src="https://github.com/TypeCellOS/BlockNote/assets/57717531/c6ba6e20-b857-4f98-a2a7-206be3017c9d" />
</p>
</details> 

**Describe the bug**
I was trying to see the documentation about DragHandleMenu and suddenly it crashes. I think The crash happens only when you visit https://www.blocknotejs.org/docs/ui-components/side-menu and hover into the changing the drag handle menu item part.

I also tried using the code just like in the documentation and it also crashes. So it might be related to the new update.

**To Reproduce**
- visit https://www.blocknotejs.org/docs/ui-components/side-menu
- scroll down
- crash

Browser: Vivaldi 6.7.3329.24 (Stable channel) (64-bit)
OS: Windows 11 Version 23H2 (Build 22631.3527)

**Comment by YousefED** [comment]
Thanks! Fixed: https://github.com/TypeCellOS/BlockNote/pull/733
