### ISSUE TITLE
 stackblitz examples crashed

### ISSUE THREAD

**Issue by HiChen404** [TypeCellOS/BlockNote#732]
**Describe the bug**

When I click on the stackblitz examples in the document, I get an error and the editor crashed.

Almost all stackblitz examples have this problem, does anyone know what's going on? 

![image](https://github.com/TypeCellOS/BlockNote/assets/58675561/91050b82-4acb-4f5e-a141-086776457de3)

**To Reproduce**

Checkout this offical example:
> https://www.stackblitz.com/github/TypeCellOS/BlockNote/tree/main/examples/05-custom-schema/02-suggestion-menus-mentions/

**Misc**
- Node version: 18
- Package manager: npm,yarn
- Browser:  chrome,firefox,edge
- [ ] I'm a [sponsor](https://github.com/sponsors/YousefED) and would appreciate if you could look into this sooner than later 💖

**Comment by YousefED** [comment]
Thanks, was able to reproduce this and will look into it

**Comment by noblejasper** [comment]
When I put a Mention on it, I got an error even at hand and the Editor was displayed blank. It would be helpful if you could tell us how to deal with this temporarily.

Is it also the same issue here?
https://github.com/TypeCellOS/BlockNote/issues/750

**Comment by noblejasper** [comment]
@YousefED @HiChen404 
It does not seem to occur with the following versions. At least I did not reproduce it once.

```
    "@blocknote/core": "^0.13.0",
    "@blocknote/mantine": "^0.13.0",
    "@blocknote/react": "^0.13.0",
```

Incidentally, the following version caused this problem

```
    "@blocknote/core": "^0.13.0",
    "@blocknote/mantine": "^0.13.1",
    "@blocknote/react": "^0.13.1",
```

Once I'm done I'll use 0.13.0
