### ISSUE TITLE
Customize BlockNote Editor Placeholder

### ISSUE THREAD

**Issue by pritishmishra703** [TypeCellOS/BlockNote#736]
It would be useful to have the ability to customize the placeholder text in the BlockNote Editor, such as changing the text content, color, and font size.

**Comment by YousefED** [comment]
@pritishmishra703 have you tried achieving this via CSS?

**Comment by softmarshmallow** [comment]
referencing for future endeavors

https://github.com/TypeCellOS/BlockNote/issues/883
