### ISSUE TITLE
Cannot read properties of undefined (reading 'SideMenu')

### ISSUE THREAD

**Issue by AbdullahKhan780** [TypeCellOS/BlockNote#763]
**Describe the bug**

<img width="1792" alt="Screenshot 2024-05-25 at 4 41 10 PM" src="https://github.com/TypeCellOS/BlockNote/assets/68871807/7e910f76-b24f-4c62-b2b6-7c5d6a2b59da">

**Comment by YousefED** [comment]
@AbdullahKhan780 what are the steps to reproduce this?
