### ISSUE TITLE
Even if editable=false, copy and paste will paste strings

### ISSUE THREAD

**Issue by noblejasper** [TypeCellOS/BlockNote#766]
**Describe the bug**

- BlockNoteView in editable=false state
- Selecting a string and performing a copy and paste causes the string to be pasted.

**To Reproduce**
Also reproduced in StackBlitz with editable=false

**Misc**
- Node version: v18.17.1
- Package manager: npm
- Browser: Chrome 

https://github.com/TypeCellOS/BlockNote/assets/75936/c9ad2ce7-4d67-46c1-bca6-6ccc0f0c1989

**Comment by YousefED** [comment]
Thanks @noblejasper , we'll look into this. What are you building with BlockNote btw?

**Comment by noblejasper** [comment]
@YousefED We are still developing it, but we are using it for our corporate SaaS product.
