### ISSUE TITLE
TypeScript errors: `BlockNoteView` has no `editor` prop

### ISSUE THREAD

**Issue by conr** [TypeCellOS/BlockNote#775]
**Describe the bug**

Following the [quickstart](https://www.blocknotejs.org/docs/quickstart) guide for BlockNote, I'm getting the following TypeScript errors stating that props like editor are not valid props for the `BlockNoteView` component (see screenshots attached).

I have installed `@blocknote/core`, `@blocknote/react`, and `@blocknote/mantine` versions `0.13.4`.

I originally posted this in the Discord, and another user reported the same issue.

<img width="212" alt="image" src="https://github.com/TypeCellOS/BlockNote/assets/5826063/700234e7-dc66-47d7-b6d9-fd74b1babf32">

<img width="1038" alt="image" src="https://github.com/TypeCellOS/BlockNote/assets/5826063/7ca0460c-ba41-4074-ae43-0f6b10331924">

**To Reproduce**

**Misc**
- Node version: `v20.13.1`
- Package manager: [Yarn](https://yarnpkg.com/)

**Comment by conr** [comment]
I worked around this for now by wrapping a new custom component:

```tsx
import { BlockNoteEditor } from "@blocknote/core";
import { BlockNoteView } from "@blocknote/mantine";
import React, { HTMLAttributes } from "react";

export type BlockNoteViewProps = {
  editor: BlockNoteEditor;
  editable?: boolean;
  onSelectionChange?: () => void;
  onChange?: () => void;
  theme?: "light" | "dark";
  formattingToolbar?: boolean;
  linkToolbar?: boolean;
  sideMenu?: boolean;
  slashMenu?: boolean;
  filePanel?: boolean;
  tableHandles?: boolean;
  children?: React.ReactNode;
} & HTMLAttributes<HTMLDivElement>;

export const Editor: React.FC<BlockNoteViewProps> = (props) => (
  <BlockNoteView {...props} />
);
```

**Comment by YousefED** [comment]
I can't seem to reproduce this. Are you able to create a stackblitz where this issue occurs?

**Comment by YousefED** [comment]
Closing this, lmk if it still occurs @conr
