### ISSUE TITLE
The suggestion popover doesn't disappear

### ISSUE THREAD

**Issue by trinhle96** [TypeCellOS/BlockNote#778]
**Describe the bug**
I implemented a mentions menu that is triggered by the "@" character in my React project, and it's working great. However, I'm facing an issue in my Next.js project: when I type something that starts with "@", but isn't a mention item, the suggestion popover displaying "No items found" doesn't disappear.
![Screenshot 2024-05-28 143717](https://github.com/TypeCellOS/BlockNote/assets/97581320/765c5f19-19e0-4b85-a8a4-7a6f537f9eed)

**To Reproduce**
stackblitz: https://stackblitz.com/edit/stackblitz-starters-qy4jp9?file=README.md

**Misc**
- Next js version: 14

**Comment by kedarvyas084** [comment]
Hello @trinhle96, In your stackblitz, I was able to get suggestions?
would it be your system's problem?

![image](https://github.com/TypeCellOS/BlockNote/assets/138874486/a57d6318-44b7-455d-aecc-6fbbfc8d7219)

**Comment by trinhle96** [comment]
Hi @kedarvyas084 , Please type until no items are found. Then, add spaces or anything, and the popover won't disappear.

**Comment by trinhle96** [comment]
Hi @YousefED, I tried your fix, and it works great. Thank you so much for your support.
