### ISSUE TITLE
Groups error "Blocos Básicos" and "Blocos básicos"

### ISSUE THREAD

**Issue by Holyblade** [TypeCellOS/BlockNote#803]
Hello,

When using the PT translation, the groups are disarranged due to one of the block categories being in lower case, this creates 3 groups with the same name, causing a cascate error, as the group divs uses the group name as key.

![error](https://github.com/TypeCellOS/BlockNote/assets/61342224/fb39cb3b-ff75-4051-8839-34bdb306d95c)
![multiple groups](https://github.com/TypeCellOS/BlockNote/assets/61342224/a1458511-333d-4454-b2e5-847d07f9bdeb)

I would like to thank you for the wonderful package <3

**Comment by YousefED** [comment]
Thanks. Can you submit a PR for this?
