### ISSUE TITLE
Add support for Uppy for file uploading

### ISSUE THREAD

**Issue by YousefED** [TypeCellOS/BlockNote#807]
**Is your feature request related to a problem? Please describe.**
We'd like to add support for https://uppy.io/ for file uploading. This would require:

**Describe the solution you'd like**
Initially, creating an example (similar to other blocknote examples in the `example` directory would suffice (as part of follow up work, later we could see what we can extract to a reusable package).

The main requirements are:

- [ ] Most important: customize the BlockNote FilePanel to use the Uppy React library (use a `FilePanelController` and the Uppy Dashboard for this)
- [ ] Make sure the `uploadFile` [function](https://www.blocknotejs.org/docs/editor-basics/setup) also uses the uppy pipeline
- [ ] It should be clear in the code where you can configure additional Uppy options such as a companion URL or transloadit server

Of course, it must work for selecting / uploading resources for different blocks (e.g.: File / Image / Video)

**Comment by ezhil56x** [comment]
Can I get assigned?
/attempt #807

**Comment by ezhil56x** [comment]
@YousefED 
It would be great if it is assigned, as it's a feature to be implemented.
Thanks!

**Comment by rajeshj11** [comment]
\attempt #807
