### ISSUE TITLE
`i.view is undefined` with `editor.replaceBlocks` or `editor.removeBlocks`

### ISSUE THREAD

**Issue by ikazaksoftaria** [TypeCellOS/BlockNote#810]
Hello! I want to update content in `BlockNoteView` component. And when I try to replace blocks with Editor API I get this error:

<details>
<summary>TypeError: i.view is undefined</summary>
<img src="https://github.com/TypeCellOS/BlockNote/assets/169999354/096c8259-2501-4690-9de0-e301b0fe687d" alt="log screenshot">
</details>

**Code**
```typescript
export const Content = ({ contentJson }: { contentJson: string }) => {
  const editor = useCreateBlockNote({ initialContent: JSON.parse(contentJson) });

  useEffect(() => {
    try {
      editor.replaceBlocks(editor.document, JSON.parse(contentJson));
    } catch (e) {
      editor.removeBlocks(editor.document);
    }
  }, [editor, contentJson]);

  return <BlockNoteView editor={editor} editable={false} />;
};
```

What is the current working alternative to dynamically update content in `BlockNoteView` component?

**Versions**
@blocknote/shadcn:  "0.13.5"
Node: v18.19.1
System: Manjaro Linux

**Comment by ikazaksoftaria** [comment]
My solution

```typescript

export const Content = ({ contentJson }: { contentJson: string }) => {
  const [editor, setEditor] = useState<BlockNoteEditor>(BlockNoteEditor.create({ initialContent: JSON.parse(contentJson) }));

  useEffect(() => {
    setEditor(BlockNoteEditor.create({ initialContent: JSON.parse(contentJson) }));
  }, [editor, contentJson]);

  return <BlockNoteView editor={editor} editable={false} />
};
```

**Comment by YousefED** [comment]
This is probably an edge case where immediately calling replaceBlocks before the editor has fully initialized throws an error. We'll look into this

**Comment by ikazaksoftaria** [comment]
> This is probably an edge case where immediately calling replaceBlocks before the editor has fully initialized throws an error. We'll look into this

Yes! It does work with `await new Promise((resolve) => setTimeout(resolve, 100));`

```typescript
export const Content = ({ contentJson }: { contentJson: string }) => {
  const editor = useCreateBlockNote({ initialContent: JSON.parse(contentJson) });

  useEffect(() => {
    new Promise((resolve) => setTimeout(resolve, 10)).then(() => {
      try {
        console.log(contentJson);
        editor.replaceBlocks(editor.document, JSON.parse(contentJson));
      } catch (e) {
        editor.removeBlocks(editor.document);
      }
    });
  }, [editor, contentJson]);

  return <BlockNoteView editor={editor} editable={false} />;
};
```

**Comment by YousefED** [comment]
closed by https://github.com/TypeCellOS/BlockNote/pull/909
