### ISSUE TITLE
我如何在编辑器中上传图片和文件进行超链接点击图片实现自动跳转超链接功能？

### ISSUE THREAD

**Issue by zhanghaidi** [TypeCellOS/BlockNote#819]
1、我如何在编辑器中上传的图片和文件进行绑定超链接功能？类似这样：
![image](https://github.com/TypeCellOS/BlockNote/assets/26913173/8f633d83-069f-4162-8ed3-be0f03cde041)

2、我需要实现自定义显示出了多媒体以外的插入功能如：ifram网页，或者 code 和Excalidraw，这很实用，也很重要
![image](https://github.com/TypeCellOS/BlockNote/assets/26913173/6c299552-175d-41d9-bce4-123b0e7cb019)

![image](https://github.com/TypeCellOS/BlockNote/assets/26913173/7552a546-2f8e-4dac-ac79-d1280db2ed2e)

**Comment by matthewlipski** [comment]
1. You can either create your own custom image block and add an `onClick` listener there, or add a listener to the default image blocks whenever the editor updates (you can use `editor.domElement.querySelector('[data-content-type="image"] img')` to get all `img` elements inside image blocks).

2. You will have to implement this yourself as a React component and add it as a child of `BlockNoteView`. The `useEditorContentOrSelectionChange` and `useSelectedBlocks` hooks will be useful to figure out when to show/hide your menu.
