### ISSUE TITLE
In custom blocks , how can I disable the menu when editable is false.

### ISSUE THREAD

**Issue by Akshdhiwar** [TypeCellOS/BlockNote#823]
I am trying to make a custom block as per the docs and now I want when the editable is false I don't want the user to access any of the input fields of the custom block.

As of now I'm referring to this [docs](https://www.blocknotejs.org/docs/custom-schemas/custom-blocks#custom-block-types) to create custom block ( Alert block that is shown in docs)

So their is a menu which is been implemented which I don't want user to interact when editable is false.

![image](https://github.com/TypeCellOS/BlockNote/assets/89899312/4a843745-7a08-46d1-a9ba-f1e3a228c820)

```
<BlockNoteView
          editor={editor}
          editable={false}
          onChange={() => {
            // Saves the document JSON to state.
            setBlocks(editor.document);
          }}
        />
```

So is their anything I'm missing out ? Is there any way I can know the editable is false and disable the menu ??

So need help regarding this , any leads would be appreciated!
Thanks.

**Comment by matthewlipski** [comment]
In the `render` function of your component you have access to `block` and `editor`, so you can use `editor.isEditable` to check whether you want to show or hide the block's menus or input fields. Hope that helps!

**Comment by Akshdhiwar** [comment]
Thanks @matthewlipski for helping , working fine with `props.editor.editable` .
