### ISSUE TITLE
Darkmode not applied in next.js next-themes

### ISSUE THREAD

**Issue by TheMikeyRoss** [TypeCellOS/BlockNote#824]
**Describe the bug**
Switching the theme using `next-themes` don't apply changes to the colors of `BlockNote

**Misc**
- Node version: 18.19.3
- Package manager: pnpm
- Browser: chrome

**Comment by zaaakher** [comment]
Make sure to pass the `resolvedTheme` to `theme` prop in the `BlockNoteView` component.

```jsx
<BlockNoteView
  editor={noteEditor}
  data-note-input
  theme={resolvedTheme as 'light' | 'dark'}
/>
```

and in your `globals.css`

```css
.bn-container[data-note-input][data-color-scheme="dark"] {
   /* styles when theme is dark*/ 
}
.bn-container[data-note-input][data-color-scheme="light"] {
   /* styles when theme is light */ 
}
```

Make sure to use the css variables mentioned [here](https://www.blocknotejs.org/docs/styling-theming/themes#theme-css-variables)

**Comment by TheMikeyRoss** [comment]
That's exactly what i'm looking for, thank you @zaaakher
