### ISSUE TITLE
`tryParseMarkdownToBlocks` not parsing checklists

### ISSUE THREAD

**Issue by TheMikeyRoss** [TypeCellOS/BlockNote#826]
**Describe the bug**
I'm parsing a markdown to blocks and it works fine but it seems to be missing the checkboxes (see attached image

![image](https://github.com/TypeCellOS/BlockNote/assets/97709651/7237fe8e-e9c2-489e-a055-75ead2debe49)

**Misc**
- Node version: 18.19.3
- Package manager: pnpm
- Browser: chrome

**Comment by matthewlipski** [comment]
I was scratching my head with this a little as well, but turns out things are actually being parsed correctly according to the [GitHub flavoured Markdown spec](https://github.github.com/gfm/#task-list-items-extension-). You just need to have a space in between the brackets as shown in the example.

**Comment by TheMikeyRoss** [comment]
@matthewlipski But I didn't manually type the brackets I literally just fetched them from my DB and parsed with `tryParseMarkdownToBlocks`. To replicate my issue:

1- In blocknote, click the plus button to open the dropdown menu and select checklist
2- Start typing and you'll see an actual checkbox in every line your write (not brackets, but actual interactive checkboxes)
3- Save the content you wrote in a database using graphql or whatever, or maybe even a react state temporarily 
4- Parse that content you saved using `tryParseMarkdownToBlocks` and it will look like the screenshot above

I didn't add or remove any spaces between any brackets.

**Comment by TheMikeyRoss** [comment]
I just checked directly in my mongoDB and it has a space between the brackets:

![image](https://github.com/TypeCellOS/BlockNote/assets/97709651/775ac42b-b4e5-4480-b2b1-e2d03b1374ff)

but when parsed in the client ui:

![image](https://github.com/TypeCellOS/BlockNote/assets/97709651/be287e69-d7fa-4526-99e1-2ac858bbe793)


I consoled logged the notes (before parsing it) and it looks fine with a space between the brackets:

![image](https://github.com/TypeCellOS/BlockNote/assets/97709651/2a85b17b-8410-45c4-9dd5-5e62a777c946)

So I'm fairly confident the `tryParseMarkdownToBlocks` is removing a space between the brackets or doing something else wrong

**Comment by TheMikeyRoss** [comment]
![image](https://github.com/TypeCellOS/BlockNote/assets/97709651/d9bb13e0-b525-4ae8-adba-67db9c13568e)
the console.log is showing that there's a space between the brackets, but the `tryParseMarkdownToBlocks` isn't

**Comment by TheMikeyRoss** [comment]
@matthewlipski or maybe it's `replaceBlocks` that's removing the space between brackets?

**Comment by TheMikeyRoss** [comment]
@matthewlipski Oops my bad, the problem is in `replaceBlocks` and not `tryParseMarkdownToBlocks`

I console logged the parsed blocks and it's keeping the space between the brackets 
![image](https://github.com/TypeCellOS/BlockNote/assets/97709651/3c8840d5-a9e0-4ce4-a6b7-28940481bf9f)


So the problem is 100% coming from `replaceBlocks`

**Comment by matthewlipski** [comment]
Nice find, thanks for diving into this!
