### ISSUE TITLE
architecture: make it possible to manipulate blocks before view is instantiated

### ISSUE THREAD

**Issue by YousefED** [TypeCellOS/BlockNote#833]
At this moment, we can't call functions like `updateBlock` `replaceBlocks` etc (see https://www.blocknotejs.org/docs/editor-api/manipulating-blocks) before the view is set up

See issues:

closes https://github.com/TypeCellOS/BlockNote/issues/810
closes https://github.com/TypeCellOS/BlockNote/issues/633
closes https://github.com/TypeCellOS/BlockNote/issues/439

**Comment by TheMikeyRoss** [comment]
Hi @YousefED any update on this one? do you need help with someting?

**Comment by YousefED** [comment]
closed by https://github.com/TypeCellOS/BlockNote/pull/909
