### ISSUE TITLE
`replaceBlocks` is removing the space between brackets for checklists

### ISSUE THREAD

**Issue by TheMikeyRoss** [TypeCellOS/BlockNote#834]
**Describe the bug**
the method `replaceBlocks` is removing the space between the brackets of a checklist which should cause it to render an actual interactive checkbox.

**To Reproduce**
This issue is broken down in this thread https://github.com/TypeCellOS/BlockNote/issues/826#issuecomment-2162085998

**Misc**
- Node version: 18.19.3
- Package manager: pnpm
- Browser: chrome

**Comment by zaaakher** [comment]
It seems the `\` escape is the culprit here

![blocknote-escape-checklist](https://github.com/TypeCellOS/BlockNote/assets/46135573/e27447df-d52c-4d84-9ef9-d61327397bd4)

**Comment by zaaakher** [comment]
It seems `blocksToMarkdownLossy` is adding the `\` escape before the brackets.
![blocknote-escape-checklist-cause](https://github.com/TypeCellOS/BlockNote/assets/46135573/baf435ae-a584-4e66-be80-64267319d125)


@TheMikeyRoss Just to confirm, are you using `blocksToMarkdownLossy` to convert the blocks to markdown before you upload them to your DB?

**Comment by TheMikeyRoss** [comment]
> are you using blocksToMarkdownLossy to convert the blocks to markdown

@zaaakher Yes exactly!
