### ISSUE TITLE
bug: toolbar strike shortcut tooltip

### ISSUE THREAD

**Issue by 2sjeong918** [TypeCellOS/BlockNote#844]
**Describe the bug**
I think the Strike shortcut tooltip is wrong. 
Actually, the shortcut that works is `cmd+shift+S`. I think it'd be nice to fix it

<img width="536" alt="image" src="https://github.com/TypeCellOS/BlockNote/assets/28250027/89051155-5e0e-415e-813f-0f65594ef8b8">

**Misc**
- react: ^18.2.0,
- BlockNote: ^0.14.0

Thank you

**Comment by mkspcd** [comment]
On macOs, I confirm that the shortcut that works is `cmd+shift+S`.
It is probably just a change to make in the dictionaries.
(All dictionaries are affected.)

```
strike: {
  tooltip: 'Strike',
  secondary_tooltip: 'Mod+Shift+X',
},
```
