### ISSUE TITLE
Bug: Display Create Link Toolbar when state editor is non-editable

### ISSUE THREAD

**Issue by lamtuanamc** [TypeCellOS/BlockNote#850]
**Describe the bug:**
In debug mode, the "Create Link" button in the toolbar is clickable when I highlight text,
even though the editor state is set to non-editable and the formattingToolbar prop is set to false.

_This issue has not been observed in the production environment._

https://github.com/TypeCellOS/BlockNote/assets/37234239/542a3768-38c9-4a06-9657-ff907ea539ad

**Comment by matthewlipski** [comment]
Hmm I can't seem to reproduce this on either the built or dev environment. Could you create a sandbox to see if this issue is specific to your project?

**Comment by lamtuanamc** [comment]
@matthewlipski I have customized CreateLinkButton.tsx so when you update the core library to display the button to download files and images,
I'm missing the conditions to display the button to create this link.
Sorry for the lack of information.

<img width="750" alt="Screenshot 2024-06-20 at 10 31 18" src="https://github.com/TypeCellOS/BlockNote/assets/37234239/10386534-b954-4013-9dca-547a783ec5bf">
