### ISSUE TITLE
SuggestionMenu , sideMenu

### ISSUE THREAD

**Issue by Munna5553** [TypeCellOS/BlockNote#861]
<html>
<body>
<div aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; outline-width: 0px; flex: 0 0 auto; color: rgb(227, 227, 227); font-family: monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(78, 53, 52); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span class="console-message-anchor" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: right; text-align: right; max-width: 100%; margin-left: 4px;"><button class="devtools-link text-button link-style ignore-list-link" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="http://localhost:5173/node_modules/react-dom/cjs/react-dom.development.js:12056" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;"><br class="Apple-interchange-newline">react-dom.development.js:12056</button> </span><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-error-text-color) !important;">Uncaught <span class="object-value-error source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><div style="box-sizing: border-box; min-width: 0px; min-height: 0px;">TypeError: Cannot read properties of undefined (reading 'SuggestionMenu')
<span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at Er (<button class="devtools-link text-button link-style ignore-list-link" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="http://localhost:5173/node_modules/@blocknote/react/src/components/SuggestionMenu/SuggestionMenu.tsx:16:19" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;">SuggestionMenu.tsx:16:19</button>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at renderWithHooks (<button class="devtools-link text-button link-style ignore-list-link" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="http://localhost:5173/node_modules/react-dom/cjs/react-dom.development.js:15486:18" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;">react-dom.development.js:15486:18</button>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at mountIndeterminateComponent (<button class="devtools-link text-button link-style ignore-list-link" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="http://localhost:5173/node_modules/react-dom/cjs/react-dom.development.js:20103:13" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;">react-dom.development.js:20103:13</button>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at beginWork (<button class="devtools-link text-button link-style ignore-list-link" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="http://localhost:5173/node_modules/react-dom/cjs/react-dom.development.js:21626:16" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;">react-dom.development.js:21626:16</button>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at beginWork$1 (<button class="devtools-link text-button link-style ignore-list-link" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="http://localhost:5173/node_modules/react-dom/cjs/react-dom.development.js:27465:14" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;">react-dom.development.js:27465:14</button>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at performUnitOfWork (<button class="devtools-link text-button link-style ignore-list-link" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="http://localhost:5173/node_modules/react-dom/cjs/react-dom.development.js:26596:12" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;">react-dom.development.js:26596:12</button>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at workLoopSync (<button class="devtools-link text-button link-style ignore-list-link" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="http://localhost:5173/node_modules/react-dom/cjs/react-dom.development.js:26505:5" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;">react-dom.development.js:26505:5</button>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at renderRootSync (<button class="devtools-link text-button link-style ignore-list-link" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="http://localhost:5173/node_modules/react-dom/cjs/react-dom.development.js:26473:7" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;">react-dom.development.js:26473:7</button>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at recoverFromConcurrentError (<button class="devtools-link text-button link-style ignore-list-link" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="http://localhost:5173/node_modules/react-dom/cjs/react-dom.development.js:25889:20" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;">react-dom.development.js:25889:20</button>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at performSyncWorkOnRoot (<button class="devtools-link text-button link-style ignore-list-link" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="http://localhost:5173/node_modules/react-dom/cjs/react-dom.development.js:26135:20" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;">react-dom.development.js:26135:20</button>)</span></div></span></span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(227, 227, 227); font-family: monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(78, 53, 52); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="monospace stack-preview-container width-constrained" style="display: inline-block; --monospace-font-size: 12px; --monospace-font-family: monospace; --source-code-font-size: 12px; --source-code-font-family: monospace; width: 461.4px; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size) !important;">
  | Show 12 more frames
-- | --

</span></div>
</body>
</html>
![Screenshot 2024-06-24 132318](https://github.com/TypeCellOS/BlockNote/assets/95542004/09abd144-b5fb-45ce-942c-8af7e35bf468)

**Comment by matthewlipski** [comment]
Hi, can you provide more details about this please? Code snippet/sandbox, bundler used, when the error gets thrown, etc?

**Comment by Munna5553** [comment]
import { BlockNoteEditor, PartialBlock } from "@blocknote/core";
import { useCreateBlockNote } from "@blocknote/react";
import { BlockNoteView } from "@blocknote/mantine"
import "@blocknote/mantine/style.css";


interface editorProps {
    initialContent?: string;
    editable?: boolean;
}

const TextEditor: React.FC<editorProps> = ({ initialContent, editable }) => {

    const editor = useCreateBlockNote({
        initialContent: initialContent ? (JSON.parse(initialContent) as PartialBlock[]) : undefined,
    }) as BlockNoteEditor;

    return (
        <BlockNoteView
            onChange={() => { console.log(JSON.stringify(editor.domElement.innerHTML)) }}
            editor={editor}
            editable={editable}
            theme={"light"}
        />
    )
}

export default TextEditor;

how to get the data where is use/call this component,

----------------------------------------------------------------------------------------------------------------------
please update documentation -> how to implement in typescript
this editor is not working in reactjs without 
  import { BlockNoteView } from "@blocknote/mantine"
import "@blocknote/mantine/style.css";
but its work with nextjs
--------------------------------------------------------------------------------------------------------------------------
please a clear doc which is really helpful us.
