### ISSUE TITLE
Issue: Improve Documentation for TypeScript Projects and Usage Instructions

### ISSUE THREAD

**Issue by Munna5553** [TypeCellOS/BlockNote#866]
The current documentation lacks details on how to use the component with TypeScript projects. Additionally, there are several issues and points of confusion that need to be addressed:

TypeScript Integration:

Please provide detailed instructions on how to integrate this component into a TypeScript project.
Include the necessary prop types and examples in the documentation.
Retrieving Content:

Provide a clear example of how to get the content where the user calls this component.
Ensure that the example includes both the implementation and the expected output.
ReactJS Usage:

The component throws an error if Mantine is not installed in a ReactJS project, but it works without Mantine in a Next.js project. Please clarify the dependencies and provide consistent instructions for both environments.
Styling Issues:

When using the component, the styles are not applied correctly, causing the content to break. Provide troubleshooting steps and examples to ensure that the styles are applied correctly.

![Screenshot 2024-06-26 010041](https://github.com/TypeCellOS/BlockNote/assets/95542004/09bf30f0-85b6-4c7a-85ea-7a79f45f5415)

**Comment by YousefED** [comment]
Can you share a Stackblitz or github repo that reproduces your issues? Curious to see exactly what you're running into
