### ISSUE TITLE
Missing ts type for `disableExtensions`

### ISSUE THREAD

**Issue by softmarshmallow** [TypeCellOS/BlockNote#881]
Cannot find a doc athttps://www.blocknotejs.org/docs, I cannot find a way to disable the table extension.

```ts
const editor = useCreateBlockNote({
    disableExtensions: ["table"],
});
```

Above will throw error

```
TypeError: Cannot read properties of undefined (reading 'name')
```

**Comment by matthewlipski** [comment]
You should be able to do this by just removing the table block from the schema, as it bundles all supporting nodes with it:
```tsx
const { table, ...remainingSpecs } = defaultBlockSpecs;
const schema = BlockNoteSchema.create({
  blockSpecs: remainingSpecs,
});

const editor = useCreateBlockNote({
  schema,
});
```

**Comment by softmarshmallow** [comment]
Great ! that works. although, when I set schema, I'm not able to set `initialContent` - Simply ts-ignore it?

<img width="337" alt="Screenshot 2024-06-30 at 7 02 56 PM" src="https://github.com/TypeCellOS/BlockNote/assets/16307013/e2c89c32-089d-447a-91db-268f054f8f70">

**Comment by matthewlipski** [comment]
Ah yeah, probably your `initialContent` also needs a type argument. Normally, when you have the type `Block[]` for `initialContent`, it uses the default block schema. But since you're now using a modified schema, you should give it the appropriate type argument:

```tsx
const { table, ...remainingSpecs } = defaultBlockSpecs;
const schema = BlockNoteSchema.create({
  blockSpecs: remainingSpecs,
});

const initialContent: Block<typeof schema.blockSchema>[] = [];

const editor = useCreateBlockNote({
  schema,
  initialContent,
});

return <BlockNoteView editor={editor} />;
```
