### ISSUE TITLE
Disable options

### ISSUE THREAD

**Issue by a-Bokhari118** [TypeCellOS/BlockNote#897]
**Is your feature request related to a problem? Please describe.**
I don't want the user to upload audio.

**Describe the solution you'd like**
Toggle options like enable-disable audio or file uploads

**Comment by YousefED** [comment]
/bounty 15

This is possible by changing the schema (see https://www.blocknotejs.org/docs/custom-schemas). It would be great if someone can add an example (https://www.blocknotejs.org/examples) that shows how to modify the default schema by - in this case - removing the audio block

**Comment by hunxjunedo** [comment]
/attempt #897 having recently contributed to a similar issue, I can work on this. Kindly assign.

**Comment by sid-sg** [comment]
/attempt #897 

I've recently worked on a similar issue where I had to remove Video, Audio and File upload options and only have Image upload option from Media upload.

Preview of my work:

![bandicam2024-07-0314-57-43-903-ezgif com-video-to-gif-converter](https://github.com/TypeCellOS/BlockNote/assets/139637931/c38e2969-f4c6-4010-8ab9-a7ef7c6a5553)

**Comment by hunxjunedo** [comment]
UPDATE: found the solution, proceeding to adding the example to Blocknote website.
