### ISSUE TITLE
SideMenu Shadcn major bug

### ISSUE THREAD

**Issue by sdrrv** [TypeCellOS/BlockNote#911]
**Describe the bug**
When you hover the drag-menu of the side-menu while using the shadcn variation of the blocknote the side-menu completely disappears and does not come back until reloaded.

**To Reproduce**
You can use the official docs here: [BlockNote with ShadCN and Tailwind](https://www.blocknotejs.org/docs/advanced/shadcn)
Just try to use the drag-menu.

- [ ] I'm a [sponsor](https://github.com/sponsors/YousefED) and would appreciate if you could look into this sooner than later 💖

**Comment by rodamora** [comment]
I am having the same bug.

**Comment by ShaquibKhanhub** [comment]
> I am having the same bug. If I remove the import '@blocknote/shadcn/style.css' the menu works.
> 
> When you click to open the side menu and moves the mouse. The menu disappears.
> 
> ![image](https://private-user-images.githubusercontent.com/5985458/347492172-4748b6bb-1720-4e2f-895f-439b858abd72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4OTEyOTgsIm5iZiI6MTcyMDg5MDk5OCwicGF0aCI6Ii81OTg1NDU4LzM0NzQ5MjE3Mi00NzQ4YjZiYi0xNzIwLTRlMmYtODk1Zi00MzliODU4YWJkNzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTNUMTcxNjM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmY1NTE3YmQ2YmE1NDE4NTFlODczYzk3YzFjYzYyODZjNjVlNzcwN2VkYTAzNDJmMmIzMDIxNzc1ZjJiZmI3ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ONp61UMFhvVvOdlQC27EbUNFw_s-dGqWMpvDlCKAPbs)

Getting the same error like TypeError: Cannot read properties of undefined (reading 'SideMenu') donno why im too much frustrated with this
