### ISSUE TITLE
Need Help: Converting JSON to HTML in Blocknote

### ISSUE THREAD

**Issue by zmind1** [TypeCellOS/BlockNote#917]
I'm new to programming and I'm using BlockNote as a text editor. I'm facing an issue: there's no function to convert JSON back to HTML. Is there a way to achieve this? Maybe I'm missing something in the documentation, but I can't find any mention of a function that does this. I want to save the content as JSON and then convert it back to HTML on the server side before sending it to the browser.

**Comment by YousefED** [comment]
see #451
