### ISSUE TITLE
Custom Formatting Toolbar  input loss focus

### ISSUE THREAD

**Issue by yanggggjie** [TypeCellOS/BlockNote#918]
**Describe the bug**
an  input  element at custom formatting toolbar will loss focus when keydown

**To Reproduce**

https://stackblitz.com/edit/github-phps2m?file=App.tsx

select some text and input something at the formatting toolbar input element

**Comment by tabascospicy** [comment]
Hi! Nice to meet you, I'm new around here and just was passing by for curiosity to learn bit by bit about the project, If you allow me to make a suggestion I would say to check how you are rendering the toolbar because in this case:
```javascript
return
 <BlockNoteView editor={editor} formattingToolbar={false}>
     <FormattingToolbarController
            formattingToolbar={() => (
              <FormattingToolbar>
                  ...
              </FormattingToolbar>
            )}
          />
</BlockNoteView>
```
each render the `() => <FormattingToolbar>` creates a new reference to the component which ends with the focus lost
it should work if you separate the toolbar component like this in order to not lose the reference on each render

```javascript
//  another component 
const FormatingToolBarComponent = () =>{
  return  <FormattingToolbar>
                  ...
              </FormattingToolbar>
}

//  then use it here 
 return
 <BlockNoteView editor={editor} formattingToolbar={false}>
     <FormattingToolbarController
           /*  this way should work */
            formattingToolbar={FormatingToolBarComponent }
          />
</BlockNoteView>
```

**Comment by yanggggjie** [comment]
> Hi! Nice to meet you, I'm new around here and just was passing by for curiosity to learn bit by bit about the project, If you allow me to make a suggestion I would say to check how you are rendering the toolbar because in this case:你好！很高兴见到你，我是这里的新人，只是出于好奇而路过，想一点一点地了解这个项目，如果你允许我提出建议，我会说检查一下你是如何渲染工具栏的，因为在这种情况下:
> 
> ```js
> return
>  <BlockNoteView editor={editor} formattingToolbar={false}>
>      <FormattingToolbarController
>             formattingToolbar={() => (
>               <FormattingToolbar>
>                   ...
>               </FormattingToolbar>
>             )}
>           />
> </BlockNoteView>
> ```
> 
> each render the `() => <FormattingToolbar>` creates a new reference to the component which ends with the focus lost每次渲染 `() => <FormattingToolbar>` 都会创建一个对组件的新引用，该引用以失去焦点结束 it should work if you separate the toolbar component like this in order to not lose the reference on each render 如果您像这样分离工具栏组件，以便不丢失每个渲染的引用，它应该可以工作
> 
> ```js
> //  another component 
> const FormatingToolBarComponent = () =>{
>   return  <FormattingToolbar>
>                   ...
>               </FormattingToolbar>
> }
> 
> //  then use it here 
>  return
>  <BlockNoteView editor={editor} formattingToolbar={false}>
>      <FormattingToolbarController
>            /*  this way should work */
>             formattingToolbar={FormatingToolBarComponent }
>           />
> </BlockNoteView>
> ```

**Comment by YousefED** [comment]
@matthewlipski maybe we should also extract all the inline components from the examples as a best practice
