### ISSUE TITLE
dev-scripts path issue on Windows

### ISSUE THREAD

**Issue by zaaakher** [TypeCellOS/BlockNote#955]
**Describe the bug**
Running `npm run gen` throws the following error on Windows:

![image](https://github.com/user-attachments/assets/548b66b7-a285-40a2-b16c-b870e9f95cc1)

**To Reproduce**
- Be on Windows 10
- Run `npm install`
- Run `npm run gen` from the root of the project or from examples dir
- See the same error as the screenshot above

**Misc**
- Node version: 18.20.3
- Package manager: pnpm
- Browser: Chrome
- [ ] I'm a [sponsor](https://github.com/sponsors/YousefED) and would appreciate if you could look into this sooner than later 💖

---

I was hitting my head for an hour trying to figure this one out. When I comment out `fs.writeFileSync` the error is gone, and this seems to be originating from the way we're getting the path/dir :

```
const dir = path.parse(import.meta.url.replace("file://", "")).dir;
```

This issue is in every instance of the above code, in `gen.ts`, `genDocs.ts`, and `util.ts`

---
I was only able to generate the example code in #954 using my MacOS. So this issue is exclusively on Windows.

**Comment by zaaakher** [comment]
@jkcs That silenced the error but it doesn't seem to be actually generating the examples.gen.tsx due to `getExampleProjects` not finding any example files due to it not knowing the exact path

**Comment by zaaakher** [comment]
> try this：https://github.com/TypeCellOS/BlockNote/pull/818/files#diff-93421da21c480705d1154839957c6737a254abe9cc85a0e91f792ce42627e17e

That only silenced the errors. But unfortunately it can't read any example directories which makes it an empty example object for `examples.gen.tsx`

**Comment by matthewlipski** [comment]
Ah yeah, I was also running into this when I was working on Windows way back. Basically, `node:path` handles Windows and MacOS paths pretty differently and it's just kind of a pain. Unfortunately the solution that was most convenient for me was removing all `path` calls and replacing them with hardcoded strings:(
