### ISSUE TITLE
During input, when the `editor.updateBlock()` method is called, the cursor jumps to the end of the paragraph

### ISSUE THREAD

**Issue by qweqwezxcasdsadzxc** [TypeCellOS/BlockNote#957]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Bonus**
[ ] I'm a [sponsor](https://github.com/sponsors/YousefED) and would appreciate if you could look into this sooner than later 💖

**Comment by zaaakher** [comment]
Is this spam?

**Comment by matthewlipski** [comment]
Translation: During input, when the editor.updateBlock() method is called, the cursor jumps to the end of the paragraph

Please post issues in English next time

**Comment by soranoo** [comment]
@matthewlipski Would you mind editing the issue title into English? ❤️

**Comment by YousefED** [comment]
Please next time report the issue in english and fill in the template
