### ISSUE TITLE
Emoji doesn't work in your demo

### ISSUE THREAD

**Issue by elfeffe** [TypeCellOS/BlockNote#959]
**Describe the bug**
There is no emoji menu

**To Reproduce**
Visit this, and you will see it doesn't work https://www.blocknotejs.org/docs/advanced/grid-suggestion-menus

**Comment by arex18** [comment]
Also,

> **Describe the bug** There is no emoji menu
> 
> **To Reproduce** Visit this, and you will see it doesn't work https://www.blocknotejs.org/docs/advanced/grid-suggestion-menus

Also reproducible with [Grid Mentions Menu](https://www.blocknotejs.org/examples/ui-components/suggestion-menus-grid-mentions).

**Comment by matthewlipski** [comment]
A bit confusing, but actually it is working, you just need to start writing a query for it to appear. This is intentional as the `:` character is more likely to be used regularly in text instead of for opening the emoji menu, but this behaviour isn't super obvious.

**Comment by arex18** [comment]
> A bit confusing, but actually it is working, you just need to start writing a query for it to appear. This is intentional as the `:` character is more likely to be used regularly in text instead of for opening the emoji menu, but this behaviour isn't super obvious.

I was aware that it pops open when you start typing, didn't know it was intentional. Can it be considered as an enhancement to enable a feature flag to show the menu or perhaps pass a callback function to a user defined React function?

**Comment by matthewlipski** [comment]
You should already be able to do this like so:
```
<BlockNoteView editor={editor} emojiPicker={false}>
  <GridSuggestionMenuController
    triggerCharacter={":"}
    columns={10}
    // Set the nr of characters in the query to show the emoji picker here
    minQueryLength={0}
  />
</BlockNoteView>
```

**Comment by elfeffe** [comment]
> You should already be able to do this like so:
> 
> ```
> <BlockNoteView editor={editor} emojiPicker={false}>
>   <GridSuggestionMenuController
>     triggerCharacter={":"}
>     columns={10}
>     // Set the nr of characters in the query to show the emoji picker here
>     minQueryLength={0}
>   />
> </BlockNoteView>
> ```

But it's in your demo where it doesn't work.

**Comment by matthewlipski** [comment]
All the demos for the Grid Suggestion Menu use `minQueryLength={2}`, here's an example where it's set to 0 instead:
https://stackblitz.com/edit/github-jwjjy6-asgrut?file=App.tsx

**Comment by elfeffe** [comment]
@matthewlipski you should say that, it seems like the editor is not working properly.
