### ISSUE TITLE
Autofocus doesn't work outside of documentation

### ISSUE THREAD

**Issue by palbrecht1** [TypeCellOS/BlockNote#960]
**Describe the bug**
In the examples in the documentation, if you click anywhere below the editor, it will automatically focus the editor on the 'Enter text or type "/" for commands' placeholder.

If you replicate the code in the documentation or go to the stackblitz from the doc, this behaviour does not exist.

Here's a short loom video showing this: https://www.loom.com/share/0b8e3e3687a74ece9764fb4d87c65d92

**To Reproduce**
Go on this stackblitz from the documentation and try to click outside of block 3:

https://stackblitz.com/github/TypeCellOS/BlockNote/tree/main/examples/01-basic/06-selection-blocks?file=App.tsx

**Misc**
- Node version: 20.5.0
- Package manager: NPM 9.8.0
- Browser: Chrome 126

**Comment by matthewlipski** [comment]
Ah, this is actually just a CSS thing - you can see what the difference is when setting the `.bn-editor` element has a border or background color (e.g. when using dark mode). In the base demo code, `.bn-editor`'s height is set to `auto`, so it depends on how many blocks are in the editor. However, the website adds additional CSS to the examples to make the height of `.bn-editor` fixed. So in the website example, you're actually always clicking on the editor whereas that's not the case in the StackBlitz demo.

**Comment by palbrecht1** [comment]
Thanks a lot @matthewlipski
