### ISSUE TITLE
Emoji item in slash menu does nothing

### ISSUE THREAD

**Issue by danielrearden** [TypeCellOS/BlockNote#963]
**Describe the bug**
Nothing happens when clicking the emoji item in the slash menu. That's because when calling `editor.openSelectionMenu`, we still consider the `minQueryLength` passed to `GridSuggestionMenuController`. Setting this value to `0` makes calling `editor.openSelectionMenu` behave as expected, but is not desirable because now the `minQueryLength` is not enforced when you type `:`.

**To Reproduce**
* Go to https://www.blocknotejs.org
* Open the slash menu
* Select the emoji item

**Misc**
- Node version: 22.4.1
- Package manager: pnpm
- Browser: Chrome
- [ ] I'm a [sponsor](https://github.com/sponsors/YousefED) and would appreciate if you could look into this sooner than later 💖

**Comment by ats1999** [comment]
Same, emojies aren’t working

**Comment by danielrearden** [comment]
FWIW, Notion does not actually open the suggestions menu for this action. Instead, it just inserts a `:`, which seems like a cleaner experience anyway.

**Comment by danlupascu** [comment]
Hey, any updates on this? Do you guys need help?

**Comment by matthewlipski** [comment]
Currently WIP in #984, looks close to being done so likely to be fixed in next release👍
