### ISSUE TITLE
Block Content Duplicated at Bottom of Page on Drag

### ISSUE THREAD

**Issue by hspak** [TypeCellOS/BlockNote#966]
**Describe the bug**
When drag-and-dropping, the contents are duplicated at the bottom of the page.

**To Reproduce**
1. Drag something by the side menu.
2. (Notice the scrollbar appear on your site.)
3. Try to scroll down to the bottom and you'll see the content.

**Misc**
- Blocknote versions
  ```
  "@blocknote/core": "0.15.2",
  "@blocknote/mantine": "0.15.2",
  "@blocknote/react": "0.15.2",
  ```
- Node version: v22.4.0
- Package manager: Bun
- Browser: Chrome
- [X] ~I'm~ [My company](https://github.com/poggiolabs) is a [sponsor](https://github.com/sponsors/YousefED) and would appreciate if you could look into this sooner than later 💖

Replicated on the [demo site](https://blocknote-main.vercel.app/ui-components/side-menu-drag-handle-items): https://www.loom.com/share/76261f0754754622ab7ecfc8197cebd2

**Comment by wardch** [comment]
![Screenshot 2024-07-27 at 7 54 31 AM](https://github.com/user-attachments/assets/3af87cd4-e345-4cb8-8d46-eb73ef56ef5a)

I am seeing this issue too, but content duplicates and appears to the top left of my screen, when I drag and drop and element.

**Comment by YousefED** [comment]
Thanks! We'll look into it this week
