### ISSUE TITLE
When the slash menu expands upwards, there is a display issue when it gets filtered.

### ISSUE THREAD

**Issue by BYODKM** [TypeCellOS/BlockNote#967]
**Describe the bug**

`No items found` should be next to the slash menu.

<img width="1573" alt="Screenshot 2024-07-29 at 11 10 49 AM" src="https://github.com/user-attachments/assets/c0570a61-8ba3-4a4c-9022-f7f9c2e907a0">

**To Reproduce**

I found it here today.
https://www.blocknotejs.org/examples/basic/minimal

**Misc**
- Browser: Mac Chrome Version 126.0.6478.183
- [ ] I'm a [sponsor](https://github.com/sponsors/YousefED) and would appreciate if you could look into this sooner than later 💖

**Comment by govindup63** [comment]
which part of codebase is responsible for the core behaviour of the SuggestionMenu. i have figured out the solution but don't know which part of code is causing that issue

**Comment by YousefED** [comment]
> which part of the codebase is responsible for the core behaviour of the SuggestionMenu? i have figured out the solution but don't know which part of the code is causing that issue

You can find this mostly here: https://github.com/TypeCellOS/BlockNote/tree/main/packages/react/src/components/SuggestionMenu

and partly in the mantine/shadcn/ariakit packages
