### ISSUE TITLE
Emoji Slash - lack of identification and bug

### ISSUE THREAD

**Issue by sathish851** [TypeCellOS/BlockNote#975]
**Describe the bug**

After selecting the **Emoji** option from the /. it still showing that **use / command**. 
**:** operation perfectly for emoji, better if the : is added as default when the Emoji option is selected.

![image](https://github.com/user-attachments/assets/8c18ff8b-6e88-4a36-8a49-1e04290e2f8a)

**Comment by AlexBSoft** [comment]
How i can remove the emoji picker from menu? It is does not works with : or / or from menu (does nothing when i click on it)

**Comment by matthewlipski** [comment]
Yeah agreed the UX for this is not great atm, the emoji picker only appears once you start typing after selecting the slash menu item. You can remove it like this:

```tsx
<BlockNoteView editor={editor} slashMenu={false}>
  <SuggestionMenuController
    triggerCharacter={"/"}
    getItems={async (query) =>
      filterSuggestionItems(getDefaultReactSlashMenuItems(editor).filter((item) => item.title !== "Emoji"), query)
    }
  />
</BlockNoteView>
```
