### ISSUE TITLE
Blocknote's PartyKit development server is 404

### ISSUE THREAD

**Issue by romatallinn** [TypeCellOS/BlockNote#982]
**Describe the bug**
The [documentation](https://www.blocknotejs.org/docs/advanced/real-time-collaboration#partykit) offers the use of Blocknote's own PartyKit server for development purposes.
Accessing it, however, results in 404. 

**To Reproduce**
- Go to [`blocknote-dev.yousefed.partykit.dev`](blocknote-dev.yousefed.partykit.dev).
- Or paste it in a sample project as provider.
- Observer `Error during WebSocket handshake: Unexpected response code: 404`

**Conclusion**
Either documentation should be updated to exclude it from offering. Or the server should be re-launched/fixed.

**Comment by YousefED** [comment]
Thanks. I've redeployed this, I think it should be working again!
