### ISSUE TITLE
Request for Custom Styling Options on Inline Components

### ISSUE THREAD

**Issue by Dhruvagwal** [TypeCellOS/BlockNote#983]
I've been using Blocknote and find it to be an excellent tool. One feature I'd love to see is the ability to apply styling options like bold and italic to custom inline components. This enhancement would provide more flexibility in formatting and enhance the overall user experience.

**Comment by YousefED** [comment]
You should be able to accomplish this with custom styles: https://www.blocknotejs.org/docs/custom-schemas/custom-styles
